<? require("../../../../lib/common.php"); ?>
<? require("../../../../lib/config.php"); ?>
<? require("../../generico/busca_nome.php3"); ?>

<html>
<head>
<script language="PHP">

  CheckFormParameters(array("ref_periodo",
                            "ref_pessoa",
                            "ref_curso",
                            "ref_campus",
                            "ref_disciplina"));

  $conn = new Connection;
  
  $conn->Open();

  $ref_disciplina_subst = $ref_disciplina_subst ? $ref_disciplina_subst : '0';
  $sql = " select pessoa_nome('$ref_pessoa'), " .
         "        descricao_disciplina('$ref_disciplina'), " .
         "        descricao_disciplina($ref_disciplina_subst), " .
         "        get_status_disciplina('$ref_pessoa','$ref_curso','$ref_disciplina');";

  $query = $conn->CreateQuery($sql);

  while ($query->MoveNext())
  {
    list ( $aluno_nome,
           $ref_disciplina_nome,
           $ref_disciplina_subst_nome,
           $status_disc) = $query->GetRowValues();
      
  }

  if ($status_disc == 2)
      $color = 'red';
  elseif ($status_disc == 1)
      $color = 'green';
  elseif ($status_disc == '')
      $color = '#000000';
  else
      $color = 'orange';

  $query->Close();

  $conn->Close();

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="desbloqueia_disciplina.php3" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Confirma Desbloqueio de Disciplina para Matrícula</b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Aluno</font></td>
      <td width="84%"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="hidden" name="ref_pessoa" value="<?echo($ref_pessoa);?>">
              <?echo("$ref_pessoa - $aluno_nome");?>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td width="84%"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td width="20%"> 
              <input name="ref_contrato" type="hidden" value="<?echo($ref_contrato);?>">
              <?echo($ref_contrato);?>
            </td>
            <td width="15%" bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Curso</font> 
            </td>
            <td width="15%"><font face="Verdana, Arial, Helvetica, sans-serif"> 
              <input type="hidden" name="ref_curso" value="<?echo($ref_curso);?>">
              <?echo($ref_curso);?>
              </font> 
            </td>
            <td width="15%" bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Campus</font> 
            </td>
            <td width="15%"><font face="Verdana, Arial, Helvetica, sans-serif"> 
              <input type="hidden" name="ref_campus" value="<?echo($ref_campus);?>">
              <?echo($ref_campus);?>
              </font> 
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo</font></td>
      <td width="84%"> 
        <input type="hidden" name="ref_periodo" value="<?echo($ref_periodo);?>"><font face="Verdana, Arial, Helvetica, sans-serif">
        <?echo($ref_periodo);?>
        </font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Disciplina do Currículo</font></td>
      <td width="84%"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="hidden" name="ref_disciplina" value="<?echo($ref_disciplina);?>">
              <?echo("$ref_disciplina - $ref_disciplina_nome");?>
            </td>
            <td bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Status Atual</font> 
            </td>
            <td> 
              <font face="Arial, Helvetica, sans-serif" size="2" color="<?echo($color);?>">
              <b>&nbsp;<?echo($status_disciplina[$status_disc]);?></b>
              </font>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Disciplina Substituída</font></td>
      <td width="84%"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="hidden" name="ref_disciplina_subst" value="<?echo($ref_disciplina_subst);?>">
              <?echo("$ref_disciplina_subst - $ref_disciplina_subst_nome");?>
            </td>
            
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
    <tr>
      <td colspan="2">
         <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit" value=" Salvar ">
          <input type="button" name="Submit22" value=" Voltar " onclick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
  </form>
</body>
</html>
