<? require("../../lib/common.php"); ?>
<HTML>
<HEAD>

<script language="JavaScript">
function buscaEnder()
{
  var wnd = window.open("/generico/post/lista_ender.php3",'buscaEnder','toolbar=no,width=550,height=350,scrollbars=yes');

  wnd.setEnder = setEnder;
}

function setEnder(ender)
{
  document.myform.endereco.value = ender;
}

function _busca()
{
  var url = "/generico/post/lista_usuarios.php3" +
            "?pnome=" + escape(document.myform.usuario.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.ref_usuario.value = id;
  document.myform.usuario.value = nome;
}
</script>

</HEAD>
<BODY bgColor=#ffffff>
<br>
<FORM action="post/perfil_link.php3" method=post name=myform>
  <TABLE align=center cols=2 width=500>
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Novo 
        Link para Usu&aacute;rio</b></font></td>
    </tr>
    <TR> 
      <TD bgColor=#ccccff width="134"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;</b></font><FONT color=#00009c 
      face="Verdana, Arial, Helvetica, sans-serif" size=2>Usu&aacute;rio </FONT></TD>
      <TD width="362"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_usuario" size="8" value="<?echo($ref_usuario);?>">
            </td>
            <td> 
              <input type="text" name="usuario" size="32" value="<?echo($usuario);?>">
            </td>
            <td> 
              <input type="button" value="..." onClick="_busca()" name="button">
            </td>
          </tr>
        </table>
      </TD>
    </TR>
    <TR> 
      <TD bgColor=#ccccff width="134"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;</b></font><FONT color=#00009c 
      face="Verdana, Arial, Helvetica, sans-serif" size=2>P&aacute;gina</FONT></TD>
      <TD width="362"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="ref_pagina" size="8" maxlength="8">
            </td>
            <td> 
              <input name=pagina size="32" maxlength="32">
            </td>
            <td> 
              <input type="button" value="..." onClick="buscaEnder()" name="button2">
            </td>
          </tr>
        </table>
      </TD>
    </TR>
    <TR> 
      <TD colSpan=2> 
        <HR SIZE=1>
      </TD>
    </TR>
    <TR> 
      <TD width="134">&nbsp;</TD>
      <TD width="362"> 
        <INPUT name=Submit type=submit value=Incluir>
        <INPUT name=Submit2 type=reset value=Limpar>
      </TD>
    </TR>
  </TABLE>
  </FORM>
<P>&nbsp;</P></BODY></HTML>
