<html>
<head>
<title>Acesso negado</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF">
<table width="89%" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr> 
    <td width="27%" height="91"> 
      <div align="center"><img src="/logo_ies.gif" width="104" height="94"></div>
    </td>
    <td width="44%" height="91"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="3"><b><font size="4" color="#FF3333">Acesso 
        negado</font><font size="4" color="#0066CC"> </font><br>
        <font size="2">Sistema Administrativo</font></b></font></div>
    </td>
    <td width="29%" height="91"> 
      <div align="center"><img src="images/princ.jpg" width="154" height="111"></div>
    </td>
  </tr>
</table>
<p align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b>A 
  tentativa de estabelecer conex&atilde;o <br>
  com <font color="#000000">o banco de dados p</font>ara <br>
  o usu&aacute;rio<font color="#0000CC"> 
  <script language="PHP">
echo("[" . $uid . "]");
</script>
  </font>foi NEGADA.</b></font></p>
<p align="center"><a href="../index.php"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Tentar 
  novamente</font></a></p>
</body>
</html>
