<? header("Cache-Control: no-cache"); ?>
<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Alunos matriculados por cidade por período por tipo de curso</title>

<script language="PHP">
$op_opcoes1 = SQLArray("$sql_periodos_academico");

$op_opcoes2 = SQLArray("select id || ' - ' || descricao, id from tipos_curso order by descricao");

function Busca($ref_periodo, $tipo_curso)
{
    if ( $ref_periodo != null && $tipo_curso != null )
    {
        $conn = new Connection;
      
        $conn->Open();
      
        $sql = "select A.ref_cidade," .
               "       B.nome," .
               "       count(A.ref_cidade)" .
               " from  pessoas A," .
               "       aux_cidades B," .
               "       (select distinct A.ref_pessoa" .
               "        from   matricula A, contratos B, cursos C" .
               "        where  A.ref_contrato = B.id" .
               "        and    A.dt_cancelamento is null" .
               "        and    B.dt_desativacao is null" .
               "        and    A.ref_periodo = '$ref_periodo'" .
               "        and    B.ref_curso = C.id" .
               "        and    C.ref_tipo_curso = '$tipo_curso') C" .
               " where B.id = A.ref_cidade" .
               " and   A.id = C.ref_pessoa" .
               " group by A.ref_cidade, B.nome" .
               " order by B.nome";

        $query = $conn->CreateQuery($sql);
        
        $fg1 = "#ffffff";
        $fg2 = "#000000";

        $bg1 = "#000000";
        $bg2 = "#ccccff";
        $bg3 = "#bbbbff";

        echo("<table width=\"90%\" border=\"0\" cellspacing=\"2\" cellpadding=\"0\" align=\"center\">");
        
        echo("<tr bgcolor=\"$bg1\">");
        echo(" <td width=\"10%\" align=\"right\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg1\"><b>Cód. cidade</b>&nbsp;</font></td>");
        echo(" <td width=\"20%\" align=\"left\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg1\">&nbsp;<b>Nome cidade</b></font></td>");
        echo(" <td width=\"10%\" align=\"right\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg1\"><b>Total de alunos</b>&nbsp;</font></td>");
        echo("</tr>");

        $total_geral = 0;
        $i = 0;
        while ( $query->MoveNext() )
        {

            list ( $ref_cidade, $nome, $total ) = $query->GetRowValues();

            if ( $i % 2 )
            {
               $bg = $bg2;
            }
            else
            {
               $bg = $bg3;
            }


            echo("<tr bgcolor=\"$bg\">");
            echo(" <td width=\"10%\" align=\"right\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg2\">$ref_cidade&nbsp;</font></td>");
            echo(" <td width=\"20%\" align=\"left\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg2\">&nbsp;$nome</font></td>");
            echo(" <td width=\"10%\" align=\"right\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg2\">$total&nbsp;</font></td>");
            echo("</tr>");

            $total_geral += $total;

            $i++;
            
        }
        echo("<tr bgcolor=\"$bg1\">");
        echo(" <td colspan=\"2\" align=\"right\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg1\"><b>Total geral</b>&nbsp;</font></td>");
        echo(" <td width=\"10%\" align=\"right\"><font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg1\"><b>$total_geral</b>&nbsp;</font></td>");
        echo("</tr>");
        
        echo("</table>");
        
        $query->Close();
        $conn->Close();
    }
}

</script>

<script language=JavaScript>
function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_periodo);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.tipo_curso);
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
                  
}
                                              
function ChangeCode(fld_name,op_name)
{ 
    var field = eval('document.myform.' + fld_name);
    var combo = eval('document.myform.' + op_name);
    var code  = field.value;
    var n     = combo.options.length;
    for ( var i=0; i<n; i++ )
    {
      if ( combo.options[i].value == code )
      {
        combo.selectedIndex = i;
        return;
      }
    }
    alert(code + ' não é um código válido!');
    field.focus();
    return true;
}

</script>

</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="alunos_cidade_tipo_curso.phtml" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="3" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Número de alunos matriculados por cidade por período e por tipo de curso</b></font></td>
    </tr>
    <tr> 
      <td width="15%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="15%"><input type="text" name="ref_periodo" size="10" maxlength="10" value="<?echo($ref_periodo)?>" OnChange="ChangeCode('ref_periodo','op1')"></td>
      <td width="70%"><? ComboArray("op1",$op_opcoes1,$ref_periodo,"ChangeOp1()"); ?></td>
    </tr>
    <tr> 
      <td width="15%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Tipo curso:</font></td>
      <td width="15%"><input type="text" name="tipo_curso" size="10" maxlength="10" value="<?echo($tipo_curso)?>" OnChange="ChangeCode('tipo_curso','op2')"></td>
      <td width="70%"><? ComboArray("op2",$op_opcoes2,$tipo_curso,"ChangeOp2()"); ?></td>
    </tr>
    <tr>
      <td colspan="3"><hr></td>
    </tr>
    <tr>
      <td colspan="3" align="center">
        <input type="submit" name="Submit"  value="  Gerar  ">
        <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
      </td>
    </tr>
  </table>
    <?
        Busca($ref_periodo,$tipo_curso);
    ?>
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
      </td>
    </tr>
 </table>
</form>
</body>
</html>
