<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript">
var cmp;

function buscaPessoa()
{
  cmp = '1';

  var url = '../generico/post/lista_pessoas.php3' +
            '?pnome=' + escape(document.myform.pnome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2)
{
  if (cmp=='1')
  {
    document.myform.pessoa.value = arg1;
    document.myform.pnome.value = arg2;
  }
}

function consexec(arg1)
{
  alert(arg1);

  if (document.myform.opcao.value == 'opcao1')
  {
    alert('Opção 1 selecionada.');
  }
  else if (document.myform.opcao.value == 'opcao2')
  {
    alert('Opção 2 selecionada.');
  }
  else if (document.myform.opcao.value == 'opcao3')
  {
    alert('Opção 3 selecionada.');
  }
  else if (document.myform.opcao.value == 'opcao4')
  {
    alert('Opção 4 selecionada.');
  }
  else if (document.myform.opcao.value == 'opcao5')
  {
    alert('Opção 5 selecionada.');
  }
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<table width="500" border="0" cellspacing="0" cellpadding="0" height="40" align="center">
  <tr bgcolor="#000099"> 
    <td height="35"> 
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Consultas 
        Diversas</font></b></font></div>
    </td>
  </tr>
</table>
<form name="myform" action="" >
  <table cols=2 width="500" align="center" border="0">
    <tr> 
      <td bgcolor="#EFEFFF" width="56"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">Per&iacute;odo</font></td>
      <td width="382" bgcolor="#FFFFEF"> <font color="#000000"> </font></td>
      <td width="40" bgcolor="#FFFFEF">&nbsp;</td>
    </tr>
    <tr> 
      <td bgcolor="#EFEFFF" width="56"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099"> 
        Aluno</font></td>
      <td width="382" bgcolor="#FFFFEF"> 
        <input type="text" name="pessoa" size="10" maxlength="10">
        <input type="text" name="pnome" size="30" maxlength="40">
        <font color="#000000"><font color="#000000"><font color="#000000"><font color="#000000"> 
        </font></font></font></font> </td>
      <td width="40" bgcolor="#FFFFEF"> 
        <div align="center"><font color="#000000"><font color="#000000"><font color="#000000"><font color="#000000"> 
          <input type="button" value="..." onClick="buscaPessoa()" name="button">
          </font></font></font></font> </div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#EFEFFF" width="56">&nbsp;</td>
      <td width="382" bgcolor="#FFFFEF"> 
        <div align="center"> </div>
      </td>
      <td width="40" bgcolor="#FFFFEF">&nbsp;</td>
    </tr>
  </table>
  <p>&nbsp; </p>
  <div align="center"> 
    <table width="237" border="0" cellspacing="0" cellpadding="0">
      <tr valign="middle" align="center" bgcolor="#000099"> 
        <td height="26"> 
          <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><u><font color="#FFFFCC">Selecione 
            a Consulta:</font></u></font></b></div>
        </td>
      </tr>
      <tr> 
        <td> <font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
          <input type="radio" name="opcao" value="op1" checked >
          Disciplinas Cursadas</font></td>
      </tr>
      <tr> 
        <td><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
          <input type="radio" name="opcao" value="op2">
          Semestres Matriculados</font></td>
      </tr>
      <tr> 
        <td><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
          <input type="radio" name="opcao" value="op3">
          Cursos </font></td>
      </tr>
      <tr> 
        <td><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
          <input type="radio" name="opcao" value="op4">
          Situa&ccedil;&atilde;o Financeiro</font></td>
      </tr>
      <tr> 
        <td><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
          <input type="radio" name="opcao" value="op5">
          Raz&atilde;o de Lan&ccedil;amentos</font></td>
      </tr>
      <tr>
        <td> 
          <div align="center">
            <input type="button" value="Consultar" onClick=consexec(document.myform.opcao.value) name="button2">
          </div>
        </td>
      </tr>
    </table>
  </div>
  <p>&nbsp; </p>
  <p>&nbsp;</p>
</form>
</body>
</html>
