<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Alunos Formandos</title>

<script language="JavaScript">
function Lista_Alunos()
{
    window.document.myform.action = "post/lista_tempo_medio.php3";
}
</script>

<script language="PHP">

$op_result = SQLArray($sql_periodos_academico);

$op_result1 = SQLArray("select id || ' / ' || substr(abreviatura,1,30) as d, id from cursos order by id");

$op_result2 = SQLArray("select descricao, id from tipos_curso order by descricao");

</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);

  document.myform.action = 'alunos_formandos.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_tipo_curso);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/alunos_formandos.php3" name="myform">
 <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta de alunos Formandos/Formados</b></font></td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td width="296"> <font color="#000000"> </font>
       <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>
              <input type="text" name="ref_curso" size="8" onChange="ChangeCode('ref_curso','op1')">
          </td>
          <td>&nbsp;</td>
          <td width="100%"><font color="#000000">
          <script language="PHP">
               ComboArray("op1",$op_result1,$ref_curso,"ChangeOp1()");
	  </script>
	  </font></td>
	</tr>
       </table>
      </td>
    </tr>
    <tr>
       <TD width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Status</font></td>
       <TD width="296">
         <font face="Arial, Helvetica, sans-serif" size="2" color="#000099">
         <INPUT type="radio" name="status" value="formandos" checked onClick="alert('Clicando neste botao você imprimirá os alunos \nque irão se formar este semestre.')">Formandos&nbsp;&nbsp;&nbsp;&nbsp;
         <INPUT type="radio" name="status" value="formados" onClick="alert('Clicando neste botao você imprimirá os alunos \nque já se formaram.')">Formados
       </TD>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
      </td>
    </tr>
    <tr>
       <td colspan="2"><font face="Helvetica" size="2" color="red"><b>ATENÇÃO:</b></font>
       </td>
    </tr>
    <tr>
       <td colspan="2"><font face="Helvetica" size="2" color="#000099"><b><li>Caso seja selecionado a opção "Formandos" somente é obrigatório informar o campo <i>Período</i>. O campo <i>Curso</i> servirá como filtro. Caso queira que saia todos os cursos, deixe este campo em branco.</li></b></font>
       </td>
    </tr>
     <tr>
       <td colspan="2"><font face="Helvetica" size="2" color="#000099"><b><li>Caso seja selecionado a opção "Formados" os campos <i>Período</i> e <i>Curso</i> servirão como filtro. Caso queira que saia os formados em todos os cursos e períodos, deixe os dois campos em branco.</li></b></font>
       </td>
    </tr>
    
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
      </td>
    </tr>
     <tr>
       <td colspan="2"><font face="Helvetica" size="2" color="#000099"><b>Parâmetros Opcionais: (Somente utilizados para a opção "Formados")</b></font>
       </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="00009C">&nbsp;Tipo do Curso</font></td>
      <td> <font color="#000000">
          <input name="ref_tipo_curso" type="text" size="5" onChange="ChangeCode('ref_tipo_curso','op')">
          <script language="PHP">
            ComboArray("op2",$op_result2,$ref_tipo_curso,"ChangeOp2()");
	      </script></font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Intervalo de Datas<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td>&nbsp;<b>De</b>&nbsp;<input type="text" name="dt_inicial" size="10" maxlength="10">
          &nbsp;<b>até</b>&nbsp;<input type="text" name="dt_final" size="10" maxlength="10">
      </td>
    </tr>

    <tr>
      <td colspan="2" align="center"> 
        <hr size="1">
        <input type="submit" name="Submit" value=" Nome e Endereço ">
        <input type="submit" name="Submit2" value=" Tempo de Conclusão " onClick="javascript:Lista_Alunos()">
        <input type="button" name="Button3" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
