<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<script language="JavaScript">

function AproveitaDisciplina(ref_pessoa,ref_contrato,curso,ref_campus,ref_disciplina,ref_curso,ref_matricula,nota_final,conceito_final,ref_disciplina_ofer,ref_periodo,carga_horaria_aprov,creditos_aprov)
{

 url = '/academico/aproveitamento_interno.phtml' +
       '?ref_pessoa=' + ref_pessoa +
       '&ref_contrato=' + ref_contrato +
       '&ref_curso=' + curso +
       '&ref_campus=' + ref_campus +
       '&ref_disciplina_subst=' + ref_disciplina +
       '&ref_curso_subst=' + ref_curso +
       '&ref_matricula=' + ref_matricula +
       '&nota_final=' + nota_final +
       '&conceito_final=' + conceito_final +
       '&ref_disciplina_ofer=' + ref_disciplina_ofer +
       '&ref_periodo=' + ref_periodo +
       '&carga_horaria_aprov=' + carga_horaria_aprov +
       '&creditos_aprov=' + creditos_aprov;

  if (ref_disciplina!='')
  {
    if (confirm("Deseja Aproveitar Disciplina ?"))
    {
        location = url;
    }
    else
    {
      alert("Aproveitamento Cancelado.");
    }
  }
  else
  {
    location = url;
  }
}

function AproveitaDisciplinaAvulso(ref_pessoa,ref_disciplina,ref_curso,ref_matricula,nota_final,conceito_final)
{

 url = '/academico/aproveitamento_int.phtml' +
       '?ref_pessoa=' + ref_pessoa +
       '&ref_disciplina_subst=' + ref_disciplina +
       '&ref_curso_subst=' + ref_curso +
       '&ref_matricula=' + ref_matricula +
       '&nota_final=' + nota_final +
       '&conceito_final=' + conceito_final;

  if (ref_disciplina!='')
  {
    if (confirm("Deseja Aproveitar Disciplina ?"))
    {
        location = url;
    }
    else
    {
      alert("Aproveitamento Cancelado.");
    }
  }
  else
  {
    location = url;
  }
}
</script>

<script language="JavaScript">
function BuscaPessoa()
{
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.ref_pessoa.value = id;
  document.myform.aluno_nome.value = nome;
}
</script>

<script language="JavaScript">
function buscaContrato()
{
  var pessoa = document.myform.ref_pessoa.value;

  if ( pessoa == '' )
  {
    alert("Código da pessoa inválido ou não especificado!");
    return;
  }

  var title = 'Seleção Contrato';

  var sql = " select A.id as id, " +
            "        A.ref_curso as Curso, " +
            "        B.descricao as Descricao, " +
            "        A.ref_campus as Campus, " +
            "        A.dt_desativacao is not null as Dest" +
            "  from contratos A, cursos B" +
            "  where A.ref_pessoa = " + pessoa + " and " +
            "        A.dt_desativacao is null and" +
            "        A.ref_curso = B.id";

  var url = "../generico/post/lista_sql.php3?title=" + escape(title) + "&sql=" + escape(sql);

  window.setResultCallback = window.setContrato;

  var wnd = window.open(url,'buscaContrato','toolbar=no,width=550,height=350,scrollbars=yes');

}

function setContrato(id,curso,descricao,campus)
{
  document.myform.ref_contrato.value = id;
  document.myform.curso.value = curso;
  document.myform.ref_campus.value = campus;
}
</script>


</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="aproveitamento_interno_disc.phtml" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Aproveitamento de Disciplina </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
      <td> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_pessoa" size="10" value="<?echo($ref_pessoa);?>">
            </td>
            <td> 
              <input type="text" name="aluno_nome" size="30" value="<?echo($aluno_nome);?>">
            </td>
            <td> 
              <input type="button" value="..." onClick="BuscaPessoa()" name="button">
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input name="ref_contrato" type=text size="10" maxlength="10" value="<?echo($ref_contrato);?>">
            </td>
            <td> 
              <input type="text" name="curso" size="10" maxlength="10" value="<?echo($curso);?>">
            </td>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">campus 
              </font> 
              <input type="text" name="ref_campus" size="10" maxlength="10" value="<?echo($ref_campus);?>">
            </td>
            <td><a href="javascript:buscaContrato()"><img src="../images/find.gif" width="16" height="16" border="0"></a> 
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"  value=" Consultar ">
          <input type="button" name="Button2" value="   Sair    " onClick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
  </form>
  
<div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099"> 
  </font></b>
</div>
<center>
<?
echo("<a href=\"javascript:AproveitaDisciplinaAvulso('','','','','','')\">
Novo Aproveitamento avulso</a>");
?>
</center>
<br>

<table border=0 cellpadding=2 cellspacing=1 align=center width="90%">
  <tr> 
    <td height=32 bgcolor="#000099" colspan=5><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Matriculas</b></font> 
  </tr>
  <tr bgcolor="#000000"> 
    <td width="76" height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>id</b></font></td>
    <td width="276" height="21"><font face="Verdana" size="2" color="#ffffff"><b>Disciplina</b></font></td>
    <td width="97" height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Oferecida</b></font></td>
    <td colspan="2" height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Substitui&ccedil;&atilde;o</b></font><font face="Verdana" size="2" color="#ffffff"></font></td>
  </tr>

<script language="PHP">

$conn = new Connection;

$conn->Open();

$sql = " select A.id, " .
       "        A.ref_campus," .
       "        A.ref_disciplina, " .
       "	    descricao_disciplina(A.ref_disciplina)," .
       "	    A.ref_curso_subst, " .
       "	    curso_desc(A.ref_curso_subst)," .
       "	    A.ref_disciplina_subst, " .
       "	    descricao_disciplina(A.ref_disciplina_subst)," .
       "	    A.ref_disciplina_ofer, " .
       "	    dia_disciplina_ofer(B.id), " .
       "	    A.dt_cancelamento is not null, " .
       "	    A.nota_final, " .
       "	    A.conceito_final, " .
       "	    A.ref_periodo, " .
       "	    A.carga_horaria_aprov, " .
       "	    A.creditos_aprov" .
       " from matricula A, disciplinas_ofer B" .
       " where A.ref_disciplina_ofer = B.id and " .
       "       A.ref_pessoa = '$ref_pessoa' and " .
       "	   A.ref_disciplina_ofer = B.id" .
       " order by A.ref_periodo";

$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

$gr_periodo=0;

for ( $row=0; $query->MoveNext(); $row++ )
{
  list ($id, 
        $ref_campus,
        $ref_disciplina,
    	$descricao_disciplina,
        $ref_curso_subst,
	    $curso_desc,
        $ref_disciplina_subst,
    	$descricao_disciplina_subst,
        $ref_disciplina_ofer,
	    $dia_semana,
    	$is_cancelada,
	    $nota_final,
    	$conceito_final, 
	    $ref_periodo,
        $carga_horaria_aprov,
        $creditos_aprov) = $query->GetRowValues();

  if ($gr_periodo != $ref_periodo)
  {
    $gr_periodo=$ref_periodo;
  </script>
  <tr bgcolor="#c0c0c0" valign="middle"> 
  <td colspan="5"><font face="Verdana" size="2" color="#000099">
    <? echo("$ref_periodo"); ?>
  </font>
  </td>
  </tr>
<script language="PHP">
  }

  if ( ( $row % 2 ) == 0 )
  {

</script>
  <tr bgcolor="#FFFFEE" valign="middle"> 
    <td width="76"><font face="Verdana" size="2" color="#000099"><?
if ($is_cancelada == 't')
{
  echo('<font color=red> [C] </font> ' . $id);
}
else
{
  echo("<a href=\"javascript:AproveitaDisciplina('$ref_pessoa','$ref_contrato','$curso','$ref_campus','$ref_disciplina','$ref_curso_subst','$id','$nota_final','$conceito_final','$ref_disciplina_ofer','$ref_periodo','$carga_horaria_aprov','$creditos_aprov')\">
  <img src=\"../images/select.gif\" border=0 title=\"Aproveita a disciplina\"></a>");
  echo("$id");
}
?></font></td>
    <td width="276"><font face="Verdana" size="2" color="#000099"><?php 
if ($ref_campus != '1')
{
  echo("<img src=\"../images/checkoff.gif\" title=\"fora sede\">");
}
else
{
  echo("<img src=\"../images/checkon.gif\" title=\"na da sede\">");
}
?><font size="1"><?echo($ref_disciplina . ' - ' . substr($descricao_disciplina,0,30));?>&nbsp;</font></font></td>
    <td width="97"> 
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_ofer);?><font color="#FF3333">&nbsp;<?echo(' dia ' . $dia_semana);?></font>&nbsp;</font></div>
    </td>
    <td width="66"> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$curso_desc\">");?></font><font face="Verdana" size="2" color="#FF0033">curso&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo("$ref_curso_subst");?></font></div>
    </td>
    <td width="74"> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$descricao_disciplina_subst\">");?>&nbsp;<font color="#FF0000">disc&nbsp;</font><?echo($ref_disciplina_subst);?></font></div>
    </td>
  </tr>
  <script language="PHP">

  }

  else
  {

</script>
  <tr bgcolor="#EEEEFF" valign="middle"> 
    <td width="76"><font face="Verdana" size="2" color="#000099"><?
if ($is_cancelada == 't')
{
  echo('<font color=red> [C] </font> ' . $id);
}
else
{
  echo("<a href=\"javascript:AproveitaDisciplina('$ref_pessoa','$ref_contrato','$curso','$ref_campus','$ref_disciplina','$ref_curso_subst','$id','$nota_final','$conceito_final','$ref_disciplina_ofer','$ref_periodo','$carga_horaria_aprov','$creditos_aprov')\">
  <img src=\"../images/select.gif\" border=0 title=\"Aproveita a disciplina\"></a>");
  echo("$id");
}
?></font></td>
    <td width="276"><font face="Verdana" size="2" color="#000099"><?php 
if ($ref_campus != '1')
{
echo("<img src=\"../images/checkoff.gif\" title=\"fora sede\">");
}
else
{
echo("<img src=\"../images/checkon.gif\" title=\"na sede\">");
}
?><font size="1"><?echo($ref_disciplina . ' - ' . substr($descricao_disciplina,0,30));?>&nbsp;</font></font></td>
    <td width="97"> 
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_ofer);?><font color="#FF3333">&nbsp;<?echo(' dia ' . $dia_semana);?></font><font color="#FF0000">&nbsp;</font></font></div>
    </td>
    <td width="66"> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$curso_desc\">");?></font><font face="Verdana" size="2" color="#FF0000">curso&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo("$ref_curso_subst");?></font></div>
    </td>
    <td width="74"> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$descricao_disciplina_subst\">");?>&nbsp;<font color="#FF0000">disc&nbsp;</font></font><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_subst);?></font></div>
    </td>
  </tr>
  <script language="PHP">

  }
}

$query->Close();

$conn->Close();

</script>
</table>
</body>
</html>
