<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<? $op_opcoes2 = SQLArray("$sql_periodos_academico");
?>
<html>
<head>
<title>Aproveitamentos</title>
<script language="JavaScript">
function BuscaPessoa()
{
  cmp = '3';
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}
</script>

<script language="JavaScript">
function buscaContrato()
{
  var pessoa = document.myform.ref_pessoa.value;

  if ( pessoa == '' )
  {
    alert("Código da pessoa inválido ou não especificado!");
    return;
  }

  var title = 'Seleção Contrato';

  var sql = " select A.id as id, " +
            "        A.ref_curso as Curso, " +
            "        B.descricao as Descricao, " +
            "        A.ref_campus as Campus, "+
            "        A.dt_desativacao is not null as Desat" +
            " from contratos A, cursos B" +
            " where A.ref_pessoa = " + pessoa + " and " +
            "       A.dt_desativacao is null and" +
            "       A.ref_curso = B.id";

  var url = "../generico/post/lista_sql.php3?title=" + escape(title) + "&sql=" + escape(sql);

  window.setResultCallback = window.setContrato;
  
  var wnd = window.open(url,'buscaContrato','toolbar=no,width=550,height=350,scrollbars=yes');

}

function setContrato(id,curso,descricao,campus)
{
  document.myform.ref_contrato.value = id;
  document.myform.ref_curso.value = curso;
  document.myform.ref_campus.value = campus;
}
</script>

<script language="JavaScript">
function buscaInstit()
{
  var title = 'Seleção Instituições';
  
  var sql = "select id as Codigo, sucinto as Nome from instituicoes order by sucinto";
  
  var url = "../generico/post/lista_sql.php3?title=" + escape(title) + "&sql=" + escape(sql);
  
  window.setResultCallback = window.setInstit;
  
  var wnd = window.open(url,'buscaInstit','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setInstit(id,nome)
{
  document.myform.ref_instituicao.value = id;
  document.myform.instituicao.value = nome;
  document.myform.obs_aproveitamento.value= "DISCIPLINA CURSADA E APROVEITADA DA " + nome;
}
</script>

<script language="JavaScript">
var cmp;

function buscaDiscp(pf)
{
  cmp = pf;
  if (cmp =='1')
  {
    var url = '../generico/post/lista_disciplinas_curso.php3' + 
              '?ref_curso=' + escape(document.myform.ref_curso.value);

  }
  else if (cmp=='2')
  {
    var url = '../generico/post/lista_disciplinas_curso.php3' + 
              '?ref_curso=' + escape(document.myform.ref_curso_subst.value);
  }

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2)
{
  if (cmp=='1')
  {
    document.myform.ref_disciplina.value = arg1;
    document.myform.ref_disciplina_nome.value = arg2;
  }

  else if (cmp=='2')
  {
    document.myform.ref_disciplina_subst.value = arg1;
    document.myform.ref_disciplina_subst_nome.value = arg2;
  }
  else if (cmp=='3')
  {
    document.myform.ref_pessoa.value = arg1;
    document.myform.aluno_nome.value = arg2;
  }
}

</script> 

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op2,document.myform.ref_periodo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
<script language="JavaScript">
function oferece()
{
  var ender = 'disciplina_ofer.phtml';
  window.open(ender,'oferece','resizable=yes, toolbar=no,width=660,height=400,scrollbars=yes');
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<FORM method="POST" action="post/insere_aproveitamento_int.php3" name="myform">
<table align="center" width="90%">
    <tr>
      <td bgcolor="#000099" colspan="4" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Digita&ccedil;&atilde;o de Aproveitamento Avulso</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo da Disciplina Oferecida&nbsp;</font></td>
      <td colspan="3"> 
        <input name="ref_disciplina_ofer" type="text" size="10" maxlength="10" value="<?echo($ref_disciplina_ofer);?>">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
      <td colspan="3">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="ref_pessoa" size="10" value="<?echo($ref_pessoa);?>">
            </td>
            <td> 
              <input type="text" name="aluno_nome" size="40" value="<?echo($aluno_nome);?>">
            </td>
            <td> 
              <input type="button" value="..." onClick="BuscaPessoa()" name="button">
            </td>
          </tr>
        
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td colspan="3">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        
          <tr>
            <td> 
              <input name="ref_contrato" type=text size="10" maxlength="10" value="<?echo($ref_contrato);?>">
            </td>
            <td> 
              <input type="text" name="ref_curso" size="10" maxlength="10" value="<?echo($ref_curso);?>">
            </td>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">campus 
              </font> 
              <input type="text" name="ref_campus" size="10" maxlength="10" value="<?echo($ref_campus);?>">
            </td>
            <td><a href="javascript:buscaContrato()"><img src="../images/find.gif" width="16" height="16" border="0"></a> 
            </td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo</font></td>
      <td colspan="3">
      <table width="100%%" border="0" cellspacing="0" cellpadding="0">
        
          <tr>
            <td colspan="2"> <font color="#000000"> 
              <input name="ref_periodo" type=text onChange="ChangeCode('ref_periodo','op2')" value="<?echo($ref_periodo);?>" size="10" maxlength="10">
              </font> <font color="#000000"> 
              <script language="PHP">
     ComboArray("op2",$op_opcoes2,$ref_periodo,"ChangeOp1()");
        </script>
              <a href="javascript:oferece()"><img src="../images/add.gif" width="16" height="15" border="0" alt="Oferece Disciplina"></a> 
              </font></td>
          </tr>
        
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Curso Substituto</font></td>
      <td colspan="3"><input name="ref_curso_subst" type="text" size="10" value="<?echo($ref_curso_subst);?>"></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Disciplina Curr&iacute;culo</font></td>
      <td colspan="3">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
        <input name="ref_disciplina" type="text" size="10">
      </td>
            <td>
        <input name="ref_disciplina_nome" type="text" size="40">
      </td>
            <td>
        <input type="button" value="..." onclick="buscaDiscp('1')">
      </td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Disciplina Cursada</font></td>
      <td colspan="3">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
        <input name="ref_disciplina_subst" type="text" size="10" value="<?echo($ref_disciplina_subst);?>">
      </td>
            <td>
        <input name="ref_disciplina_subst_nome" type="text" size="40">
      </td>
            <td>
        <input type="button" value="..." onclick="buscaDiscp('2')">
      </td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nota 
        Final&nbsp;</font></td>
      <td colspan="3"> 
        <input name="nota_final" type="text" size="10" maxlength="10" value="<?echo($nota_final);?>">
      </td>
    </tr>
    <tr>
      <td width="38%" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Conceito Final</font></td>
      <td colspan="3"> 
        <input name="conceito_final" type="text" size="10" maxlength="10" value="<?echo($conceito_final);?>">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td colspan="3">
        <input name="dt_matricula" type=text value="<? echo date("d-m-Y"); ?>" size="10" maxlength="10">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Carga horária aproveitada</font></td>
      <td colspan="3"><input name="carga_horaria_aprov" type="text" size="10" maxlength="10"></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Cr&eacute;ditos aproveitados </font></td>
      <td colspan="3"><input name="creditos_aprov" type="text" size="10" maxlength="10"></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Institui&ccedil;&atilde;o</font></td>
      <td colspan="3">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
        <input name="ref_instituicao" type="text" size="10" maxlength="10">
      </td>
            <td>
        <input type="text" name="instituicao" size="40">
      </td>
            <td>
        <input type="button" value="..." onclick="buscaInstit()" name="button22">  </td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Observa&ccedil;&atilde;o</font></td>
      <td colspan="3"><textarea name="obs_aproveitamento" cols="46" rows="3" wrap="10">DISCIPLINA CURSADA E APROVEITADA DA </textarea></td>
    </tr>
    <tr>
      <td align="center" colspan="4">
      <HR size="1">
      </td>
    </tr>
    <tr>
      <td align="center" colspan="4">
        <input type="submit" name="Submit" value=" Salvar ">
        <input type="button" name="Button" value=" Voltar " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
