<? require("../../../lib/common.php"); ?>

<html>
<head>
<title>UNIVATES</title>
</head>

<body bgcolor="#FFFFFF" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" marginwidth="20" marginheight="20">

<TABLE width="500" border="0" cellspacing="4" cellpadding="2" align="center">
  <tr bgcolor="#FFCF31" class="dark">
    <td width="98%" colspan="2">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#0000CE"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="3"><font size="4" color="#000099">Sistema de Atestados</font></font></b></font></div>
    </td>
  </tr>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="atestado_curso.phtml">Matrícula Curso</a></b></font></div>
    </td>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2"><b><font size="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><a href="atestado_auxilio_transporte.phtml">Auxílio Transporte</a></font></font></b></font></div>
    </td>
  </tr>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="atestado_curso_matricula.phtml">Matrícula Disciplinas</a></b></font></div>
    </td>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2"><b><font size="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><a href="atestado_sub_judice.phtml">Sub-Júdice</a></font></font></b></font></div>
    </td>
  </tr>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="atestado_matricula_periodo.phtml">Disciplinas Período</a></b></font></div>
    </td>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2"><b><font size="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><a href="atestado_matricula_geral.phtml">Disciplinas Geral</a></font></font></b></font></div>
    </td>
  </tr>

  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="atestado_professores.phtml">Atestado Professores</a></b></font></div>
    </td>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="atestado_coren.phtml">Atestado COREN</a></b></font></div>
    </td>
  </tr>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="declaracao_coren.phtml">Declaração COREN</a></b></font></div>
    </td>
    <td width="49%">&nbsp;</td>
  </tr>
 
</table>
<TABLE width="500" border="0" align="center">
  <tr>
    <td height="36" valign="top" align="center"> 
      <input type="button" name="Button1" value="  Sair  " onClick="javascript:history.go(-1)">
    </td>
  </tr>
</table>
</body>
</html>
