<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<? require("../../../lib/common.php"); ?>
<? require("../../../lib/properties.php"); ?>
<?
  $periodo = $properties->Get("periodo","0");
?>

<html>
<head>
<META name="GENERATOR" content="IBM WebSphere Homepage Builder V4.0.0 for Linux">
<title>UNIVATES</title>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;
  
  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo);
}

function ChangeCode(fld_name,op_name)
{
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

var cmp;

function buscaPlaca()
{
  cmp = '1';

  var url = '../generico/post/busca_placa.php3' +
            '?placa=' + escape(document.myform.placa.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function buscaPessoa()
{
  cmp = '1';

  var url = '../generico/post/lista_pessoas.php3' +
            '?pnome=' + escape(document.myform.pnome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2)
{
  if (cmp=='1')
  {
    document.myform.pessoa.value = arg1;
    document.myform.pnome.value = arg2;
  }
}
</script>

<script language="PHP">
function SQL_Combo($nome,$sql,$default,$onchange)
{
  $conn = new Connection;
  $conn->Open();
  $query = $conn->CreateQuery($sql);
  
  if ( $onchange != "" )
    echo("<select name=\"$nome\" onchange=\"$onchange\">");
  else
    echo("<select name=\"$nome\">");
  
  for ( $i=1; $query->MoveNext(); $i++ )
  {
    list ( $text, $value ) = $query->GetRowValues();

    if ( $value == $default )
      echo("  <option value=\"$value\" selected>$text</option>\n");
    else
      echo("  <option value=\"$value\">$text</option>\n");
  }
  echo("</select>");
  $query->Close();
  $conn->Close();
}

</script>

</head>

<body bgcolor="#FFFFFF" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" marginwidth="20" marginheight="20">

<TABLE width="500" border="0" cellspacing="4" cellpadding="2" align="center">
  <tr bgcolor="#FFCF31" class="dark">
    <td width="98%" colspan="2">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#0000CE"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="3"><font size="4" color="#000099">Cadastros Duplos</font></font></b></font></div>
    </td>
  </tr>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2" color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"><b><a href="cadastro_duplo.phtml">Alunos</a></b></font></div>
    </td>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><font size="2"><b><font size="2"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><a href="instit_duplic.phtml">Instituições</a></font></font></b></font></div>
    </td>
  </tr>
  <tr bgcolor="#FFFFFF">
    <td width="49%" class="dark">&nbsp;</td>
    <td width="49%" class="dark">&nbsp;</td>
  </tr>
 
</table>
<TABLE width="500" border="0" align="center">
  <tr>
    <td height="36" valign="top" align="center"> 
      <input type="button" name="Button1" value="  Sair  " onClick="javascript:history.go(-1)">
    </td>
  </tr>
</table>
 
</body>

</html>

