<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../generico/busca_nome.php3"); ?>
<? require("../lib/VerificaTurnos.php3"); ?>
<?
  $op_opcoes2 = SQLArray("$sql_periodos_academico");
?>
<html>
<head>
<script language="JavaScript">

function seta_campo(ref_pessoa)
{
url = 'cancela_disciplina.phtml' +
      '?ref_pessoa=' + escape(document.myform.ref_pessoa.value);

self.location=(url);
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;
  var contrato = eval('document.myform.ref_contrato');

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';

  var url = "../generico/post/busca_mes_parcelas.php3" +
            "?ref_periodo=" + escape(fld.value) +
            "&ref_contrato=" + escape(contrato.value);

  window.SetResultParcelas = setMesParcelas;
  
  var wnd = window.open(url,'busca','toolbar=no,width=680,height=550,scrollbars=yes');
}

function ChangeOp1()
{
  if (document.myform.ref_contrato.value != '')
    {
       ChangeOption(document.myform.op2,document.myform.ref_periodo);
    }
  else
    {
       alert('Você deve selecionar primeiro o contrato !!!');
       return;
    }
}

function ChangeCode(fld_name,op_name)
{
  if (document.myform.ref_contrato.value == '')
  {
      alert('Você deve selecionar primeiro o contrato !!!');
      document.myform.ref_periodo.value = '';
      return;
  }
  else
  {
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var contrato = eval('document.myform.ref_contrato');
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      var url = "../generico/post/busca_mes_parcelas.php3" +
                "?ref_periodo=" + escape(field.value) +
                "&ref_contrato=" + escape(contrato.value);

      window.SetResultParcelas = setMesParcelas;
      
      var wnd = window.open(url,'busca','toolbar=no,width=680,height=550,scrollbars=yes');
      
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;

  }
}
</script>
<script language="JavaScript">
function CancelaDisciplina(ref_pessoa,ref_contrato,ref_periodo,ref_disciplina_ofer,ref_disciplina,ref_curso,ref_periodo,ref_campus,ref_matricula,fl_tx_cancel,mes,mes_resto,carga_horaria,ref_disciplina_subst,ref_curso_subst,creditos_diurno,creditos_noturno,creditos_disciplina_cancel,turno_disciplina_cancel,turno_curso)
{
    if (mes== "" || mes == 0 || mes==null)
    {
        alert('O mês de seqüência não pode ser nulo!!!');
        return;
    }
  
    if (confirm("Deseja Cancelar Disciplina ?"))
    {
        var motivo = prompt("Motivo de Cancelamento","");

        if (motivo == "" || motivo==null)
        {
            alert("Cancelar OK");
        }
        else
        {
            var url = '/academico/post/cancela_disciplina.php3' +
                      '?ref_contrato=' + ref_contrato +
                      '&ref_pessoa=' + ref_pessoa +
                      '&ref_periodo=' + ref_periodo +
                      '&ref_disciplina_ofer=' + ref_disciplina_ofer +
                      '&ref_disciplina=' + ref_disciplina +
                      '&ref_disciplina_subst=' + ref_disciplina_subst +
                      '&ref_curso_subst=' + ref_curso_subst +
                      '&ref_curso=' + ref_curso +
                      '&periodo_id=' + ref_periodo +
                      '&ref_campus=' + ref_campus +
                      '&num_parcelas=' + mes_resto +
                      '&mes=' + mes +
                      '&ref_matricula=' + ref_matricula +
                      '&ref_motivo=' + motivo +
                      '&fl_tx_cancel=' + fl_tx_cancel +
                      '&carga_horaria=' + carga_horaria;
    
            if (turno_curso != 'N')
            {
                if (turno_disciplina_cancel != 'N')
                {
                    creditos_diurno = creditos_diurno - creditos_disciplina_cancel;
                }
                else
                {
                    creditos_noturno = creditos_noturno - creditos_disciplina_cancel;
                }
                
                if ((creditos_diurno < 16) && (creditos_noturno > 0))
                {
                    if (confirm('O aluno é de um curso diurno e com este cancelamento ficará matriculado em \n' + creditos_noturno + ' créditos noturno e ' + creditos_diurno + ' créditos diurnos, ou seja, não estará matriculado \nem pelo menos 16 créditos no diurno. Clique OK para continuar, senão \nclique Cancel.'))
                    {
                        location=url;
                    }
                    else
                    {
                        alert("Disciplina não Cancelada.");
                    }
                }
                else
                {
                    location=url;
                }
            }
            else
            {
                location=url;
            }
        }
  
    }
    else
    {
        alert("Cancelamento não efetuado!!!");
    }
}
</script>

<script language="JavaScript">
function BuscaPessoa()
{
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.ref_pessoa.value = id;
  document.myform.aluno_nome.value = nome;
}

   

</script>

<script language="JavaScript">
function buscaContrato()
{
  var pessoa = document.myform.ref_pessoa.value;

  if ( pessoa == '' )
  {
    alert("Código da pessoa inválido ou não especificado!");
    return;
  }

  var title = 'Seleção Contrato';

  var sql = " select A.id as id, " +
            "        A.ref_curso as Curso, " + 
            "        B.descricao as Descricao, " + 
            "        A.ref_campus as Campus" +
            " from contratos A, cursos B" +
            " where A.ref_pessoa = " + pessoa + " and " +
            "       A.dt_desativacao is null and" +
            "       A.ref_curso = B.id";

  var url = "../generico/post/lista_sql.php3?title=" + escape(title) + "&sql=" + escape(sql);

  window.setResultCallback = window.setContrato;
  
  var wnd = window.open(url,'buscaContrato','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setContrato(id,curso,descricao,campus)
{
  document.myform.ref_contrato.value = id;
  document.myform.curso.value = curso;
  document.myform.ref_campus.value = campus;
}

function setMesParcelas(mes_sequencia, parcelas_a_dividir, parcelas)
{
  document.myform.mes.value = mes_sequencia;
  document.myform.mes_resto.value = parcelas;
}

</script>

</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="cancela_disciplina.phtml" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Cancelar Disciplina </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
      <td> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_pessoa" size="10"  onChange="javascript:seta_campo(ref_pessoa)" value="<?echo($ref_pessoa);?>">
            </td>
            <td> 
              <input type="text" name="aluno_nome" size="32" value="<?echo($aluno_nome);?>">
            </td>
            <td> 
              <input type="button" value="..." onClick="BuscaPessoa()" name="button">
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input name="ref_contrato" type=text size="10" maxlength="10" value="<?echo($ref_contrato);?>">
            </td>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">curso 
              </font> 
              <input type="text" name="curso" size="10" maxlength="10" value="<?echo($curso);?>">
            </td>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">campus 
              </font> 
              <input type="text" name="ref_campus" size="10" maxlength="10" value="<?echo($ref_campus);?>">
            </td>
            <td><a href="javascript:buscaContrato()"><img src="../images/find.gif" width="16" height="16" border="0"></a> 
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo&nbsp;</font></td>
      <td> 
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td colspan="2"> <font color="#000000"> 
             <input name="ref_periodo" type=text onChange="ChangeCode('ref_periodo','op2')" size="10" maxlength="10" value="<?echo($ref_periodo);?>">
              </font> <font color="#000000"> 
              <script language="PHP">
                ComboArray("op2",$op_opcoes2,$cod_periodo,"ChangeOp1()");
	      </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Helvetica" size="2" color="#00009C">&nbsp;M&ecirc;s Sequ&ecirc;ncia</font></td>
      <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
       <tr>
        <td>
          <input name="mes" type=text value="<?echo($mes);?>" size="10" maxlength="10">
        </td>
       	<td width="50" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nº Parcelas </font></td>
       	<td width="50">
	  <input name="mes_resto" type=text value="<?echo($mes_resto);?>" size="10" maxlength="10">
	 </td>
	</tr>
      </table>
       </td>
    </tr>   
    <?if (!empty($ref_pessoa))
    { 
        $nome = Busca_Nome($ref_pessoa);
    ?>
      <script language="javascript">
         document.myform.aluno_nome.value="<? echo($nome); ?>";
      </script>
    <?
    }
    
    ?>
    <tr>
<!--      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Com Taxa </font></td>-->
      <td valign="middle"> <font color="#000099"> <font face="Verdana, Arial, Helvetica, sans-serif"> 
        <font size="2">
        <font color="#000099">
        <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2">
        <script language="PHP">
          /*if ($fl_tx_cancel==yes)
          {
            echo("<input type=\"radio\" name=\"fl_tx_cancel\" value=\"yes\" checked>sim "); 
            echo("<input type=\"radio\" name=\"fl_tx_cancel\" value=\"no\">n&atilde;o");
          }
          else
          {
            echo("<input type=\"radio\" name=\"fl_tx_cancel\" value=\"yes\">sim ");
            echo("<input type=\"radio\" name=\"fl_tx_cancel\" value=\"no\" checked>n&atilde;o");
          }*/
            echo("<input type=\"hidden\" name=\"fl_tx_cancel\" value=\"no\" checked>");
        </script>
 </font></font></font>
 </font></font></font></td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"  value=" Consultar ">
          <input type="button" name="Button2" value="   Sair    " onClick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
</form>
<table border=0 cellpadding=2 cellspacing=1 align=center width="90%">
  <tr> 
    <td height=32 bgcolor="#000099" colspan=5><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Matrículas</b></font> 
  </tr>
  <tr bgcolor="#000000"> 
    <td width="76" height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>id</b></font></td>
    <td width="276" height="21"><font face="Verdana" size="2" color="#ffffff"><b>Disciplina</b></font></td>
    <td width="97" height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Oferecida</b></font></td>
    <td colspan="2" height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Substitui&ccedil;&atilde;o</b></font><font face="Verdana" size="2" color="#ffffff"></font></td>
  </tr>
  <script language="PHP">
  
@$turnos = VerificaTurnos($ref_contrato, $curso, $ref_periodo);
    
list ($creditos_diurno, $creditos_noturno) = split("-", "$turnos", 2);
  
$conn = new Connection;

$conn->Open();

// Verifica se o aluno tem algum incentivo que necessite de autorização para efetuar esta operação
$sql = " select date(now()) > A.dt_limite_autorizacao " .
       " from bolsas A, aux_bolsas B " .
       " where A.ref_tipo_bolsa=B.id and " .
       "       A.ref_contrato='$ref_contrato' and " .
       "       A.dt_validade>date(now()) and " .
       "       B.fl_autorizacao = 't' and " .
       "       A.percentual <> 0;";

$query = $conn->CreateQuery($sql);

$passou_prazo = 'f';
if ( $query->MoveNext() )
{
  $passou_prazo = $query->GetValue(1);
}

if ($passou_prazo!='f')
{
    </script>
    <script language="JavaScript">
        alert("Atenção: Este aluno possui algum tipo de benefício, portanto se ele alterar sua matrícula terá que entrar em contato com o Setor de Atendimento ao Aluno (e-mail assistencia.aluno@univates.br).");
    </script>
    <script language="PHP">
}

$query->Close();

$sql = " select A.id, " .
       "        A.ref_campus," .
       "    	A.ref_disciplina, " .
       "    	descricao_disciplina(A.ref_disciplina)," .
       "    	A.ref_curso_subst, " .
       "        curso_desc(A.ref_curso_subst)," .
       "    	A.ref_disciplina_subst, " .
       "    	descricao_disciplina(A.ref_disciplina_subst)," .
       "    	A.ref_disciplina_ofer, " .
       "    	dia_disciplina_ofer_todos(B.id), " .
       "    	A.dt_cancelamento is not null," .
       "    	A.creditos_aprov," .
       "    	A.carga_horaria_aprov, " .
       "        turno_curso(A.ref_curso), " .
       "        turno_disciplina_ofer(A.ref_disciplina_ofer), " .
       "        get_creditos(A.ref_disciplina), " .
       "        get_creditos(A.ref_disciplina_subst) " .
       " from matricula A, disciplinas_ofer B" .
       " where A.ref_contrato='$ref_contrato' and  " .
       "       A.ref_periodo='$ref_periodo' and" .
       "       A.ref_disciplina_ofer = B.id";

$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

for ( $row=0; $query->MoveNext(); $row++ )
{
  list ($id, 
      	$ref_campus_ofer,
        $ref_disciplina,
    	$descricao_disciplina,
        $ref_curso_subst,
    	$curso_desc,
        $ref_disciplina_subst,
    	$descricao_disciplina_subst,
        $ref_disciplina_ofer,
    	$dia_semana,
    	$is_cancelada,
    	$creditos_aprov,
    	$carga_horaria_aprov,
        $turno_curso,
        $turno_disciplina_cancel,
        $num_creditos_disciplina_cancel,
        $num_creditos_disciplina_subst_cancel) = $query->GetRowValues();

  if ($ref_disciplina_subst)
  {
      $creditos_disciplina_cancel = $num_creditos_disciplina_subst_cancel;
  }
  else
  {
      $creditos_disciplina_cancel = $num_creditos_disciplina_cancel;
  }
  
  if ( ( $row % 2 ) == 0 )
  {

      </script>
        <tr bgcolor="#FFFFEE" valign="middle">
          <td width="76"><font face="Verdana" size="2" color="#000099"><?

      if ($is_cancelada == 't')
      {
        echo('<font color=red> [C] </font> ' . $id);
      }
      else
      {
        echo("<a href=\"javascript:CancelaDisciplina('$ref_pessoa','$ref_contrato','$ref_periodo','$ref_disciplina_ofer','$ref_disciplina','$curso','$ref_periodo','$ref_campus','$id','$fl_tx_cancel','$mes','$mes_resto','$carga_horaria_aprov','$ref_disciplina_subst','$ref_curso_subst','$creditos_diurno','$creditos_noturno','$creditos_disciplina_cancel','$turno_disciplina_cancel','$turno_curso')\">" .
        "<img src=\"../images/delete.gif\" border=0 title=\"Cancela a disciplina\"></a>" .
        "$id");
      }
      ?></font></td>
          <td width="276"><font face="Verdana" size="2" color="#000099"><?php

      $sql2 = "select ref_campus from contratos where ref_pessoa = $ref_pessoa and ref_curso = $curso";
      $query22 = $conn->CreateQuery($sql2);
      $query22->MoveNext();
      $ref_campus_aux  = $query22->GetValue(1);
      if ($ref_campus_ofer != $ref_campus_aux)
      {
        echo("<img src=\"../images/checkoff.gif\" title=\"fora sede\">");
      }
      else
      {
        echo("<img src=\"../images/checkon.gif\" title=\"na da sede\">");
      }
      ?><font size="1"><?echo($ref_disciplina . ' - ' . substr($descricao_disciplina,0,30));?>&nbsp;</font></font></td>
          <td width="97">
            <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_ofer);?><font color="#FF3333">&nbsp;<?echo(' dia ' . $dia_semana);?></font>&nbsp;</font></div>
          </td>
          <td width="66">
            <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$curso_desc\">");?></font><font face="Verdana" size="2" color="#FF0033">curso&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo("$ref_curso_subst");?></font></div>
          </td>
          <td width="74">
            <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$descricao_disciplina_subst\">");?>&nbsp;<font color="#FF0000">disc&nbsp;</font><?echo($ref_disciplina_subst);?></font></div>
          </td>
        </tr>
        <script language="PHP">

  }

  else
  {

    </script>
      <tr bgcolor="#EEEEFF" valign="middle">
        <td width="76"><font face="Verdana" size="2" color="#000099"><?
    if ($is_cancelada == 't')
    {
      echo('<font color=red> [C] </font> ' . $id);
    }
    else
    {
      echo("<a href=\"javascript:CancelaDisciplina('$ref_pessoa','$ref_contrato','$ref_periodo','$ref_disciplina_ofer','$ref_disciplina','$curso','$ref_periodo','$ref_campus','$id','$fl_tx_cancel','$mes','$mes_resto','$carga_horaria_aprov','$ref_disciplina_subst','$ref_curso_subst','$creditos_diurno','$creditos_noturno','$creditos_disciplina_cancel','$turno_disciplina_cancel','$turno_curso')\">" .
      "<img src=\"../images/delete.gif\" border=0 title=\"Cancela a disciplina\"></a>" .
      "$id");
    }
    ?></font></td>
        <td width="276"><font face="Verdana" size="2" color="#000099"><?php

    $sql2 = "select ref_campus from contratos where ref_pessoa = $ref_pessoa and ref_curso = $curso";
    $query22 = $conn->CreateQuery($sql2);
    $query22->MoveNext();
    $ref_campus_aux  = $query22->GetValue(1);
    if ($ref_campus_ofer != $ref_campus_aux)
    {
      echo("<img src=\"../images/checkoff.gif\" title=\"fora sede\">");
    }
    else
    {
      echo("<img src=\"../images/checkon.gif\" title=\"na da sede\">");
    }
    ?><font size="1"><?echo($ref_disciplina . ' - ' . substr($descricao_disciplina,0,30));?>&nbsp;</font></font></td>
        <td width="97">
          <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_ofer);?><font color="#FF3333">&nbsp;<?echo(' dia ' . $dia_semana);?></font><font color="#FF0000">&nbsp;</font></font></div>
        </td>
        <td width="66">
          <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$curso_desc\">");?></font><font face="Verdana" size="2" color="#FF0000">curso&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo("$ref_curso_subst");?></font></div>
        </td>
        <td width="74">
          <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$descricao_disciplina_subst\">");?>&nbsp;<font color="#FF0000">disc&nbsp;</font></font><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_subst);?></font></div>
        </td>
      </tr>
      <?

  }
}

$query->Close();
$conn->Close();

?>
</table>

<p>&nbsp;</p></body>
</html>
