<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../generico/busca_nome.php3"); ?>
<?
  $op_opcoes2 = SQLArray("$sql_periodos_academico");
  $op_opcoes3 = SQLArray("select id || '  ' || substr(descricao,1,30),id from motivos order by id");
?>
<html>
<head>
<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_periodo);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.ref_motivo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>

</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="../relat/carta_devedores_motivos_ps.php3" name="myform">
  <table width="90%" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Carta para Alunos por Motivo de desativação do Contrato </b></font></td>
    </tr>
    <tr> 
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo&nbsp;</font></td>
      <td> 
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> <font color="#000000"> 
              <input name="ref_periodo" type=text onChange="ChangeCode('ref_periodo','op2')" value="<?echo($ref_periodo);?>" size="10" maxlength="10">
	     </td>
	     <td>
              <script language="PHP">
                ComboArray("op2",$op_opcoes2,$ref_periodo,"ChangeOp2()");
              </script>
             </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Motivo</font></td>
      <td>
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="11%"> <font color="#000000">
              <input name="ref_motivo" type=text onChange="ChangeCode('ref_motivo','op3')" value="<?echo($ref_motivo);?>" size="10" maxlength="10">
              </font></td>
            <td width="89%"><font color="#000000">
              <script language="PHP">
                 ComboArray("op3",$op_opcoes3,$ref_motivo,"ChangeOp3()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data de Cancelamento</font></td>
      <td>
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="11%">
	       <input name="dt_cancelamento" type=text value="10-07-2002" size="10" maxlength="10">
            </td>
            <td width="89%"><font color="#000000">
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data de Regularização</font></td>
      <td>
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="11%">
	       <input name="dt_regularizacao" type=text value="29-07-02 à 03-08-02" size="30" maxlength="30">
            </td>
            <td width="89%"><font color="#000000">
              </font></td>
          </tr>
        </table>
      </td>
    </tr>

    
    <tr>
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"  value=" Imprimir ">
        <input type="reset"  name="Submit2" value="  Limpar  ">
        <input type="button" name="voltar"  value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
  </form>
</body>
</html>
