<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Confirmação de Matrícula</title>
<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $ref_periodo == '' )
{
  list ( $ref_periodo ) = QueryExecute($sql_periodos_academico);
  $ref_periodo = trim(substr($ref_periodo, 0, strpos($ref_periodo, "/")));
}
$op_result = SQLArray($sql_periodos_academico);
/*
$sql = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$ref_periodo' " .
       " order by A.id;" ;
*/
$sql = " select distinct A.id||' / '||A.abreviatura as d, " .
      "        A.id " .
      " from cursos A, matricula B " .
      " where A.id = B.ref_curso and " .
      "       B.ref_periodo = '$ref_periodo' " .
      " order by A.id;" ;

$op_result1 = SQLArray($sql);

</script>

<script language="JavaScript">

function Carta_Tecnico(ref_periodo, curso_id, datas_ajuste, DataImpressao, num_oficio)
{
    location="/relat/confirmacao_matricula_tecnico_ps.php3" +  
    	     "?ref_periodo=" + document.myform.ref_periodo.value + 
    	     "&curso_id=" + document.myform.curso_id.value + 
	         "&datas_ajuste=" + document.myform.datas_ajuste.value + 
	         "&DataImpressao=" + document.myform.DataImpressao.value + 
    	     "&num_oficio=" + document.myform.num_oficio.value;
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);

  document.myform.action = 'confirmacao_matricula.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.curso_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'ref_periodo')
      {
        document.myform.action = 'confirmacao_matricula.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="../relat/confirmacao_matricula_ps.php3" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Confirmação de matrícula</b></font></td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td>
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="curso_id" onChange="ChangeCode('curso_id','op1')" size="8">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op1",$op_result1,$curso_id,"ChangeOp1()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="85"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data(s) de ajuste(s):</font></td>
      <td colspan="2">
        <input type="text" name="datas_ajuste" value="26 a 31/07/2004" size="15"></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="85"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Prazo limite para trocas de disciplinas trancadas (dd-mm-aaaa):</font></td>
      <td colspan="2">
        <font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">Data:</font><input type="text" name="data_troca" value="31/07/2004" size="10" maxlength="10">
        <font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">Telefone:</font><input type="text" name="fone_troca" value="3714-7010" size="9" maxlength="9">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="85"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Período de recesso:</font></td>
      <td colspan="2">
        <input type="text" name="datas_recesso" value="" size="20" maxlength="19"></font><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">Caso não tenha período de recesso, deixe em branco este campo.</font>
      </td>
    </tr>

    <tr>
      <td bgcolor="#CCCCFF" width="85"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Emissão</font></td>
      <td colspan="2">
        <input type="text" name="DataImpressao" value="<? echo date("d/m/Y") ?>" size="10"></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="85"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Número Ofício</font></td>
      <td colspan="2">
        <input type="text" name="num_oficio" value="" size="3"></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Tipo:</font></td>
       <td>
      	<INPUT type="radio" name="opcao" value="1" checked>Graduação&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="opcao" value="2">Técnico
       </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
        <input type="submit" name="Submit"   value="  Gerar  ">
        
	    <!--<input type="button" name="Submit2"  value="  Técnico  " onClick="Carta_Tecnico('<?=$ref_periodo?>','<?=$curso_id?>','<?=$datas_ajuste?>','<?=$DataImpressao?>','<?=$num_oficio?>')">-->
        
        <input type="button" name="Button2" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
