<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<html>
<head>
<title>Grupos de Disciplinas</title>
<script language="JavaScript">
function _init()
{
  document.myform.id.focus();
}
</script>
<script language="PHP">
$hasmore = false;

function ListaGruposDisciplinas()
{
  global $id, $descricao, $hasmore;
  global $like;

  $descricao = strtoupper($descricao);

  $count = 0;

  $like = "";
  
  if ( $id != "" )
    $like = "$id";

  if ( $descricao != "" )
    $like = "$like% $descricao%";

  else if ( $like != "" )
    $like = "$like%";
     
  if ( $like != "" )
  {
    
    $bg0 = "#000000";
    $bg1 = "#EEEEFF";
    $bg2 = "#FFFFEE";

    $fg0 = "#FFFFFF";
    $fg1 = "#000099";
    $fg2 = "#000099";

    $conn = new Connection;
  
  $conn->Open();

  $sql = "select id, descricao" .
         "  from grupos_disciplinas";

  $where = '';

   if ( $id != '' )
  {
    $where .= ( $where == '' ) ? ' where ' : ' and ';
    $where .= "id = $id";
  }

  if ( $descricao != '' )
  {
    $where .= ( $where == '' ) ? ' where ' : ' and ';
    $where .= "upper(descricao) like upper('$descricao%')";
  }

  $sql .= $where . " order by descricao";

  $query = $conn->CreateQuery($sql);

    echo("<table width=\"490\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
    
    echo("  <tr bgcolor=\"$bg0\">\n");
    echo("    <td width=\"20%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Código</font></b></td>\n");
    echo("    <td width=\"70%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Descrição</font></b></td>\n");
    echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
    echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
    echo("  </tr>\n");

  for ( $i=0; $i<25 && $query->MoveNext(); $i++ )
    {
    
      list ( $id,$nome ) = $query->GetRowValues();
      
      if ( $i % 2 )
      {
        $bg = $bg1;
        $fg = $fg1;
      }
      
      else
      {
        $bg = $bg2;
        $fg = $fg2;
      }

      if ( empty($campo) )
        $campo = '';

    $registro = $query->GetValue(1);
    $href  = "<a href=\"grupos_disciplinas_altera.phtml?id=$id\"><img src=\"../images/update.gif\" title='Alterar' align='absmiddle' border=0></a>";
    $href1 = "<a href=\"javascript:Confirma_Exclui('$registro')\"><img src=\"../images/delete.gif\" title='Excluir' align='absmiddle' border=0></a>";


      echo("  <tr bgcolor=\"$bg\">\n");
      echo("    <td width=\"20%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$id</font></b></td>\n");
      echo("    <td width=\"70%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$nome</font></b></td>\n");
      echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href</font></b></td>\n");
      echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href1</font></b></td>\n");
      echo("  </tr>\n");
    }

    echo("</table>");

    $hasmore = $query->MoveNext();

    $query->Close();

    $conn->Close();

    $count = $i;
  }

  else
    echo("<br><center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center><br>");

  return $count;
}
</script>
<script language="JavaScript">
function Confirma_Exclui(arg1)
{
  url = 'post/grupos_disciplinas_exclui.php3?id=' + arg1;

  if (confirm("Você tem certeza que deseja EXCLUIR o Grupo de Disciplina: "+arg1+" ?"))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="consulta_inclui_grupos_disciplinas.phtml" name="myform">
  <div align="center"> 
    <p> 
      <input type="button" value="  Incluir  " onClick="location='grupos_disciplinas.phtml'" name="button">
      <input type="button" value="   Sair   " onClick="javascript:history.go(-1)" name="Button2">
      <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
      </font></b></font></font> <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
      </font></b></font></font> <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
      </font></b></font></font> </p>
    </div>
  <hr align="center" width="500">
  <p align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O DUPLICAR CADASTROS !</font></b></font> </p>
  <div align="center"> 
    <table width="500" border="0" cellspacing="0" cellpadding="2" height="100">
      <tr bgcolor="#0066CC"> 
        <td colspan="4" height="28"> 
          <div align="center"><font size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o de Grupos de Disciplinas</font></b></font></div>
        </td>
      </tr>
      <tr> 
        <td width="6">&nbsp;</td>
        <td width="50"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">C&oacute;digo:</font> 
        </td>
        <td width="271"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Descri&ccedil;&atilde;o:</font> 
        </td>
        <td width="40">&nbsp; </td>
      </tr>
      <tr> 
        <td width="6">&nbsp;</td>
        <td width="50"> 
          <input type="text" name="id" size="8" value="<?echo($id)?>">
        </td>
        <td width="271"> 
          <input type="text" name="descricao" size="40" value="<?echo($descricao)?>">
        </td>
        <td width="40"> 
          <input type="submit" name="botao" value="Localizar">
        </td>
      </tr>
      <tr> 
        <td colspan="4" align="center"> 
          <hr size="1" width="490">
        </td>
      </tr>
      <tr> 
        <td colspan="4"> <?PHP ListaGruposDisciplinas(); ?> <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
          </font><font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"><?PHP  if ( $hasmore )
                 echo("<BR><center>Se o Grupo da Disciplina não estiver listado, seja mais específico.</center>"); ?></font></b></font></font><font color="#FF0000"> 
          </font></b></font></font> </td>
      </tr>
      <tr align="center"> 
        <td colspan="4"> 
          <hr size="1" width="490">
        </td>
      </tr>
    </table>
  </div>
</form>
</body>
</html>
