<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Consulta Reprovados</title>

<script language="PHP">

$op_result = SQLArray($sql_periodos_academico);

</script>

<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

</script>

</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" name="myform" action="post/consulta_reprovados2.php3">
<TABLE width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta alunos que repetiram um determinado número de disciplinas ou mais</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo Atual</font></td>
      <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="periodo_id" onChange="ChangeCode('periodo_id','op')" size="8" value="<?echo($periodo_id)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Número de Disciplinas</font></td>
      <td> 
        <INPUT name="num_disc" type="text" value="" size="5" maxlength="5">
      </td>
    </tr>
    <tr>
      <td width="92" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Mostrar Professores?</font></td>
       <td>
      	<INPUT type="radio" name="mostrar_professores" value="1">Sim&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="mostrar_professores" value="2" checked>Não
       </td>
    </tr>

    <tr>
      <td width="92" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Tipo de Curso</font></td>
      <td>
         <script language="PHP">
         $conn = new Connection;
         $conn->Open();

         // Query
         $sql = " select id, " .
                "        substr(descricao,0,40) " .
                " from tipos_curso " .
                " order by id";

         @$query = $conn->CreateQuery($sql);
         $i = 1;
         </script>
         
         <SELECT multiple name="tipos_curso[]" size="5">
         
         <script language="PHP">
         while ($query->MoveNext())
         {
             list($tipo_curso_id,
                  $tipo_curso_desc) = $query->GetRowValues();
         </script>
         
           <OPTION value='<?echo($tipo_curso_id);?>'><?echo("$tipo_curso_id - $tipo_curso_desc");?> 

         <script language="PHP">
         $i++;
         }
         $query->Close();
         $conn->Close();
         </script>
         </select>
      </td>
    </tr>
    <TR>
     <td colspan="2">
         <hr size="1">
     </td>
    </TR>
    <TR>
     <td colspan="2">
        <font color="#000099" size="2" face="Verdana, Arial, Helvetica, sans-serif">Obs.: Imprime todos os alunos que reprovaram em determinado número de disciplinas ou mais, exceto as disciplinas do Período Atual</font>
     </td>
    </TR>
    <TR>
     <td colspan="2">
         <hr size="1">
     </td>
    </TR>
    <tr>
     <td colspan="2" align="center">
       <INPUT type="submit" name="relatorio" value="  Gerar  ">
       <input type="button" name="Submit22"  value="  Sair  " onClick="javascript:history.go(-1)">
     </td>
    </tr>
</TABLE>
</form>
</body>
</html>

