<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Datas de Aula Remanejadas por Período</title>
<?
    $op_result = SQLArray($sql_periodos_academico);
?>

<script language="JavaScript">

function Confirma_Exclui(arg1)
{
  url = 'post/datas_aula_exclui.php3?id=' + arg1;

  if (confirm("Você tem certeza que deseja excluir a data de aula: "+arg1))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
}
</script>

<script language="PHP">

$hasmore = false;

function MostraDatasAula()
{  
    global $ref_periodo, $hasmore;
  
    if ( $ref_periodo != "" )
    {
        $conn = new Connection;

        $conn->Open();

        $sql = " select id, " .
               "        ref_periodo, " .
               "        ref_disciplina_ofer, " .
               "        ref_disciplina_ofer_compl, " .
               "        get_disciplina_de_disciplina_of(ref_disciplina_ofer), " .
               "        descricao_disciplina(get_disciplina_de_disciplina_of(ref_disciplina_ofer)), " .
               "        to_char(data_nova,'dd-mm-yyyy'), " .
               "        to_char(data_antiga,'dd-mm-yyyy') " .
               " from calendario_academico_compl " . 
               " where ref_periodo = '$ref_periodo' " .
               " order by ref_disciplina_ofer";

        $query = $conn->CreateQuery($sql);

        echo("<center><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
        echo("<tr bgcolor=\"#000000\">\n");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Id</b></font></td>");
        echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
        echo ("<td width=\"35%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Descricao</b></font></td>");
        echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Oferta</b></font></td>");
        echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Compl Oferta</b></font></td>");
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Data&nbsp;Antiga</b></font></td>");
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Data&nbsp;Nova</b></font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo("  </tr>"); 

        $i=1;

        // cores fundo
        $bg0 = "#000000";
        $bg1 = "#EEEEFF";
        $bg2 = "#FFFFEE";

        // cores fonte
        $fg0 = "#FFFFFF";
        $fg1 = "#000099";
        $fg2 = "#000099";
 
        while( $query->MoveNext() )
        {
            list ($id,
                  $ref_periodo,
                  $ref_disciplina_ofer,
                  $ref_disciplina_ofer_compl,
                  $ref_disciplina,
                  $descricao_disciplina,
                  $data_nova,
                  $data_antiga) = $query->GetRowValues();
            
            $href  = "<a href=\"datas_aula_altera.phtml?id=$id\"><img src=\"../images/update.gif\" title='Alterar Cadastro' align='absmiddle' border=0></a>";
            $href1 = "<a href=\"javascript:Confirma_Exclui('$id')\"><img src=\"../images/delete.gif\" title='Excluir Cadastro' align='absmiddle' border=0></a>";

            if ( $i % 2)
            {
                $bg = $bg1;
                $fg = $fg2;
            }
            else
            {
                $bg = $bg2;
                $fg = $fg1;
            }
            
            echo("<tr bgcolor=\"$bg1\">\n");
            echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$id</td>");
            echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$ref_disciplina</td>");
            echo ("<td width=\"45%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$descricao_disciplina</td>");
            echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$ref_disciplina_ofer</td>");
            echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$ref_disciplina_ofer_compl</td>");
            echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$data_antiga</td>");
            echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$data_nova</td>");
            echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href</td>");
            echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href1</td>");

            echo("  </tr>");


            $i++;

        }

        echo("</table></center>");
        $query->Close();
        $conn->Close();
    }
    else
        echo("<br><center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center><br>");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="consulta_inclui_datas_aulas.phtml" name="myform">
  <div align="center"> 
    <p> 
      <input type="button" name="button"  value=" Incluir " onClick="location='datas_aula_inclui.phtml'">
      <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
    </p>
   </div>
  <hr align="center" width="490">
  <p align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O DUPLICAR CADASTROS !</font></b></font> </p>
  <div align="center"> 
    <table width="90%" border="0" cellspacing="0" cellpadding="2">
      <tr bgcolor="#0066CC"> 
        <td colspan="4" height="28"> 
          <div align="center"><font size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o de Datas de Aulas Remanejadas por Período</font></b></font></div>
        </td>
      </tr>
      <tr><td>&nbsp;</td></tr>
      <tr> 
        <td bgcolor="#CCCCFF" width="50"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp;Período:&nbsp;&nbsp;</font></td>
            <td>
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
        		ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script></font></td>	
            <td width="40"> 
          <input type="submit" name="botao" value="Localizar">
          </td>
      </tr>
      <tr> 
        <td colspan="4" align="center"> 
          <hr size="1" width="490">
        </td>
      </tr>
      <tr> 
        <td colspan="4"> <?PHP MostraDatasAula(); ?> <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
          </font><font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000">
	  <?PHP  if ( $hasmore )
          echo("<BR>Se a informação não estiver listada, seja mais específico."); ?>
	  </font></b></font></font><font color="#FF0000"> 
          </font></b></font></font> </td>
      </tr>
      <tr align="center"> 
        <td colspan="4"> 
          <hr>
        </td>
      </tr>
    </table>
  </div>
</form>
</body>
</html>
