<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Líderes de Turma</title>
<?
    $op_result = SQLArray($sql_periodos_academico);
?>

<script language="JavaScript">

function Confirma_Exclui(arg1)
{
  url = 'post/lideres_exclui.php3?id=' + arg1;

  if (confirm("Você tem certeza que deseja excluir o líder da turma: "+arg1))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
}
</script>

<script language="PHP">

$hasmore = false;

function MostraLideres()
{  
    global $ref_periodo, $hasmore;
  
    if ( $ref_periodo != "" )
    {
        $conn = new Connection;

        $conn->Open();

        $sql = " select A.id, " .
               "        A.ref_periodo, " .
               "        A.ref_disciplina_ofer, " .
               "        A.ref_disciplina_ofer_compl, " .
               "        get_disciplina_de_disciplina_of(A.ref_disciplina_ofer), " .
               "        descricao_disciplina(get_disciplina_de_disciplina_of(A.ref_disciplina_ofer)),".
               "        A.ref_pessoa, " .
               "        B.nome, " .
               "        B.email, " .
               "        B.fone_particular, " .
               "        B.fone_profissional, " .
               "        B.fone_celular, " .
               "        B.fone_recado " .
               " from lideres A, pessoas B " . 
               " where A.ref_pessoa = B.id and " .
               "       A.ref_periodo = '$ref_periodo' " .
               " order by B.nome";

        $query = $conn->CreateQuery($sql);

        echo("<center><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
        echo("<tr bgcolor=\"#000000\">\n");
        echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
        echo ("<td width=\"35%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Disciplina</b></font></td>");
        echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
        echo ("<td width=\"35%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Aluno</b></font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo("  </tr>"); 
               
        $i=1;

        // cores fundo
        $bg0 = "#000000";
        $bg1 = "#EEEEFF";
        $bg2 = "#FFFFEE";

        // cores fonte
        $fg0 = "#FFFFFF";
        $fg1 = "#000099";
        $fg2 = "#000099";
 
        while( $query->MoveNext() )
        {
            list ($id,
                  $ref_periodo,
                  $ref_disciplina_ofer,
                  $ref_disciplina_ofer_compl,
                  $ref_disciplina,
                  $descricao_disciplina,
                  $ref_pessoa,
                  $nome_pessoa,
                  $email_pessoa,
                  $fone_particular,
                  $fone_profissional,
                  $fone_celular,
                  $fone_recado) = $query->GetRowValues();

            if ($i == 1)
            {
                $lista_lideres = ";Listagem de Líderes de Turma $ref_periodo;;;;;;;\n";
                $lista_lideres .= "Código;Disciplina;Código;Aluno;E-mail;Fone Particular;Fone Profissional;Fone Celular;Fone Recado\n";
            }

            $lista_lideres .="$ref_disciplina;$descricao_disciplina;$ref_pessoa;$nome_pessoa;$email_pessoa;$fone_particular;$fone_profissional;$fone_celular;$fone_recado\n";

            $nome_pessoa = "<a href=\"mailto:$email_pessoa\">$nome_pessoa</a>";
           
            $href  = "<a href=\"lideres_altera.phtml?id=$id\"><img src=\"../images/update.gif\" title='Alterar Cadastro' align='absmiddle' border=0></a>";
            $href1 = "<a href=\"javascript:Confirma_Exclui('$id')\"><img src=\"../images/delete.gif\" title='Excluir Cadastro' align='absmiddle' border=0></a>";

            if ( $i % 2)
            {
                $bg = $bg1;
                $fg = $fg2;
            }
            else
            {
                $bg = $bg2;
                $fg = $fg1;
            }
            
            echo("<tr bgcolor=\"$bg1\">\n");
            echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$ref_disciplina</td>");
            echo ("<td width=\"35%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$descricao_disciplina</td>");
            echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$ref_pessoa</td>");
            echo ("<td width=\"35%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$nome_pessoa</td>");
            echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href</td>");
            echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href1</td>");

            echo("  </tr>");


            $i++;

        }                       

        echo("</table></center>");
       
        echo("<hr>");
        $filename = 'lista_lideres_' . $ref_periodo . '.csv';
        $fp = fopen($filename, "w");
        fwrite($fp, $lista_lideres);
        fclose($fp);

        echo("<center><a href=\"$filename\">Salvar em Planilha</a></center>");
        
        $query->Close();
        $conn->Close();
    }
    else
        echo("<br><center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center><br>");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="consulta_inclui_lideres.phtml" name="myform">
  <div align="center"> 
    <p> 
      <input type="button" name="button"  value=" Incluir " onClick="location='lideres_inclui.phtml'">
      <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
    </p>
   </div>
  <hr align="center" width="490">
  <p align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O DUPLICAR CADASTROS !</font></b></font> </p>
  <div align="center"> 
    <table width="90%" border="0" cellspacing="0" cellpadding="2">
      <tr bgcolor="#0066CC"> 
        <td colspan="4" height="28"> 
          <div align="center"><font size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o Líderes de Turma</font></b></font></div>
        </td>
      </tr>
      <tr><td>&nbsp;</td></tr>
      <tr> 
        <td bgcolor="#CCCCFF" width="50"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp;Período:&nbsp;&nbsp;</font></td>
            <td>
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
        		ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script></font></td>	
            <td width="40"> 
          <input type="submit" name="botao" value="Localizar">
          </td>
      </tr>
      <tr> 
        <td colspan="4" align="center"> 
          <hr size="1" width="490">
        </td>
      </tr>
      <tr> 
        <td colspan="4"> <?PHP MostraLideres(); ?> 
        <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000">
	    <?
        if ( $hasmore )
            echo("<BR>Se a informação não estiver listada, seja mais específico."); 
        ?>
	    </font></b></font></font> 
        </td>
      </tr>
      <tr align="center"> 
        <td colspan="4"> 
          <hr>
        </td>
      </tr>
    </table>
  </div>
</form>
</body>
</html>
