<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Consulta Repetencias</title>

<script language="PHP">

$op_result = SQLArray($sql_periodos_academico);

</script>

<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function acao(cod_acao)
{
    if (cod_acao == '1')
    {
        window.document.myform.action="post/consulta_repetencias.php3";
    }

    if (cod_acao == '2')
    {
        window.document.myform.action = "post/consulta_repetencias2.php3";
    }
}

</script>

</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" name="myform">
<TABLE width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta alunos que estão repetindo disciplinas em determinado período</b></font></td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="periodo_id" onChange="ChangeCode('periodo_id','op')" size="8" value="<?echo($periodo_id)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <TR>
     <td colspan="2">
         <hr size="1">
     </td>
    </TR>
    <tr>
     <td colspan="2" align="center">
       <INPUT type="submit" name="relatorio2" value=" Gerar por Ordem de Curso e Disciplina " onclick="javascript:acao('2')"><br>
       <INPUT type="submit" name="relatorio1" value=" Gerar por Ordem de Aluno " onclick="javascript:acao('1')"><br>
       <input type="button" name="Submit22" value="  Sair  " onClick="javascript:history.go(-1)">
     </td>
    </tr>
</TABLE>
</form>
</body>
</html>

