<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Cunsultas de Número de Alunos</title>

<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $ref_periodo == '' )
{
  list ( $ref_periodo ) = QueryExecute($sql_periodos_academico);
  $ref_periodo = trim(substr($ref_periodo, 0, strpos($ref_periodo, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

</script>

<script language="JavaScript">
function Lista_Cursos1()
{
    location="consulta_matriculas.phtml" +
             "?ref_periodo=" + document.myform.ref_periodo.value;
}

function Lista_Cursos2()
{
    location="cons_numalu_curso_campus.php3" +
             "?ref_periodo=" + document.myform.ref_periodo.value;
}

function Lista_Cursos3()
{
    location = "cons_numalu_credito_curso.php3" +
               "?ref_periodo=" + document.myform.ref_periodo.value + 
               "&dt_livro_matricula=" + document.myform.dt_livro_matricula.value + 
               "&anterior=" + document.myform.anterior.checked;
}

function Lista_Cursos4()
{
    location="cons_numalu_curso_disciplina.php3" +
             "?ref_periodo=" + document.myform.ref_periodo.value + 
             "&dt_livro_matricula=" + document.myform.dt_livro_matricula.value + 
             "&anterior=" + document.myform.anterior.checked;
}

function Lista_Cursos5()
{
    location="cons_numalu_turma.php3" +
             "?ref_periodo=" + document.myform.ref_periodo.value +
             "&dt_livro_matricula=" + document.myform.dt_livro_matricula.value + 
             "&anterior=" + document.myform.anterior.checked;
}

function Lista_Cursos6()
{
    location="cons_numalu_curso_vest.php3" +
             "?ref_periodo=" + document.myform.ref_periodo.value +
             "&dt_livro_matricula=" + document.myform.dt_livro_matricula.value + 
             "&anterior=" + document.myform.anterior.checked;
}
</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="cons_numalu_curso.php3" name="myform">
<table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
  <tr> 
    <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta do Número de Alunos</b></font></td>
  </tr>
  <tr> 
    <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
    <td width="296"> <font color="#000000"> </font> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td> 
            <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
          </td>
          <td>&nbsp;</td>
          <td width="100%"><font color="#000000"> 
            <script language="PHP">
              ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
            </script>
            </font></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;É um Período<br>&nbsp;Antigo?:</font>
    </td>
    <td>
      <input type="checkbox" name="anterior" value="1">
      <input type="text" name="dt_livro_matricula" size="15" maxlength="15" value="">
      <font face="Arial, Helvetica, sans-serif" size="2" color="#000099">Se for, informe a data (dd-mm-aaaa) de Geração do Livro Matrícula.</font>
    </td>
  </tr>
  <tr>
    <td colspan="2" align="center"> <hr> </td>
  </tr>
</table>
<div align="center"> 
  <p>
     <input type="submit" name="Submit"  value="  Número de Alunos Matriculados por Curso (*) ">
  </p>
  <p> 
     <input type="button" name="Button1" value=" Número de Alunos N&atilde;o Matriculados por Curso" onClick="javascript:Lista_Cursos1()">
  </p>
  <p> 
     <input type="button" name="Button2" value=" Número de Alunos por Curso e Campus (Ativo + Passivo) " onClick="javascript:Lista_Cursos2()">
  </p>    
  <p> 
     <input type="button" name="Button3" value=" Número de Alunos por Número de Créditos (*) " onClick="javascript:Lista_Cursos3()">
  </p>
  <p> 
     <input type="button" name="Button4" value=" Número de Alunos Matriculados por Curso e Disciplina (*) " onClick="javascript:Lista_Cursos4()">
  </p>
  <p> 
     <input type="button" name="Button5" value=" Número de Alunos Matriculados por Turma e Dia da Semana (*) " onClick="javascript:Lista_Cursos5()">
  </p>  
  <p>
     <input type="button" name="Button6"  value="Número de Alunos Matriculados por Curso separando Vestibular (**)" onClick="javascript:Lista_Cursos6()">
  </p>
  <p>
     <input type="button" name="voltar" value="  Sair  " onClick="javascript:history.go(-1)">
  </p>
</div>
<table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
  <tr>
    <td colspan="2" align="center"> <hr> </td>
  </tr>
  <tr> 
    <td colspan="2"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="red"><b>&nbsp;(*)&nbsp;</b></font><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099">Opções que utilizam o parâmetro "Período Antigo"</td>
  </tr>
  <tr> 
    <td colspan="2"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="red"><b>&nbsp;(**)&nbsp;</b></font><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099">Nesta opção. marque o campo "Período Antigo" e coloque o código do vestibular no campo data livro matricula.</td>
  </tr>
  <tr>
    <td colspan="2" align="center"> <hr> </td>
  </tr>
</table>
</form>
</body>
</html>
