<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>

<html>
<head>

<script language="PHP">

$op_result = SQLArray($sql_periodos_academico);
$sql   = "select id||' / '||abreviatura as d,id from cursos order by d";
$op_result1 = SQLArray($sql);
$sql   = "select id||' / '||nome_campus as d,id from campus order by d";
$op_result2 = SQLArray($sql);
$sql   = "select id||' / '||descricao as d, id from vestibular order by dt_ordem desc";
$op_result4 = SQLArray($sql);

</script>

<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;
  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeOp4()
{
  ChangeOption(document.myform.op4,document.myform.vest_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function buscaPessoa()

{
  var url = '../generico/post/lista_pessoas.php3' +
            '?pnome=' + escape(document.myform.pnome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2)

{
  document.myform.pessoa.value = arg1;
  document.myform.pnome.value = arg2;
}


</script>

</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">

<form method="post" action="/relat/contrato_prest_servicos_grad.php3" name="myform">
<CENTER>
<TABLE width="90%" border="0" cellspacing="2" cellpadding="0">

    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Contrato de Prestação de Serviços Educacionais - Graduação</b></font></td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">

          <tr>
            <td>

              <input type="text" name="periodo_id" size="8" onChange="ChangeCode('periodo_id','op')" value="">

            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">

              <script language="PHP">
                 ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>

              </font></td>
          </tr>

      </table>
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Curso:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">

          <tr>
            <td>

              <input type="text" name="ref_curso" size="8" onChange="ChangeCode('ref_curso','op1')" value="">

            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">

              <script language="PHP">
                 ComboArray("op1",$op_result1,$ref_curso,"ChangeOp1()");
              </script>

              </font></td>
          </tr>

      </table>
      </td>
    </tr>
    <tr>
      <TD width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Campus:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">

          <tr>
            <td>

              <input type="text" name="ref_campus" size="8" onChange="ChangeCode('ref_campus','op2')" value="">

            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">

              <script language="PHP">
                ComboArray("op2",$op_result2,$ref_campus,"ChangeOp2()");
              </script>

              </font></td>
          </tr>

      </table>
      </td>
    </tr>
        <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Aluno:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
                <td>
                <input type="text" name="pessoa" size="8" maxlength="10">
                &nbsp;
                <input type="text" name="pnome" size="31" maxlength="20">
                <input type="button" value="..." onClick="buscaPessoa()" name="button">

          </tr>


      </table>
      </td>
     </tr>
     <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Status:</font></td>
      <td>
        <table>
            <tr>
                <td>
                    <INPUT type="radio" name="bixo" value="nao" checked>Graduação&nbsp;&nbsp;&nbsp;&nbsp;
                    <INPUT type="radio" name="bixo" value="sim" onClick="Javascript:alert('AVISO! \nVocê está tentando imprimir o Contrato de Prestação de Serviços para calouros.\nPara isso ser possível, informe o código do Vestibular no campo Vestibular. \nAlém disso escolha ao lado a opção pela qual o candidato aprovou. \nCUIDADO: Executando esta operação o Número do Contrato de Prestação de \nServiços Educacionais (999999/99X) do(s) aluno(s) será recodificado!!!')">Calouros&nbsp;&nbsp;&nbsp;&nbsp;
                    <INPUT type="radio" name="bixo" value="outros" onClick="Javascript:alert('AVISO! \nEste botão gera contratos para Reingressos, Transferências, Portador de Diploma ...\nCUIDADO: Executando esta operação o Número do Contrato de Prestação de \nServiços Educacionais (999999/99X) do(s) aluno(s) será recodificado!!!')">Outros
                </td>
                <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Opção:</font></td>
                <td>
      	            <INPUT type="radio" name="opcao" value="1" checked>1ª Opção&nbsp;&nbsp;&nbsp;&nbsp;
      	            <INPUT type="radio" name="opcao" value="2">2ª Opção&nbsp;&nbsp;&nbsp;&nbsp;
      	            <INPUT type="radio" name="opcao" value="3">3ª Opção
                </td>
            </tr>
        </table>
       </td>
      </td>
     </tr>
     <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Vestibular:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">

          <tr>
            <td>

              <input type="text" name="vest_id" size="8" onChange="ChangeCode('vest_id','op4')" value="">

            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">

              <script language="PHP">
                 ComboArray("op4",$op_result4,$vest_id,"ChangeOp4()");
              </script>

              </font></td>
          </tr>

      </table>
      </td>
    </tr>
    <tr>
      <td colspan="2"><hr></td>
    </tr>
    <TR>
      <TD colspan="2" align="center">
        <INPUT type="submit" name="Submit" value=" Imprimir ">
        <INPUT type="button" name="voltar" value="  Voltar  " onclick="location='contratos_prest_serv.phtml'">
      </TD>
    </TR>
</TABLE>
</CENTER>
</form>
</body>
</html>
