<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
   $op1_opcoes = SQLArray($sql_periodos_academico);
?>
<html>
<head>
<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_periodo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function buscaDisciplina()
{
  var ref_periodo = document.myform.ref_periodo.value;

  if ( ref_periodo == '' )
  {
    alert("Código do período inválido ou não especificado!");
    return;
  }

  var url = "../generico/post/lista_disciplinas_ofer.php3" +
            "?ref_periodo=" + escape(ref_periodo) +
            "&desc=" + document.myform.descricao_disciplina.value;

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(ref_disciplina_ofer, descricao_disciplina, ref_disciplina_ofer_compl)
{
  document.myform.ref_disciplina_ofer.value = ref_disciplina_ofer;
  document.myform.descricao_disciplina.value = descricao_disciplina;
  document.myform.ref_disciplina_ofer_compl.value = ref_disciplina_ofer_compl;
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/datas_aula_inclui.php3" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> 
      <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>Inclusão de Datas de Aulas Remanejadas</b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo 
        </font>
      </td>
      <td width="80%"> 
        <input name="ref_periodo" type=text size="7" onChange="ChangeCode('ref_periodo','op1')" value="<?echo($ref_periodo)?>">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op1",$op1_opcoes,$ref_periodo,"ChangeOp1()");</script>
        </font>
      </td>
    </tr>

    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Código da Disciplina Oferecida&nbsp;</font></td>
      <td colspan="3" width="70%">
       <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
         <td>
            <input type=text name="ref_disciplina_ofer" size="7" maxlength="10">
            <input type="text" name="descricao_disciplina" size="30">
         </td>
         <td>
         <div align="right">
            <input type="button" value="..." onClick="buscaDisciplina()" name="button22"></div>
         </td>
        </tr>
       </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Código da Disciplina Oferecida Compl</font></td>
      <td> 
        <input name="ref_disciplina_ofer_compl" type=text size="7">
      </td>
    </tr>
    
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Nova<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td> 
        <input name="data_nova" type=text size="10" maxlength="10">
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Antiga<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td> 
        <input name="data_antiga" type=text size="10" maxlength="10">
      </td>
    </tr>

    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="reset" name="Submit2"  value=" Limpar ">
        <input type="button" name="Button2" value=" Voltar " onClick="location='consulta_inclui_datas_aulas.phtml'">
      </td>
    </tr>
  </table>
  </form>
  </body>
</html>
