<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../../../lib/config.php"); ?>
<?
    $op_result = SQLArray("select '----- Selecione o Periodo -----','' union all (select id||' / '||substr(descricao, 0, 25) as d,id from periodos order by coalesce(dt_inicial,'1900-01-01') desc)");
    $op_result1 = SQLArray("SELECT id || ' - ' || descricao, id FROM tipos_curso ORDER BY descricao");
?>
<html>
<head>
<title>Alunos Egressos</title>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_tipo_curso);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>
<body bgcolor="#FFFFFF">
<form method="post" action="post/egressos.php3" name="myform">
  <br><table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta Egressos</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"> <font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Inicial (dd/mm/aaaa):</font></td>
      <td width="70%">
        <input name="dt_inicial" type=text size="10" maxlength="10">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="30%"> <font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Final (dd/mm/aaaa):</font></td>
      <td width="70%">
        <input name="dt_final" type=text size="10" maxlength="10">
      </td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"><? ComboArray("op",$op_result,$ref_periodo,"ChangeOp()"); ?></font></td>
          </tr>   
        </table>
      </td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Trazer todos egressos:</font></td>
      <td width="296"> <font color="#000000"><input type="checkbox" name="todos_egressos" value="t" checked></font></td>
    </tr>
    <tr>
       <td colspan="2"><font face="Helvetica" size="2" color="#000099">
         <ul>
          <li>Serão listados todos os alunos que se formaram entre as datas iniciais e finais informadas e voltaram a estudar novamente após a formatura.</li>
          <li>Se o período for especificado, a listagem retornará apenas os alunos com matrícula no período selecionado.</li>
          <li>Se a opção 'Trazer todos egressos' não estiver selecionada, somente os cursos pertencentes ao período selecionado serão trazidos.</li>
         </ul>
       </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
      </td>
    </tr>
    <tr>
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit" value=" Listar ">
        <input type="button" name="Button3" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
