<? require("../../../lib/common.php"); ?>
<html>
<head>
  <title>Alunos Egressos que voltaram a estudar em determinado período</title>
</head>
<body bgcolor="#FFFFFF" onLoad="document.myform.dt_inicial.focus()">
<form method="post" action="post/egressos_que_retornaram.php3" name="myform">
  <br><table width="90%" border="0" cellspacing="2" cellpadding="1" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="3" height="28" align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta egressos que voltaram a estudar na instituição no período especificado</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" rowspan="3" align="center" width="20%"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Período de reingresso</font></td>
      <td bgcolor="#CCCCFF" width="20%"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Inicial (dd/mm/aaaa):</font></td>
      <td width="70%"><input name="dt_inicial" type=text size="10" maxlength="10"></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Final (dd/mm/aaaa):</font></td>
      <td><input name="dt_final" type=text size="10" maxlength="10"></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Tipo de Egresso:</font></td>
      <td>
         <INPUT type="radio" name="tipo_egresso" value="1" checked>Todos os Egressos&nbsp;
         <INPUT type="radio" name="tipo_egresso" value="2">Somente Egressos após a Formatura
      </td>
    </tr>
    
    <tr> 
      <td colspan="3" align="center"><hr size="1"></td>
    </tr>
    <tr>
      <td colspan="3" align="center"> 
        <input type="submit" name="Submit" value="  Listar  ">
        <input type="button" name="Button3" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
