<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/InvData.php3"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
  $op1_opcoes = SQLArray("select nome_campus, id from campus order by nome_campus");
  $op2_opcoes = SQLArray("select nome, id from dias order by id");
?>  
<html>
<head>
<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_campus);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.dia_semana);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>

<script language="PHP">
$conn = new Connection;

$conn->Open();

$aux_dt_exame = InvData($dt_exame);

$sql = " select ref_periodo," .
       "        ref_campus," .
       "        dt_exame," .
       "        descricao," .
       "        fl_exame," .
       "        dia_semana" .
       " from dt_exames_periodos " .
       " where ref_periodo = '$ref_periodo' and " .
       "       dt_exame = '$aux_dt_exame' and " .
       "       dia_semana = '$dia_semana' and " .
       "       ref_campus = '$ref_campus'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $ref_periodo,
       $ref_campus,
       $dt_exame,
       $descricao,
       $fl_exame,
       $dia_semana) = $query->GetRowValues();

$dt_exame = InvData($dt_exame);

$query->Close();

$conn->Close();

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="POST" action="post/exames_periodo_edita.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099">
      <td height="35" colspan="2" align="center">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Alteração de Datas de Exame</font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Período&nbsp;</font></td>
      <td> 
        <?echo($ref_periodo);?>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Campus</font>
      </td>
      <td width="80%"> 
        <input name="ref_campus" type=text size="7" onChange="ChangeCode('ref_campus','op1')" value="<?echo($ref_campus);?>">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op1",$op1_opcoes,$ref_campus,"ChangeOp1()");</script>
        </font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Exame&nbsp;<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td> 
        <input name="dt_exame" type=text value="<?echo($dt_exame);?>">
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descrição&nbsp;</font></td>
      <td> 
        <input name="descricao" type=text value="<?echo($descricao);?>">
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Flag Exame&nbsp;</font></td>
      <td> 
        <select name="fl_exame">
          <option value="<?echo($fl_exame);?>" selected><?echo($status[$fl_exame]); ?></option>
          <?if ($fl_exame == '0') 
	        { echo "<option value=\"1\">Sim</option>";}
	        if ($fl_exame == '1')
            { echo "<option value=\"0\">Não</option>";}
          ?>
        </select>
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Dia da Semana</font>
      </td>
      <td width="70%"> 
        <input name="dia_semana" type=text size="6" value="<?echo($dia_semana)?>" onChange="ChangeCode('dia_semana','op2')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op2",$op2_opcoes,$dia_semana,"ChangeOp2()");</script>
        </font>
      </td>
    </tr>
    
    
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="button" name="Submit2" value=" Voltar " onclick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
<input name="ref_periodo" type="hidden" value="<?echo($ref_periodo);?>">
<input name="ref_campus1" type="hidden" value="<?echo($ref_campus);?>">
<input name="dt_exame1" type="hidden" value="<?echo($dt_exame);?>">
<input name="descricao1" type="hidden" value="<?echo($descricao);?>">
<input name="dia_semana1" type="hidden" value="<?echo($dia_semana);?>">
<BR>
</form>
</body>
</html>
