<? header("Cache-Control: no-cache"); ?>
<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Listagem por motivo de Entrada</title>
<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $ref_periodo == '' )
{
  list ( $ref_periodo ) = QueryExecute($sql_periodos_academico);
  $ref_periodo = trim(substr($ref_periodo, 0, strpos($ref_periodo, "/")));
}
$op_result1  = SQLArray($sql_periodos_academico);

$op_result2 = SQLArray("select id || '  ' || substr(descricao,1,30),id from motivos order by id");
</script>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_periodo);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_motivo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/lista_motivo_ingresso.php3" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>Listagem de Alunos por Motivo de Ingresso</b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op1')" value="<?echo($ref_periodo);?>">
              <script language="PHP">
        		ComboArray("op1",$op_result1,$ref_periodo,"ChangeOp1()");
	          </script>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Motivo Ingresso</font></td>
      <td>
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input name="ref_motivo" type=text onChange="ChangeCode('ref_motivo','op2')" value="<?echo($ref_motivo);?>" size="8" maxlength="8">
              <script language="PHP">
                 ComboArray("op2",$op_result2,$ref_motivo,"ChangeOp2()");
              </script>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr><td colspan="2"><hr></td></tr>
    <tr><td colspan="2">Obs.: Esta listagem foi preparada para emitir os portadores de diploma de um período que efetuaram sua matrícula.</td></tr>
    <tr><td colspan="2"><hr></td></tr>
  </table>
  <div align="center"> 
    <p>
      <input type="submit" name="Submit"  value="  Gerar  ">
      <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
    </p>
  </div>
</form>
</body>
</html>
