<? require("../../../lib/common.php"); ?>
<html>
<head>
<title>Lista de Disciplinas Oferecidas</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="PHP">
function Lista_cancelamentos($ref_periodo)
{
   global $href, $curso_id, $periodo_id;

   $conn = new Connection;

   $conn->open();

   $sql = " select distinct A.ref_pessoa, " .
          "                 B.ref_curso, " .
          "                 B.ref_campus, ". 
          "                 curso_desc(B.ref_curso), ".
          "                 get_campus(B.ref_campus), dt_matricula " .
          " from matricula A, contratos B" .
          " where A.ref_pessoa = B.ref_pessoa and B.ref_last_periodo = '2001A' and" .
          "       A.ref_periodo = '2001A' and " .
//          "       A.dt_matricula <= '12/31/2000' and " .
          "       A.dt_cancelamento  <= '12/31/2000' and " .                      // is not null and " .
          "       A.ref_pessoa not in " .
          "       (select distinct ref_pessoa from matricula where ref_periodo = '2001A' " .
          "                        and dt_cancelamento is null) order by ref_curso, ref_campus;";

   SaguAssert(0, $sql);
   
   $query = $conn->CreateQuery($sql);

   echo("<center><table width=\"95%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

   $i=1;
   $j=0;
   $aux_curso = 10;
   $aux_campus = 1;

   // cores fundo
   $bg0 = "#000000";
   $bg1 = "#EEEEFF";
   $bg2 = "#FFFFEE";
 
   // cores fonte
   $fg0 = "#FFFFFF";
   $fg1 = "#000099";
   $fg2 = "#000099";

   $soma = 0;
   $soma_total = 0;

   $ii = 0;

   while( $query->MoveNext() )
   {
     list ($ref_pessoa,
           $ref_curso,
           $ref_campus,
           $curso,
           $campus) = $query->GetRowValues();

     $ii++;
     if ($ii == 1)
     {
         echo ("<td bgcolor=\"#000099\" colspan=\"4\"><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><center><b>Listagem de Cancelamentos</b></center></font></td>");
         echo ("<tr bgcolor=\"#000000\">\n");
         echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Cód</b></font></td>");
         echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Campus</b></font></td>");
         echo ("<td width=\"70%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Curso</b></font></td>");
         echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Total</b></font></td>");
         echo ("  </tr>"); 
         $curso_ = $curso;
         $campus_ = $campus;
         $ref_curso_ = $ref_curso;
     }
 
     if( ($ref_curso != $aux_curso) || ($ref_campus != $aux_campus) )
     {
         if ( $i % 2 )
         {
           echo ("<tr bgcolor=\"$bg1\">\n");
           echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$ref_curso_</td>");
           echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$campus_</td>");
           echo ("<td width=\"70%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$curso_</td>");
           echo ("<td width=\"10%\" align = \"right\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$soma</td>");
           echo ("  </tr>");
         }
         else
         {
           echo ("<tr bgcolor=\"$bg2\">\n");
           echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$ref_curso_</td>");
           echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$campus_</td>");
           echo ("<td width=\"70%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$curso_</td>");
           echo ("<td width=\"10%\" align = \"right\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$soma</td>");
           echo ("  </tr>\n");
         }
         $curso_ = $curso;
         $campus_ = $campus;
         $ref_curso_ = $ref_curso;
         $aux_curso  = $ref_curso;
         $aux_campus = $ref_campus;
         $soma_total += $soma;
         $soma = 0;
         $i++;
     }
     $soma++;
   }

   if ( $i % 2 )
   {
      echo ("<tr bgcolor=\"$bg1\">\n");
      echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$ref_curso</td>");
      echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$campus</td>");
      echo ("<td width=\"70%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$curso</td>");
      echo ("<td width=\"10%\" align = \"right\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$soma</td>");
      echo ("  </tr>");
   }
   else
   {
      echo ("<tr bgcolor=\"$bg2\">\n");
      echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$re_curso</td>");
      echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$campus</td>");
      echo ("<td width=\"70%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$curso</td>");
      echo ("<td width=\"10%\" align = \"right\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$soma</td>");
      echo ("  </tr>\n");
   }

   $soma_total += $soma;

   echo ("<td bgcolor=\"#000099\" colspan=\"4\" align=\"right\"><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>TOTAL: $soma_total</b></font></td>");

   echo("</table></center>");

   @$query->Close();

   @$conn->Close();

}
</script>
</head>
<body bgcolor="#FFFFFF">
<form method="post" action="" name="myform">
  <script language="PHP">
Lista_cancelamentos('2001A');
</script>
</form>
</body>
</html>
