<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Lista de Alunos por Status da Matrícula</title>

<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $periodo_id == '' )
{
  list ( $periodo_id ) = QueryExecute($sql_periodos_academico);
  $periodo_id = trim(substr($periodo_id, 0, strpos($periodo_id, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

/*
$sql = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$periodo_id' " .
       " order by A.id;" ;
*/     
$sql = " select distinct A.id||' / '||A.abreviatura as d, " .
      "        A.id " .
      " from cursos A, matricula B " .
      " where A.id = B.ref_curso and " .
      "       B.ref_periodo = '$periodo_id' " .
      " order by A.id;" ;


$op_result1 = SQLArray($sql);

$sql = " select nome_campus, id from campus" .
       " order by id;" ;

$op_result2 = SQLArray($sql);

</script>

<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);

  document.myform.action = 'lista_status.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.curso_id);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.campus_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>

</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/lista_status.php3" name="myform">
<TABLE width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Lista de Alunos por Status da Matrícula</b></font></td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="periodo_id" onChange="ChangeCode('periodo_id','op')" size="8" value="<?echo($periodo_id)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Curso:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="curso_id" onChange="ChangeCode('curso_id','op1')" size="8">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
		ComboArray("op1",$op_result1,$curso_id,"ChangeOp1()");
	      </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <TD width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Campus:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="campus_id" onChange="ChangeCode('campus_id','op2')" size="8">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
		ComboArray("op2",$op_result2,$campus_id,"ChangeOp2()");
	      </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="161"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;&nbsp;Status</font></td>
      <td colspan="3" width="410">
          <select name="idx_status">
            <option value="" selected>----- Selecione -----</option>
            <option value="1">Reprovado</option>
            <option value="2">Desistente</option>
            <option value="3">Aprovado</option>
            <option value="4">Dispensado</option>
          </select>
      </td>
    </tr>
    <TR>
     <td colspan="2">
         <hr size="1">
     </td>
    </TR>
    <tr>
     <td colspan="2" align="center">
       <input type="submit" name="Submit"  value=" Gerar ">
       <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
     </td>
    </tr>
</TABLE>
</form>
</body>
</html>

