<html>
<head>
<title>Efetuar Matrícula</title>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<table width="500" border="0" cellspacing="4" cellpadding="1" align="center">
  <tr>
    <TD bgcolor="#FFCC33" height="24" valign="middle">
      <div align="center"><FONT color="#0000cc"><B>Matrícula Seriada</B></FONT></div>
    </td>
  </tr>
    <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="matricula_aluno_internet.phtml"><font color="#FFFFFF">Efetuar Matrícula</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  <tr>
    <TD width="100%" align="center" bgcolor="#0099FF" valign="middle"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><A href="#" onClick="javascript:history.go(-1)"><b><font color="#FFFFFF">Voltar</font></b></a></font></td>
  </tr>
</table>
<br>
<table width="500" border="0" cellspacing="4" cellpadding="1" align="center">
  <tr>
    <TD bgcolor="#FFCC33" height="24" valign="middle">
      <div align="center"><FONT color="#0000cc"><B>Matrícula por Disciplinas</B></FONT></div>
    </td>
  </tr>
  <tr>
    <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="matricula_aluno.phtml"><font color="#FFFFFF">Efetuar Matrícula</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  <tr>
    <td width="51%" bgcolor="#0099FF">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="desbloqueia_disciplina.phtml"><font color="#FFFFFF">Desbloqueia Disciplina</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
    </td>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><b><font size="2"><a href="acresce_disciplina.phtml"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF">Acr&eacute;scimo Disciplina </font></a></font></b></div>
    </td>
  </tr>
  <tr>
    <td width="49%" bgcolor="#0099FF">
      <div align="center"><b><font size="2"><a href="cancela_disciplina.phtml"><font face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF">Trancamento Disciplina </font></a></font></b></div>
    </td>
  </tr>
  <tr>
    <TD width="100%" align="center" bgcolor="#0099FF" valign="middle"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><A href="#" onClick="javascript:history.go(-1)"><b><font color="#FFFFFF">Voltar</font></b></a></font></td>
  </tr>

<!--  <tr>
    <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="matricula_aluno_ajuste.phtml"><font color="#FFFFFF">Ajuste de Matrícula</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  <tr>
    <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="matricula_aluno_tecnico.phtml"><font color="#FFFFFF">Matrícula Técnico</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  <tr>
    <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="autorizacao_matricula.phtml"><font color="#FFFFFF">Autorização Matrícula</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  -->
  </table>
</body>
</html>
