<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<?
  $periodo_id = $properties->Get("periodo_id","0");
  $aluno_id   = $properties->Get("aluno_id");
?>
<html>
<head>
<title>Untitled Document</title>
<script language="PHP">
function SQL_Combo($nome,$sql,$default,$onchange)
{
  $conn = new Connection;
  
  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $onchange != "" )
    echo("<select name=\"$nome\" onchange=\"$onchange\">");
  else
    echo("<select name=\"$nome\">");
    
  for ( $i=1; $query->MoveNext(); $i++ )
  {
    list ( $text, $value ) = $query->GetRowValues();
      
    if ( $value == $default )
      echo("  <option value=\"$value\" selected>$text</option>\n");
    else
      echo("  <option value=\"$value\">$text</option>\n");
  }

  echo("</select>");

  $query->Close();

  $conn->Close();
}

</script>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function _busca()
{
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.aluno_id.value = id;
  document.myform.aluno_nome.value = nome;
}

</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="matricula_curso.phtml" name="myform">
<table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
  <tr bgcolor="#000099"> 
    <td colspan="2" height="35"> 
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Matr&iacute;culas</font></b></font></div>
    </td>
  </tr>
  <tr bgcolor="#CCCCFF"> 
    <td colspan="2" height="32" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099"><b>&nbsp;&nbsp;Identifica&ccedil;&atilde;o do Aluno </b></font></td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
    <td> 
      <input type="text" name="periodo_id" size="10" onChange="ChangeCode('periodo_id','op')" value="<?echo($periodo_id);?>">
      <font color="#000000">
  <script language="PHP">
  	SQL_Combo("op",$sql_periodos_academico,$periodo_id,"ChangeOp()");
  </script>
      </font> </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Aluno:</font></td>
    <td> 
      <input type="text" name="aluno_id" size="10" value="<?echo($aluno_id);?>">
      <input type="text" name="aluno_nome" size="40" value="<?echo($aluno_nome);?>">
      <input type="button" value="..." onclick="_busca()">
    </td>
  </tr>
  <tr> 
    <td align="center" colspan="2"><hr></td>
  </tr>
  <tr> 
    <td align="center" colspan="2"> 
      <input type="submit" name="Submit"  value=" Prosseguir ">
      <input type="button" name="Button2" value="    Sair    " onClick="javascript:history.go(-1)">
    </td>
  </tr>
</table>
</form>
</body>
</html>
