<?php 
 require("../../../lib/common.php");
 require("../../../lib/config.php");
 require("../lib/ProcessaMaterial.php3"); 
 require("../lib/StatusDisciplina.php3"); 
?>

<html>
<head>
<title>Matrícula</title>

<script language="JavaScript">
var lu_ofer  = null;
var lu_code  = null;
var lu_desc  = null;
var lu_prof  = null;
var lu_dia   = null;
var lu_turno = null;
var lu_check = null;
var lu_ele   = null;

function setResult(ofer,curso_id,id,nome,prof,dia,turno)
{
  lu_check.checked = true;
  lu_ofer.value  = ofer;
  lu_code.value  = id;
  lu_curso.value = curso_id;
  lu_desc.value  = nome; 
  lu_prof.value  = prof;
  lu_dia.value   = dia;
  lu_turno.value = turno;
}

/* Preenche os campos das disciplinas */
/* Com Mouse			      */
function lookup(obj)
{
  var form = obj.form;

  for ( i=0; i<form.length; i++ )
  {
    if ( form.elements[i] == obj )
    {
      lu_check  = form.elements[i-9];
      lu_ele    = form.elements[i-8];
      lu_code   = form.elements[i-7];
      lu_curso  = form.elements[i-6];
      lu_ofer   = form.elements[i-5];
      lu_desc   = form.elements[i-4];
      lu_prof   = form.elements[i-3];
      lu_dia    = form.elements[i-2];
      lu_turno  = form.elements[i-1];

      return true;
    }
  }

  return false;
}

/* Preenche os campos das disciplinas eletivas (bolinha amarela) */
/* Acesso com Mouse					         */
function lookup2(obj)
{
    if ( !lookup(obj) )
        return;

    var url = "/lib/lista_disciplinas_nome_internet.php3" + 
              "?periodo_id=" + escape('<?=$periodo_id?>') +
              "&curso_id=" + escape('<?=$curso_id?>') +
              "&ref_campus=" + escape('<?=$ref_campus?>') +
              "&aluno_id=" + escape('<?=$aluno_id?>');

    if ( lu_code.value != '' )
        url += '&ref_disciplina=' + escape(lu_code.value);

    if ( lu_desc.value != '' )
        url += '&desc_disciplina=' + escape(lu_desc.value);
  
    if ( lu_ele.value != '' )
        url += '&ref_disciplina_ele=' + escape(lu_ele.value);

    var wnd = window.open(url,'busca','toolbar=no,width=780,height=350,scrollbars=yes');

}

function pre_requisitos(url)
{
  window.open(url,'requisitos','resizable=yes, toolbar=no,width=540,height=236,scrollbars=yes');
}

</script>
<?php

CheckFormParameters(array('periodo_id','aluno_id'));

?>

</head>

<body>
<form name="myform" method="post" action="matricula_salvar_internet.php3">
<br>
<div align=center>
<TABLE width="760" border="0" cellspacing="0" cellpadding="0" height="40">

    <tr bgcolor="#000099">
      <TD height="35">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">
        Disciplinas da Matr&iacute;cula</font></b></font></div>
      </td>
    </tr>

</table>
</div>
<?php
    // Processa material de matrícula de acordo com a situação atual
    ProcessaMaterial($periodo_id, $curso_id, $ref_campus, $aluno_id);

    $conn = new Connection;
    $conn->Open();

    //seleciona as disciplinas em dependencia
    $sql = "SELECT DISTINCT C.ref_disciplina, ".
           "       descricao_disciplina(C.ref_disciplina), " .
           "       C.semestre_curso " .
           "  FROM cursos_disciplinas C " .
           " LEFT JOIN contratos B " .
           "    ON (C.semestre_curso <= B.semestre ) " .
           " LEFT JOIN matricula A " .
           "    ON (A.ref_contrato = B.id AND " .
           "        A.ref_disciplina = C.ref_disciplina ) " .
           " WHERE B.id           = '$id_contrato' " .
           "   AND ( " .
           "             A.fl_liberado = 1 " . //desistente
           "          OR A.fl_liberado = 2 " . //reprovado
           "          OR ( A.nota_final < (SELECT media_final FROM periodos WHERE periodos.id = A.ref_periodo) " .
           "          AND (fl_liberado = '2' OR fl_liberado = '1' OR A.fl_liberado = '') )  " .
           "          OR A.id is null " .
           "       ) " .
           "   AND C.ref_curso = '$curso_id' " .
           "   AND C.ref_campus = '$ref_campus' " .
           "ORDER BY C.semestre_curso asc; ";

//echo $sql;

    $query = $conn->CreateQuery($sql);

        $x=0;
        while($query->MoveNext())
        {
            list($ref_disciplina, 
                 $disciplina, 
                 $semestre_curso) = $query->GetRowValues();
            $dependencia[$x] = "$ref_disciplina;$disciplina;$semestre_curso";

            $sql = "select fl_liberado from matricula where ref_disciplina = '$ref_disciplina' " .
                   "and ref_contrato = '$id_contrato' and (fl_liberado = 3 or fl_liberado = 4)";
            $query2 = $conn->CreateQuery($sql);
            if( $query2->MoveNext() )
            {
                unset($dependencia[$x]);
            }
            else
            {
                $x++;
            }
            if ( $x > 2 && !$chave )
            {
                $chave = 1;
                $semestre = $semestre_curso;
            }
        }

        //Define o semestre atual
        //echo $semestre;
        if( count($dependencia)>6 )
        {
            $semestre_atual = $semestre;
            $proximo_semestre = $semestre;
        }
        else
        {
            $semestre_atual = ($semestre+1);
            $proximo_semestre = ($semestre+1);
        }

        $conn->Close();
?>
<table width="760" border="0" cellspacing="2" cellpadding="0" align="center" background="/images/fundo_matricula.png">
  <tr>
    <td><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;<b>Periodo:</b></font></td>
    <td colspan="2"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($periodo_id);?></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;<b>Per&iacute;odo Atual: </b>  <?echo($semestre_atual);?></font></td>
    <td colspan="2"><font face="Arial, Helvetica, sans-serif" size="2"><b>Próximo Per&iacute;odo:</b>  <?echo($proximo_semestre+1);?></font></td>
  </tr> 
  <tr> 
    <td><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;<b>Aluno:</b></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2"><?echo($aluno_id);?></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2"> <?echo($aluno_nome);?></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;<b>Parcelas:</b></font>
        <font face="Arial, Helvetica, sans-serif" size="2">
          <input type="text" name="num_parcelas" size=1 value="6">vezes
        </font>
    </td>
    <td><font face="Arial, Helvetica, sans-serif" size="2"><b>Turma:
        </b><?=$turma?><i>(<?=$ref_periodo_turma?>)</i></font>
    </td>
  </tr>
  <tr> 
    <td><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;<b>Curso:</b></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2"><?echo($curso_id);?></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2"><?echo($curso_nome);?></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;<b>Contrato: </b><?echo($id_contrato);?></font></td>
    <td><font face="Arial, Helvetica, sans-serif" size="2">
    <?
    	echo("<b>Campus:</b> ");
    	echo($ref_campus)
    ?>
    </font></td>
  </tr>
  <tr>
    <td colspan="5" align="center">
      <table>
        <tr>
          <td align=center><img src="images/attention.gif" width="50" height="50"></td>
          <td align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="red"><p><b>
DEPENDÊNCIA(S):</font><font face="Arial, Helvetica, sans-serif" size="2" color="blue"> 
<?
    for($x=0;$x<count($dependencia);$x++)
    {
        list($cod,$dis,$sem) = explode(";", $dependencia[$x]);
        if ( $sem < $semestre_atual )
        {
            echo("<br>$x $cod($dis) - " . $sem. " sem.");
            $dep[] = $cod;
        }
    }
?>
</b></p></font>
          </td>
        </tr>
      </table>
    </td>    
  </tr>
</table>
<table width="760" border="0" cellspacing="0" cellpadding="0" align="center" background="/images/fundo_matricula.png">
  <tr align="center" bgcolor="#000099"> 
    <td height="30" colspan="11"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b>DISCIPLINAS OFERECIDAS</b></font></td>
  </tr>
  <tr bgcolor="#CCCCCC" valign=middle> 
  <td width="4%" align="left">&nbsp;</td>
  <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">C&oacute;d. Ofer.</font></td>
  <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">C&oacute;digo</font></td>
  <td width="8%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Status</font></td>
  <td width="8%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Dia</font></td>
  <td width="15%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Turno</font></td>
  <td width="36%"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Disciplina<br>Professor</font></td>
  <td width="6%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Horário</font></td>
  <td width="9%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Período</font></td>
  <td width="6%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Matriculas<br>Vagas</font></td>
  <td width="10%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="#000000">Campus<br>Turma</font></td>
  </tr>
  
  <?

  $conn = new Connection;
  $conn->Open();
  $conn->Begin();

  //disciplinas possiveis
  $sql = " select ref_disciplina, ".
         "        descricao_disciplina(ref_disciplina), ".
         "        ref_disciplina_subst,".
         "        descricao_disciplina(ref_disciplina_subst), ".
         "        get_semestre_curso (ref_curso, ref_campus, ref_disciplina), ".
         "        status ".
         " from disciplinas_todos_alunos ".
         " where ref_campus = '$ref_campus' ".
         "   and ref_curso = '$curso_id' ".
         "   and ref_pessoa = '$aluno_id' ".
         " order by get_semestre_curso (ref_curso, ref_campus, ref_disciplina)";

  $query = $conn->CreateQuery($sql);

  $i = 0;
  
  // Inicio primeiro while
  $aux_semestre_curso = 0;
  while ($query->MoveNext())
  {
      list ($ref_disciplina, 
     	    $nome_disciplina, 
    	    $ref_disciplina_subst, 
    	    $nome_disciplina_subst, 
            $semestre_curso,
            $status) = $query->GetRowValues();

      $sql2 = " select id, " .
      	      "	      ref_disciplina, " .
              "       descricao_disciplina(ref_disciplina), " .
              "       professor_disciplina_ofer_todos(id), " . 
              "       dia_disciplina_ofer_todos(id), " .
    	      "       get_dia_semana_abrv(dia_disciplina_ofer_todos(id)), " .
              "       turno_disciplina_ofer_todos(id), " .
              "	      get_turno(turno_disciplina_ofer_todos(id)), " .
              "       get_horarios_todos(id), " .
              "       get_periodos_todos(id), " .
              "       ref_curso, " .
              "       get_color_campus(ref_campus), " .
              "       get_campus(ref_campus), " .
              "       get_status_disciplina('$aluno_id','$curso_id','$ref_disciplina')," .
              "       get_num_matriculados(id), " .
              "       num_alunos, " .
              "       check_matricula_pessoa(id, '$aluno_id'), " .
              "       turma, " .
              "       ref_periodo_turma " .
              " from disciplinas_ofer ";
    	      
              if (!$ref_disciplina_subst)
              {
                  $sql2 .= " where ref_disciplina = '$ref_disciplina' and ";
              }
              else
              {
                  $sql2 .= " where ref_disciplina = '$ref_disciplina_subst' and ";
              }

      $sql2.= "       ref_periodo = '$periodo_id' and " .
              "       ref_curso = '$curso_id' and ref_campus = '$ref_campus' and ".
              "       is_cancelada <> '1'" .
              " order by dia_disciplina_ofer_todos(id), turno_disciplina_ofer_todos(id);";

      $query2 = $conn->CreateQuery($sql2);

      // Início segundo while
      while ($query2->MoveNext())
      {
        list ( $ofer, 
    	       $cod_disciplina_oferecida,
               $nome_disciplina_oferecida,
    	       $prof, 
               $idia, 
               $dia,
               $iturno, 
    	       $turno,
               $horario,
               $periodos,
    	       $curso, 
               $color2,
               $campus,
               $status_disc,
    	       $num_matriculados,
    	       $num_alunos,
               $check_matricula_pessoa,
               $turma_d,
               $ref_periodo_turma_d) = $query2->GetRowValues();

        $num_alunos = $num_alunos ? $num_alunos : '0';

        //impressao da data da disciplina
        $array_periodos = explode('/',$periodos);
        $horario = str_replace('às','<br>às<br>',str_replace(' ','',str_replace(':00 ','',$horario.' ')));
        $periodos = '';
        for ($x=0; $x<count($array_periodos); $x++)
        {
            list ($periodo_inicial,
                  $periodo_final) = split(' até ', $array_periodos[$x]);

            $periodos .= substr($periodo_inicial, 8, 2) . "/" . substr($periodo_inicial, 5, 2) . "<br>à<br>" . substr($periodo_final, 8, 2) . "/" . substr($periodo_final, 5, 2) . "/";
             
        }
        $periodos = substr($periodos, 0, -1);

        if ($status_disc == '2')
        { 
            $fleg_status = 't'; 
        }
        else
        { 
            $fleg_status = 'f'; 
        }

        $name_check = "check1_" . $i;
        $ofer1_code1 = $ofer . "_" . $ref_disciplina . "_" . $fleg_status . "_" . $idia . "_" . $iturno . "_" . $ref_disciplina_subst . "_" . $semestre_curso;

		$href1 = '<input type="checkbox" name="ofer1_code1[]" value="'.$ofer1_code1.'">';

        if ( ($num_matriculados>=$num_alunos) || ($status_disc==1||$status_disc==0) )
        {
            // echo  $semestre_atual;
            if ( $semestre_curso == $semestre_atual )
            {
                if ( $turma_d == $turma && $ref_periodo_turma_d == $ref_periodo_turma ) 
				{
                    $href2 = "<input type=\"checkbox\" name=\"$name_check\" checked>";
                }
                else
                {
                    $href2 = "<input type=\"checkbox\" name=\"$name_check\">";
				}
            }
            elseif ( $semestre_curso < $semestre_atual )
            {
                if( in_array($ref_disciplina,$dep) )
                {
                    $href2 = "<input type=\"checkbox\" name=\"$name_check\" checked>";
				}
                else
                {
                    $href2 = "<input type=\"hidden\" name=\"$name_check\">";
                }
            }
            else
            {
                $href2 = "<input type=\"hidden\" name=\"$name_check\">";
			}
        }
        else
        {
            $href2 = "<input type=\"hidden\" name=\"$name_check\">";
        }

        $href3 = "<a href=\"javascript:pre_requisitos('/generico/mostra_pre_requisitos_internet.phtml?ref_disciplina=$ref_disciplina&curso_id=$curso_id')\"><img src=\"../images/info.gif\" border=0 title='Ver Pré Requisitos'></a>";

        if ($status_disc == 2) $color = 'red';
        elseif ($status_disc == 1) $color = 'green';
        elseif ($status_disc == '') $color = '#000000';
        else $color = 'orange';

        if ( $i % 2 == 0) $bg = "#EEEEFF";
        else $bg = "#FFFFEE";
    
	if($aux_semestre_curso<>$semestre_curso) {
        ?>
		<tr align="center" bgcolor="#000099"> 
			<td height="30" colspan="11"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><?=$semestre_curso?>o. PER&Iacute;ODO</b></font></td>
		</tr>
	<?
	}
	$aux_semestre_curso = $semestre_curso;
	?>

        <tr bgcolor="<?echo($bg);?>" valign="middle">
          <?php //echo $href1; ?>
			<td width="5%" align="left"><?php echo $href1;?></td>
			<td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><b><?echo($ofer);?></b>&nbsp;&nbsp;</font>			</td>
			<td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($ref_disciplina);?></font></td>
          <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="<? echo($color);?>"><b><?echo($status_disciplina[$status_disc]);?></b></font></td>
          <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($dia);?></font></td>
          <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($turno);?></font></td>
          <td width="45%"> <font face="Arial, Helvetica, sans-serif" size="2"><b><? echo($nome_disciplina);?><?if ($ref_disciplina_subst) echo("<br>($ref_disciplina_subst - $nome_disciplina_subst)")?></b><br><? echo($prof);?></font></td>
          <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><? echo("$horario");?></font></td>
          <td width="10%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($periodos);?></font></td>
          <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2"><?echo("$num_matriculados/$num_alunos");?></font></td>
          <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2" color="<? echo($color2) ?>"><b><?echo($campus);?></b><br><?=$turma_d?><i>(<?=$ref_periodo_turma_d?>)</i></font></td>
<? if(($status_disc!=0) and ($status_disc!=2) and ($semestre_curso!=$proximo_semestre))
   {
?>
   <td width="5%" align="center"><font face="Arial, Helvetica, sans-serif" size="2">  
</font></td>
<? } ?>

        </tr>
      <?
      $i++;
      }
      $query2->Close();
      // Fim segundo while
  }
  // Fim primeiro while
  $query->Close();
?>

  <input type="hidden" name="ref_periodo" value="<?echo($periodo_id);?>">
  <input type="hidden" name="ref_pessoa" value="<?echo($aluno_id);?>">
  <input type="hidden" name="email" value="<?echo($email)?>">
  <input type="hidden" name="nome_pessoa" value="<?echo($aluno_nome);?>">
  <input type="hidden" name="ref_curso" value="<?echo($curso_id);?>">
  <input type="hidden" name="nome_curso" value="<?echo($curso_nome);?>">
  <input type="hidden" name="ref_contrato" value="<?echo($id_contrato);?>">
  <input type="hidden" name="ref_campus" value="<?echo($ref_campus);?>">
  <input type="hidden" name="num_creditos_min" value="<?echo($num_creditos_min)?>">
  <input type="hidden" name="fl_limite_turno" value="<?echo($fl_limite_turno)?>">
  <input type="hidden" name="semestre" value="<?echo($proximo_semestre)?>">
  <tr> 
    <td align="center" colspan="11"> 
        <hr size="1" width="100%">
        <input type="button" value=" << Voltar " name="Button1" onClick="location='matricula_renovacao_internet.phtml?periodo_id=<?=$periodo_id?>&aluno_id=<?=$aluno_id?>&email=<?=$email?>&aluno_nome=<?=$aluno_nome?>&curso_id=<?=$curso_id?>&curso_nome=<?=$curso_nome?>&id_contrato=<?=$id_contrato?>&ref_campus=<?=$ref_campus?>'">
        <input type="submit" value=" Seguir >> " name="seguir">
    </td>
  </tr>
</table>
<table width="760" height="77" border="0" cellspacing="2" cellpadding="0" align="center" background="/images/fundo_matricula.png">
  <tr> 
    <td align="center" valign="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b>Matrículas <?echo($periodo_id);?></b></font>
    </td>
  </tr>
</table>
<input type="hidden" name="semestre_atual" value="<?=$semestre_atual?>">
<?
$dep1 = implode(',',$dep);
?>
<input type="hidden" name="dependencias" value="<?=$dep1?>">
</form>
</body>
</html>
