<? require("../../../lib/common.php"); ?>
<? require("../../../lib/properties.php"); ?>
<html>
<head>
<title>Cadastro de Notas</title>
<script language="PHP">
CheckFormParameters(array('curso_id','periodo_id'));

$properties->Set("periodo_id",$periodo_id);
$properties->Save();

</script>
<script language="JavaScript">
function Select_Disc(id_disc)
{
  var url = "notas_disc_alunos.phtml" +
            "?disc=" + escape(id_disc) + 
            "&curso_id=" + escape('<?echo($curso_id)?>') +
            "&periodo_id=" + escape('<?echo($periodo_id)?>');

  location = url; 
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
  <script language="PHP">
   $conn = new Connection;

   $conn->open();

   $sql = "  select A.id, " .  // Oferecida
          "         B.id, " .  // Complementar
          "         A.ref_curso, " .
          "         A.ref_periodo, " .
          "         A.ref_disciplina," .
          "         descricao_disciplina(A.ref_disciplina)," .
          "         B.dia_semana, " .
          "         curso_desc(A.ref_curso), ".
          "         A.is_cancelada " .
          "  from disciplinas_ofer A, disciplinas_ofer_compl B " .
          "  where A.id = B.ref_disciplina_ofer and " .
    	  "	       A.ref_curso='$curso_id' and " .
          "        A.ref_periodo='$periodo_id' and " . 
          "        A.is_cancelada='0' " .
          "  order by B.dia_semana, A.ref_disciplina;";

   $query = $conn->CreateQuery($sql);
   
</script>
<table width="90%" align="center" cellspacing="0" cellpadding="0" border="0">
  <tr bgcolor="#000099"> 
    <td colspan="5" height="28"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>Curso: 
      <?echo($curso_id)?> / Período: <?echo($periodo_id)?></b></font></td>
  <tr bgcolor="#000000"> 
    <td width="20"><Font face="Verdana" size="2" color="#ffffff"><b>&nbsp;</b></font></td>
    <td width="20"><Font face="Verdana" size="2" color="#ffffff"><b>Código</b></font></td>
    <td width="292"><Font face="Verdana" size="2" color="#ffffff"><b>Disciplina 
      / Professor</b></font></td>
    <td width="50"><Font face="Verdana" size="2" color="#ffffff"><b>Dia</b></font></td>
    <td width="50"><Font face="Verdana" size="2" color="#ffffff"><b>Ofer</b></font></td>
  </tr>
  <script language="PHP">
  for ( $i=0; $query->MoveNext(); $i++ )
  {
    list ( $id_ofer,
           $id_compl,
           $ref_curso,
           $ref_periodo,
           $ref_disciplina,
           $descricao_disciplina,
           $dia_semana,
           $curso_desc ) = $query->GetRowValues();

    $href = "<a href=\"javascript:Select_Disc('$id_ofer')\"><img src=\"../images/select.gif\" title='Selecionar' border=0></a>";

    $sql = " select ref_professor, " .
           "        pessoa_nome(ref_professor) " .
           " from disciplinas_ofer_prof " .
           " where ref_disciplina_ofer = '$id_ofer' and " .
           "       ref_disciplina_compl = '$id_compl'";

    $query2 = $conn->CreateQuery($sql);

    if ( $i % 2 == 0 )
    {
      $bg = "#EEEEFF";
    }
    else
    {
      $bg = "#FFFFEE";
    }

  </script>
  <tr bgcolor="<?echo($bg)?>" valign="top"> 
    <td><font color="#000099"><b><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><?echo($href)?></font></b></font></td>
    <td align="center"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><?echo($ref_disciplina)?></font></td>
    <td><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><?echo($descricao_disciplina)?></font></td>
    <td><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><?echo($dia_semana)?></font></td>
    <td><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><?echo($id_ofer)?></font></td>
  </tr>

<script language="PHP">
  
while( $query2->MoveNext() ) // while
{	
  list ($ref_professor,              
        $professor_nome) = $query2->GetRowValues();
	  
</script>
    <tr bgcolor="<?echo($bg)?>" valign="top"> 
        <td colspan="2">&nbsp;</td>
        <td><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><i>
        <?echo($professor_nome)?>&nbsp;</i></font></td>
        <td colspan="2">&nbsp;</td>
    </tr>
<script language="PHP">
} // end while

$query2->Close();

} // end for 

</script>
<tr><td colspan="5" align="center"><hr></td></tr>
</table>
  <script language="PHP">
   $query->Close();

   $conn->Close();
</script>
<form name="form1" >
  <div align="center">
    <input type="button" name="Button2" value="   Sair   " onClick="location='notas.phtml'">
  </div>
</form>
</body>
</html>
