<?php 
   
   require("../../../lib/common.php"); 
   require("../../../lib/config.php"); 

  CheckFormParameters(array('curso_id','periodo_id'));
?>
<html>
<head>
<title>Cadastro de Notas</title>
<script language="JavaScript">
function _init()
{
  document.forms[0].elements[0].focus()
}
</script>
<script language="PHP">
function ListaAlunos($disc)
{
   global $href, $curso_id, $periodo_id;

   $conn = new Connection;

   $conn->open();

   $sql = " SELECT DISTINCT ref_disciplina_ofer, " .
          "                 ref_pessoa, " .
          "                 pessoa_nome(ref_pessoa), " .
          "                 ref_professor_disciplina_ofer('$disc'), " .
          "                 professor_disciplina_ofer('$disc'), " .
          "                 ref_curso, " .
          "                 curso_desc(ref_curso), " .
          "                 ref_campus, " .
          "                 get_campus(ref_campus), " .
          "                 ref_disciplina, " .
          "                 descricao_disciplina(ref_disciplina), " .
          "                 ref_disciplina_subst, " .
          "                 descricao_disciplina(ref_disciplina_subst), " .
          "                 nota_final, " .
          "                 num_faltas, " .
      	  "		            fl_liberado, " .
    	  "     		    id, " .
          "                 get_creditos(get_disciplina_de_disciplina_of('$disc')), " .
          "                 get_carga_horaria(get_disciplina_de_disciplina_of('$disc')) " .
          " FROM matricula " .
          " WHERE ref_disciplina_ofer = '$disc' and " .
          "       dt_cancelamento is null " .
          " ORDER BY pessoa_nome(ref_pessoa);" ;
 
   $query = $conn->CreateQuery($sql);

   echo("<center><table width=\"95%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

   $i=1;
   $indice=0;
   $j=0;

   // cores fundo
   $bg0 = "#000000";
   $bg1 = "#EEEEFF";
   $bg2 = "#FFFFEE";
 
   // cores fonte
   $fg0 = "#FFFFFF";
   $fg1 = "#000099";
   $fg2 = "#000099";

   while( $query->MoveNext() )
   {
     list ( $ref_disciplina_ofer,
            $ref_pessoa, 
            $pessoa_nome,
            $ref_professor,
            $nome_professor,
            $ref_curso,
            $curso_desc,
            $ref_campus,
            $campus,  
            $ref_disciplina,
            $descricao_disciplina,
            $ref_disciplina_subst,
            $descricao_disciplina_subst,
            $nota_final,
            $num_faltas,
    	    $fl_liberado,
            $id_matricula,
            $num_creditos,
            $carga_horaria) = $query->GetRowValues();

        if( !$nota_final ) 
            { $nota_final=''; } 

        if( !$num_faltas ) 
            { $num_faltas=''; } 

        if ( $ref_disciplina_subst )
        {
            $code_disc = $ref_disciplina_subst;
            $desc_disc = $descricao_disciplina_subst;
        }
        else 
        {
            $code_disc = $ref_disciplina;
            $desc_disc = $descricao_disciplina;
        }
    
        // Teve que ser hard code porque infelizmente os cursos técnicos tem esta excessão
        if ($carga_horaria == 40)
        {
            $frequencia_maxima = $carga_horaria;
            $frequencia_minima = (($frequencia_maxima * 75) / 100);
        }
        else
        {
            $frequencia_maxima = ($carga_horaria + ($carga_horaria / 15));
            $frequencia_minima = (($frequencia_maxima * 75) / 100);
        }
        
        if ($i == 1)
        {
            echo ("<tr><td bgcolor=\"#000099\" colspan=\"7\"><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><center><b>Digitação de Notas</b></center></font></td>");
            echo ("<tr>");
            echo ("<td bgcolor=\"#000099\" colspan=\"3\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Disciplina: " . $ref_disciplina . " - " . $descricao_disciplina . "</b></font></td>");
            echo ("<td bgcolor=\"#000099\" colspan=\"4\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Campus: " . $ref_campus . " - " . $campus . "</b></font></td>");
            echo ("</tr>\n"); 
            echo ("<tr>");
            echo ("<td bgcolor=\"#000099\" colspan=\"3\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Professor(a): " . $ref_professor . " - " . $nome_professor . "</b></font></td>");
            echo ("<td bgcolor=\"#000099\" colspan=\"4\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Oferecida: " . $disc . "</b></font></td>");
            echo ("</tr>\n"); 
            echo ("<td bgcolor=\"#000099\" colspan=\"3\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Periodo: " . $periodo_id . "</b></font></td>");
            echo ("<td bgcolor=\"#000099\" colspan=\"2\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Créditos: " . $num_creditos . "</b></font></td>");
            echo ("<td bgcolor=\"#000099\" colspan=\"2\"> <font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\"><b>Freq. Min: " . $frequencia_minima . "&nbsp;H/A</b></font></td></tr>\n");
            echo ("<tr><td bgcolor=\"#000099\" colspan=\"7\">&nbsp;</td></tr>");
            echo ("<tr bgcolor=\"#000000\">\n");
            echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Cont</b></font></td>");
            echo ("<td width=\"50%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Nome</b></font></td>");
            echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Curso</b></font></td>");
            echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
            echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Nota</b></font></td>");
            echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Faltas<!--Freqüência--></b></font></td>");
            echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Desist.</b></font></td>");
            echo ("  </tr>"); 
        }

        if ( $i % 2 )
        {
            $bg = $bg1;
            $fg = $fg1;
        }
        else
        {
            $bg = $bg2;
            $fg = $fg2;
        }
        
        echo("<tr bgcolor=\"$bg\">\n");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$i</td>");
        echo ("<td width=\"50%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$pessoa_nome</td>");
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$ref_curso</td>");
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$ref_pessoa</td>");
        $j ++;
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\"><input type=\"text\" name=\"nota[]\" value=\"$nota_final\" onChange=\"javascript:mudacampo($j)\" size=\"5\" maxlength=\"5\"></td>");
        $j = $j + 5;
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\"><input type=\"text\" name=\"faltas[]\" value=\"$num_faltas\" onChange=\"javascript:mudacampo($j)\" size=\"5\" maxlength=\"5\"></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">");
	    if ($fl_liberado == '2')
	    {   echo ("<input type=\"checkbox\" name=\"desist_$indice\" value=\"S\" checked>");  }
	    else
	    {   echo ("<input type=\"checkbox\" name=\"desist_$indice\" value=\"N\">"); }
	  
        echo ("<input type=hidden name=\"matricula[]\" value=\"$id_matricula\"></td>");
        echo ("<input type=hidden name=\"ref_pessoa[]\" value=\"$ref_pessoa\">\n");
        echo ("<input type=hidden name=\"pessoa_nome[]\" value=\"$pessoa_nome\">\n");
	    
        echo("  </tr>");
     
     $i++;
     $indice++;
     
   }
   echo ("<tr><td colspan=7 align=center><hr size=1>" .
         "<input type=button value=' Voltar ' onClick=\"javascript:history.go(-1)\">" .
         "<input type=submit value=' Salvar '>" .
         "<input type=hidden name=\"curso_id\"   value=\"$curso_id\">" .
         "<input type=hidden name=\"periodo_id\" value=\"$periodo_id\">" .
         "<input type=hidden name=\"frequencia_maxima\" value=\"$frequencia_maxima\">" .
         "</td></tr>\n");

   echo("</table></center>");

   $query->Close();

   $conn->Close();

}
</script>
<script language="JavaScript">
function mudacampo(qual)
{
document.forms[0].elements[qual].focus();
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="notas_disc_alunos.php3" name="myform">
  <script language="PHP">
    ListaAlunos($disc)
  </script>
</form>
</body>
</html>
