<? require("../../../lib/common.php"); ?>

<html>
<head>
<script language="JavaScript">
function _init()
{
  document.myform.senha.focus();
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<table width="90%" border="0" cellspacing="2" cellpadding="0" height="28" align="center">
<form method="post" action="<? echo($url); ?>" name="myform">
  <tr bgcolor="#000099" height="28"> 
    <td colspan="2"> 
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Digite a senha do Administrador Acadêmico</font></b></font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Usuário</font></td>
    <td><font color="red">&nbsp;<?echo ("secgeral"); ?> 
      <input type="hidden" name="usuario" value="secgeral">
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Senha</font></td>
    <td> 
      <input type="password" name="senha" size="20" maxlength="20">
    </td>
  </tr>
  <tr> 
    <td colspan="2"> 
      <hr size="1">
    </td>
  </tr>
  <tr> 
    <td colspan="2" align="center"> 
      <input type="submit" name="Submit"  value=" Continuar ">
      <input type="reset" name="Submit2"  value="  Limpar  ">
      <input type="button" name="Button2" value="   Sair   " onClick="javascript:history.go(-1)">
    </td>
  </tr>
  <tr> 
    <td colspan="2">&nbsp; </td>
  </tr>
</table>
</form>
</body>
</html>
