<? require("../../../lib/common.php"); ?>

<html>
<head>
<script language="PHP">

$dt  = getdate();
$dia = $dt["mday"];
$mes =$dt["mon"];
$ano = $dt["year"];
</script>
<script language="JavaScript">
var tipo_busca;

function _init()
{
  document.myform.nome.focus();
}

function buscaCidade(pf_opcao)
{
  var url;
  tipo_busca=pf_opcao;

 if (tipo_busca == 1)
   url = '../generico/post/lista_cidades.php3' + 
         '?cnome=' + escape(document.myform.cnome.value);

 else if (tipo_busca == 2)
   url = '../generico/post/lista_cidades.php3' + 
         '?cnome=' + escape(document.myform.cnome_rg.value);

 else if (tipo_busca == 3)
   url = '../generico/post/lista_cidades.php3' + 
         '?cnome=' + escape(document.myform.naturalidade.value);

 else if (tipo_busca == 5)
   url = '../generico/post/lista_cidades.php3' + 
         '?cnome=' + escape(document.myform.d_cidade_2g.value);

 window.open(url,"popWindow","toolbar=no,width=600,height=368,top=5,left=5,directories=no,menubar=no,scrollbars=yes");
}

function incluiFiliacao()
{
  tipo_busca = 6;
  var wnd = window.open("../generico/filiacao_inclui.phtml",'buscaPessoa','toolbar=no,width=550,height=350,scrollbars=yes');
}


function setResult(id,nome,cep,ref_pais,ref_estado,pais_desc)
{
 if (tipo_busca == 1)
 {
      document.myform.ref_cidade.value = id;
      document.myform.cnome.value = nome;
      document.myform.cep.value = cep;
 }

 else if (tipo_busca == 2)
 {
      document.myform.rg_cidade.value = id;
      document.myform.cnome_rg.value = nome;
 }
 
 else if (tipo_busca == 3)
 {
     document.myform.ref_naturalidade.value = id;
     document.myform.naturalidade.value = nome;
     document.myform.ref_nacionalidade.value = ref_pais;
     document.myform.nacionalidade.value = pais_desc;
  }

 else if (tipo_busca == 4)
 {
     document.myform.cidade_1g.value = id;
     document.myform.d_cidade_1g.value = nome;
  }

 else if (tipo_busca == 5)
 {
     document.myform.cidade_2g.value = id;
     document.myform.d_cidade_2g.value = nome;
 }

 else if (tipo_busca == 6)
 {
   document.myform.ref_filiacao.value = id;
   document.myform.nome_filiacao.value = nome + ' ' + cep;
 }

}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido para um curso.');

  field.focus();

  return true;
}

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<div align="center"> 
  <table width="583" border="0" cellspacing="0" cellpadding="0" height="40" align="center">
    <tr bgcolor="#000099"> 
      <td height="35"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Inclus&atilde;o 
          de Respons&aacute;vel - Seguro Estudantil</font></b></font></div>
      </td>
    </tr>
  </table>
  
</div>
<form method="post" action="post/pessoaf_seguro_inclui.php3" name="myform">
  <table cols=2 width="583" align="center">
    <tr> 
      <td bgcolor="#CCCCFF" width="161" height="30"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nome</font></td>
      <td height="30" colspan="3" width="410"> 
        <input name="nome" type=text size="40" maxlength="80">
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="161"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;N&ordm; 
        do CPF</font></td>
      <td colspan="3" width="410"> 
        <input name="cod_cpf_cgc" type=text size="20" maxlength="18">
      </td>
    </tr>
    <tr> 
      <td colspan="4"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td width="161"> 
        <input type="hidden" name="op_cidade" value="2">
      </td>
      <td colspan="3" width="410"> 
        <input type="submit" name="Submit" value="Gravar">
        <input type="reset" name="Submit2" value="Limpar">
        <input type="button" name="Button2" value="Sair do Cadastro" onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
<p>&nbsp;</p></body>
</html>
