<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>

<html>
<head>

<script language="PHP">

function Regimes()
{

  $conn = new Connection;

  $conn->Open();

  $sql= " select id,descricao from regimes_disciplinas order by 1";

  $query = $conn->CreateQuery($sql);

  $n = $query->GetColumnCount();

  echo("<center><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

  $i=1;

  // cores fundo
  $bg0 = "#000000";
  $bg1 = "#EEEEFF";
  $bg2 = "#FFFFEE";

  // cores fonte
  $fg0 = "#FFFFFF";
  $fg1 = "#000099";
  $fg2 = "#000099";
  
  while( $query->MoveNext() )
  {
    list ($id,
          $descricao) = $query->GetRowValues();

    $href1 = "<a href=\"javascript:Confirma_Exclui('$id')\"><img src=\"../images/delete.gif\" alt='Excluir Regime' title='Excluir Regime' align='absmiddle' border=0></a>";
    $href2 = "<a href=\"regimes_disciplinas_altera.phtml?id=$id\"><img src=\"../images/update.gif\" alt='Alterar Regime' title='Alterar Regime' align='absmiddle' border=0></a>";

    if ($i == 1)
    {
      echo("<tr bgcolor=\"#000000\">\n");
      echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;</b></font></td>");
      echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;</b></font></td>");
      echo ("<td width=\"*\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Descrição</b></font></td>");
      echo("  </tr>"); 
    }

    if ( $i % 2)
    {
      echo("<tr bgcolor=\"$bg1\">\n");
      echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href1</td>");
      echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href2</td>");
      echo ("<td width=\"*\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\"><b>$id - $descricao</b></font></td>");
      echo("  </tr>");
    }
    else
    {
      echo("<tr bgcolor=\"$bg2\">\n");
      echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$href1</td>");
      echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$href2</td>");
      echo ("<td width=\"*\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\"><b>$id - $descricao</b></font></td>");
      echo("  </tr>");
    }

    $i++;

  }

  echo("</table></center>");

  $query->Close();

  $conn->Close();
}


Function Exclui_Regime($arg)
{
$conn = new Connection;

$conn->Open();

$sql = "delete from regimes_disciplinas where id = '$id';";

$ok = $conn->Execute($sql);  // tire o @ para visualizar mensagens de error do sistema DB

$conn->Close();

SaguAssert($ok,"Não foi possível de excluir o registro!");

}
</script>

<script language="JavaScript">
function Confirma_Exclui(id)
{
  url = 'post/regimes_disciplinas_excluir.php3?id=' + id;

  if (confirm("Você tem certeza que deseja excluir este regime?"))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/regimes_disciplinas.php3" name="myform">
<table width="90%" align="center">
  <tr bgcolor="#000099"> 
    <td height="35" colspan="2"> 
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Regimes das Disciplinas</font></b></font></div>
    </td>
  </tr>
  <tr>
    <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descrição</font></td>
    <td>
       <input name="descricao" type=text size="20">
    </font></td>
  </tr>
  <tr> 
    <td colspan="2"> 
      <hr size="1">
    </td>
  </tr>
  <tr> 
    <td height="33" colspan="2"> 
      <div align="center"> 
        <input type="submit" name="Submit"  value="  Incluir  ">
        <input type="button" name="Button2" value="   Sair   " onClick="javascript:history.go(-1)">
      </div>
    </td>
  </tr>
  <tr>
    <td height="13" colspan="2">
      <hr size="1">
    </td>
  </tr>
  <tr> 
    <td height="33" colspan="2"> 
      <div align="center">
        <?PHP Regimes(); ?>
      </div>
    </td>
  </tr>
</table>
</form>
</body>
</html>
