<? require("../../../lib/common.php"); ?>

<html>
<head>
<script language="JavaScript">
function _init()
{
  document.myform.id.focus();
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/grava_senha.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099"> 
      <td height="35" colspan="2"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Senha do Administrador Acadêmico</font></b></font></div>
      </td>
    </tr>
    <tr>
      <td bgcolor="#FFFFFF"><font face="Verdana, Arial,
      Helvetica, sans-serif" size="3" color="#00009C">&nbsp;<b>Dados Atuais</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Usuário</font></td>
      <td width="369"><font color="red">&nbsp;<?echo ("secgeral"); ?>
        <input type="hidden" name="usuario" value="secgeral" size="20">
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Senha Atual</font></td>
      <td width="369"> 
        <input name="senha_atual" type=password size="20" maxlength="20">
      </td>
    </tr>
    <tr> 
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#FFFFFF"><font face="Verdana, Arial,
      Helvetica, sans-serif" size="3" color="#00009C">&nbsp;<b>Dados Novos</b></font></td>
    </tr> 
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nova Senha</font></td>
      <td width="369"> 
        <input name="password1" type=password size="20" maxlength="20">
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Repete Nova Senha</font></td>
      <td width="369"> 
        <input name="password2" type=password size="20" maxlength="20">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="reset"  name="Submit2" value=" Limpar ">
        <input type="button" name="Button"  value="  Sair  "  onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
