<? require("../../../lib/common.php"); ?>
<html>
<head>
<script language="JavaScript">
function _init()
{
  document.myform.descricao.focus();
}
</script>

<script language="PHP">

CheckFormParameters(array("id"));

$conn = new Connection;

$conn->Open();

$sql = " select id," .
       "        descricao" .
       " from tipos_curso " .
       " where id = '$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $descricao) = $query->GetRowValues();

$query->Close();

$conn->Close();

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/tipos_curso_altera.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099"> 
      <td height="35" colspan="2"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Alteração de Tipos de Cursos</font></b></font><font size="4" face="Verdana, Arial, Helvetica, sans-serif"><b></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo</font></td>
      <td> <font face="Verdana, Arial, Helvetica, sans-serif" color="#FF0033"> 
        <input type="hidden" name="id" value="<? echo($id); ?>">
        <?php echo($id); ?> </font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descri&ccedil;&atilde;o&nbsp;</font></td>
      <td> 
        <input name="descricao" type=text value="<?echo($descricao);?>" size="35">
      </td>
    </tr>
    <tr> 
      <td colspan="2"><hr></td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit" value=" Salvar ">
        <input type="button" name="Button" value=" Voltar " onclick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
