<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../generico/busca_nome.php3"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<?
  $today = getdate();
  $date  = $today["year"] . "-01-01";
  $op_opcoes2 = SQLArray("select id||' / '||descricao as d,id from periodos where dt_inicial >= '$date' order by d");

  CheckFormParameters(array("ref_pessoa","ref_contrato","ref_curso","ref_campus","ref_periodo","ref_disciplina_ofer","ref_matricula","mes","dividir","num_parcelas","ref_motivo"));

  $aluno_nome = GetPessoaNome($ref_pessoa,true);
?>
<html>
<head>
<script language="JavaScript">
var lu_ofer     = null;
var lu_code     = null;
var lu_desc     = null;
var lu_prof     = null;
var lu_day      = null;
var lu_turno    = null;
var lu_status   = null;
var lu_creditos = null;

function valor(indice)
{
   document.myform.verifica.value = document.myform.validacao[indice].value;
}

function setResult(ofer,id,nome,prof,day,ref_curso,turno,status,creditos)
{
  if (status == '2')
     lu_status.value = 't';
  else
     lu_status.value = 'f';
	      
  lu_ofer.value     = ofer;
  lu_code.value     = id;
  lu_desc.value     = nome;
  lu_prof.value     = prof;
  lu_day.value      = day;
  lu_turno.value    = turno;
  lu_creditos.value = creditos;
}
/* Preenche os campos das disciplinas */
/* Com Mouse                          */
function lookup(obj)
{
  var form = obj.form;

  for ( i=0; i<form.length; i++ )
  {
    if ( form.elements[i] == obj )
    {
      lu_creditos = form.elements[i-8];
      lu_status   = form.elements[i-7];
      lu_code     = form.elements[i-6];
      lu_ofer     = form.elements[i-5];
      lu_desc     = form.elements[i-4];
      lu_prof     = form.elements[i-3];
      lu_day      = form.elements[i-2];
      lu_turno    = form.elements[i-1];

      return true;
    }
  }

  return false;
}

/* Preenche os campos das disciplinas */
/* Com ENTER                          */
function lookup_enter(obj)
{
  var form = obj.form;

  for ( i=0; i<form.length; i++ )
  {
    if ( form.elements[i] == obj )
    {
      lu_creditos = form.elements[i-2];
      lu_status   = form.elements[i-1];
      lu_code     = form.elements[i];
      lu_ofer     = form.elements[i+1]
      lu_desc     = form.elements[i+2];
      lu_prof     = form.elements[i+3];
      lu_day      = form.elements[i+4];
      lu_turno    = form.elements[i+5];

      return true;
    }
  }

  return false;
}
 
/* Preenche os campos das disciplinas do currículo (bolinha vermelha) */
/* Acesso com Mouse                                                   */
function Busca_Ofer1(obj)
{
  if ( !lookup(obj) )
    return;
 
  if (document.myform.verifica.value == '1')
  {
  var url = "../generico/post/lista_disciplinas.php3" +
            "?periodo=" + escape(document.myform.ref_periodo.value) +
            "&curso=" + escape(document.myform.ref_curso.value) +
    	    "&ref_pessoa=" + escape(document.myform.ref_pessoa.value);
  }
  else
  {
  var url = "../generico/post/lista_disciplinas_nome.php3" +
            "?periodo=" + escape(document.myform.ref_periodo.value) +
            "&curso=" + escape(document.myform.ref_curso.value) +
            "&ref_pessoa=" + escape(document.myform.ref_pessoa.value);

   if ( lu_code.value != '' )
     url += '&id=' + escape(lu_code.value);

   if ( lu_desc.value != '' )
     url += '&desc=' + escape(lu_desc.value);

  }
  
  var wnd = window.open(url,'busca','toolbar=no,width=780,height=550,scrollbars=yes');

}

/* Preenche os campos das disciplinas do currículo (bolinha vermelha) */
/* Acesso com ENTER                                                   */
function Busca_Ofer1_enter(obj)
{
  if ( !lookup_enter(obj) )
    return;

  if (document.myform.verifica.value == '1')
  {
  var url = "../generico/post/lista_disciplinas_matricula.php3" +
            "?periodo=" + escape(document.myform.ref_periodo.value) +
            "&curso=" + escape(document.myform.ref_curso.value) +
            "&ref_disciplina=" + escape(document.myform.ref_disciplina.value) +
    	    "&ref_pessoa=" + escape(document.myform.ref_pessoa.value) +
	        "&nao_oferecida=" + document.myform.nao_oferecida.checked;
  }
  else
  {
  var url = "../generico/post/lista_disciplinas_nome_matricula.php3" +
            "?periodo=" + escape(document.myform.ref_periodo.value) +
	        "&curso=" + escape(document.myform.ref_curso.value) +
            "&ref_pessoa=" + escape(document.myform.ref_pessoa.value);

    if ( lu_code.value != '' )
      url += '&id=' + escape(lu_code.value);

    if ( lu_desc.value != '' )
      url += '&desc=' + escape(lu_desc.value);
  }

  var wnd = window.open(url,'busca','toolbar=no,width=780,height=350,scrollbars=yes');

}

/* Preenche os campos das disciplinas eletivas (bolinha amarela) */
/* Acesso com Mouse                                              */
function Busca_Ofer2(obj)
{
  if ( !lookup(obj) )
    return;

  var url = "../generico/post/lista_disciplinas_nome.php3" +
            "?periodo=" + escape(document.myform.ref_periodo.value) +
    	    "&curso=" + escape(document.myform.ref_curso.value) +
            "&ref_pessoa=" + escape(document.myform.ref_pessoa.value);
	      
  if ( lu_code.value != '' )
    url += '&id=' + escape(lu_code.value);

  if ( lu_desc.value != '' )
    url += '&desc=' + escape(lu_desc.value);

  var wnd = window.open(url,'busca','toolbar=no,width=780,height=350,scrollbars=yes');

}

/* Preenche os campos das disciplinas eletivas (bolinha amarela) */
/* Acesso com ENTER                                              */
function Busca_Ofer2_enter(obj)
{
  if ( !lookup_enter(obj) )
    return;

  var url = "../generico/post/lista_disciplinas_nome_matricula.php3" +
            "?periodo=" + escape(document.myform.ref_periodo.value) +
	        "&curso=" + escape(document.myform.ref_curso.value) +
            "&ref_pessoa=" + escape(document.myform.ref_pessoa.value);

  if ( lu_code.value != '' )
    url += '&id=' + escape(lu_code.value);

  if ( lu_desc.value != '' )
    url += '&desc=' + escape(lu_desc.value);

  var wnd = window.open(url,'busca','toolbar=no,width=780,height=350,scrollbars=yes');

}

function VerMatricula()
{
  var vet_code1  = new Array(document.myform.elements.length);
  var vet_day1   = new Array(document.myform.elements.length);
  var vet_turno1 = new Array(document.myform.elements.length);
  
  var j = 0;
  var k = 0;
  var l = 0;
  
  for ( var i=0; i<vet_code1.length; i++ )
  {
    if ( document.myform.elements[i].name=='code1[]')
      vet_code1[j++] = document.myform.elements[i].value;
    if ( document.myform.elements[i].name=='code2[]')
      vet_code1[j++] = document.myform.elements[i].value;
    
    if ( document.myform.elements[i].name=='day1[]')
      vet_day1[k++] = document.myform.elements[i].value;
    if ( document.myform.elements[i].name=='day2[]')
      vet_day1[k++] = document.myform.elements[i].value;
      
    if ( document.myform.elements[i].name=='turno1[]')
      vet_turno1[l++] = document.myform.elements[i].value;
    if ( document.myform.elements[i].name=='turno2[]')
      vet_turno1[l++] = document.myform.elements[i].value;
    
    if ( document.myform.elements[i].name=='ref_disciplina')
      vet_code1[j++] = document.myform.elements[i].value;
    if ( document.myform.elements[i].name=='ref_disciplina_ele')
      vet_code1[j++] = document.myform.elements[i].value;
    
    if ( document.myform.elements[i].name=='day')
      vet_day1[k++] = document.myform.elements[i].value;
    if ( document.myform.elements[i].name=='day_ele')
      vet_day1[k++] = document.myform.elements[i].value;
    
    if ( document.myform.elements[i].name=='turno')
      vet_turno1[l++] = document.myform.elements[i].value;
    if ( document.myform.elements[i].name=='turno_ele')
      vet_turno1[l++] = document.myform.elements[i].value;
      
  }
  
  for ( var i=0; i<j-1; i++ )
  {
    for ( var n=i+1; n<j; n++ )
    {
      if ( (vet_code1[i] == vet_code1[n]) && (vet_code1[i] !=''))
      {
        alert('Você já está matriculado(a) na disciplina de código ' + vet_code1[i] + '!!!');
	        return false;
      }
      if ( (vet_day1[i] == vet_day1[n]) && (vet_turno1[i] == vet_turno1[n]) && (vet_day1[i] != '') && (vet_turno1[i] != '') )
      {
        if (confirm('Não é possível fazer esta disciplina no dia ' + vet_day1[i] + ' e no turno ' + vet_turno1[i] + '\n pois você já está matriculado(a) em uma disciplina neste dia e turno.\n Se mesmo assim você deseja matricular o aluno nesta disciplina\n clique OK, senão clique Cancel.'))
	        return true;
        else
	        return false;
      }

    }
  }
  return true;
}

function TrocaDisciplina(creditos_diurno,creditos_noturno,creditos_disciplina_cancel,turno_disciplina_cancel,turno_curso)
{
    var retorno = VerMatricula();

    if (retorno == true)
    {
        var creditos_disciplina_acres = 0;
        var turno_disciplina_acres = 0;
    
        var creditos     = document.myform.creditos.value;
        var turno        = document.myform.turno.value;
    
        var creditos_ele = document.myform.creditos_ele.value;
        var turno_ele    = document.myform.turno_ele.value;
    
        if ((creditos_ele != '') && (turno_ele != ''))
        {
            creditos_disciplina_acres = creditos_ele;
            turno_disciplina_acres = turno_ele;
        }
        else
        {
            creditos_disciplina_acres = creditos;
            turno_disciplina_acres = turno;
        }
    
        if (turno_curso != 'N')
        {
            if (turno_disciplina_cancel != 'N')
            {
                creditos_diurno = parseInt(creditos_diurno) - parseInt(creditos_disciplina_cancel);
            }
            else
            {
                creditos_noturno = parseInt(creditos_noturno) - parseInt(creditos_disciplina_cancel);
            }
        
            if (turno_disciplina_acres != 'N')
            {
                creditos_diurno = parseInt(creditos_diurno) + parseInt(creditos_disciplina_acres);
            }
            else
            {
                creditos_noturno = parseInt(creditos_noturno) + parseInt(creditos_disciplina_acres);
            }
        
            if ((creditos_diurno < 16) && (creditos_noturno > 0))
            {
                if (confirm('O aluno é de um curso diurno e com esta troca ficará matriculado em \n' + creditos_noturno + ' créditos noturno e ' + creditos_diurno + ' créditos diurnos, ou seja, não estará matriculado \nem pelo menos 16 créditos no diurno. Clique OK para continuar, senão \nclique Cancel.'))
                {
                    document.myform.submit();
                }
                else
                {
                    alert("Disciplina não trocada.");
                }
            }
            else
            {
                document.myform.submit();
            }
        }
        else
        {
            document.myform.submit();
        }
    }
}

</script>

</head>
<body bgcolor="#FFFFFF">
<br>
<form method="post" action="post/troca_disciplina.php3" name="myform">
<table width="90%" align="center">
    <tr>
      <td height=32 bgcolor="#000099" colspan=2 align="center"><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Trocar Disciplina</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="32%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
      <td width="68%">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="hidden" name="ref_pessoa" size="10" value="<?echo($ref_pessoa);?>"><b><? echo($ref_pessoa); ?></b>
            </td>
            <td>
              <input type="hidden" name="aluno_nome" size="32" value="<?echo($aluno_nome);?>"><b><? echo($aluno_nome); ?></b>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td width="100%">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input name="ref_contrato" type="hidden" size="10" maxlength="10" value="<?echo($ref_contrato);?>"><? echo($ref_contrato); ?>
            </td>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">Curso:
              </font></td>
            <td>
              <input type="hidden" name="ref_curso" size="10" maxlength="10" value="<?echo($ref_curso);?>"><? echo($ref_curso); ?>
            </td>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">Campus:
              </font>
              <input type="hidden" name="ref_campus" size="10" maxlength="10" value="<?echo($ref_campus);?>"><? echo($ref_campus); ?>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo&nbsp;</font></td>
      <td width="400">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td colspan="2"> <font color="#000000">
              <input name="ref_periodo" type="hidden" size="10" maxlength="10" value="<?echo($ref_periodo);?>"><? echo($ref_periodo); ?>
              </font> <font color="#000000">
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="193"><font face="Helvetica" size="2" color="#0000cc">&nbsp;M&ecirc;s Sequ&ecirc;ncia</font></td>
      <td width="100%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
       <tr>
        <td>
          <input name="mes" type="hidden" value="<?echo($mes);?>" size="10" maxlength="10"><? echo($mes); ?>
        </td>
        <td width="60" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica,
sans-serif" size="2" color="#00009C">&nbsp;Dividir por</font></td>
        <td width="60">
          <input name="dividir" type="hidden" value="<?echo($dividir);?>" size="10"
maxlength="10"><? echo($dividir); ?>
        </td>
        <td width="60" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica,
sans-serif" size="2" color="#00009C">&nbsp;Nº Parcelas</font></td>
        <td width="60">
          <input name="num_parcelas" type="hidden" value="<?echo($num_parcelas);?>"><? echo($num_parcelas); ?>
          <input name="ref_motivo" type="hidden" value="<?echo($ref_motivo);?>">
          <input name="ref_matricula" type="hidden" value="<?echo($ref_matricula);?>">
          <input name="carga_horaria" type="hidden" value="<?echo($carga_horaria);?>">
          <input name="creditos_diurno" type="hidden" value="<?echo($creditos_diurno);?>">
          <input name="creditos_noturno" type="hidden" value="<?echo($creditos_noturno);?>">
          <input name="creditos_disciplina_cancel" type="hidden" value="<?echo($creditos_disciplina_cancel);?>">
          <input name="turno_disciplina_cancel" type="hidden" value="<?echo($turno_disciplina_cancel);?>">
          <input name="turno_curso" type="hidden" value="<?echo($turno_curso);?>">
        </td>
       </tr>
      </table>
       </td>
    </tr>
    <tr>
      <td colspan="4">
         <hr size="1">
      </td>
    </tr>
</table>

<table width="90%" align="center">
    <tr>
      <td><b><font face="Arial, Helvetica, sans-serif" size="2">CURRÍCULO</font></b></td>
      <td align="rigth"><img src="../images/redball.gif"></td>
      <td>&nbsp;</td>
      <td><b><font face="Arial, Helvetica, sans-serif" size="2">ELETIVAS ou SUBSTITUTAS</font></b></td>
      <td align="rigth"><img src="../images/yellowball.gif"></td>
    </tr>
</table>

<script language="PHP">

$conn = new Connection;

$conn->Open();

$sql = " select A.ref_disciplina, " .
       "    	A.ref_disciplina_subst, " .
       "    	get_dia_semana_abrv(dia_disciplina_ofer_todos(B.id)), " .
       "    	turno_disciplina_ofer_todos(B.id) " .
       " from matricula A, disciplinas_ofer B" .
       " where A.ref_disciplina_ofer = B.id and " .
       "       A.ref_contrato='$ref_contrato' and  " .
       "       A.ref_periodo='$ref_periodo' and" .
       "       A.dt_cancelamento is null and " .
       "       A.ref_disciplina_ofer <> '$ref_disciplina_ofer' ;";
       
$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

for ( $row=0; $query->MoveNext(); $row++ )
{
  list ($ref_disciplina,
        $ref_disciplina_subst,
    	$dia_semana,
        $turno) = $query->GetRowValues();
        
        $code1 = $ref_disciplina;
        $code2 = $ref_disciplina_subst == 0 ? '' : $ref_disciplina_subst;

        if ( !$ref_disciplina_subst )
        {
            $day1    = $dia_semana;
            $day2    = '';
            $turno1  = $turno;
            $turno2  = '';
        }
        else
        {
            $day1    = '';
            $day2    = $dia_semana;
            $turno1  = '';
            $turno2  = $turno;
        }

        echo("\n<input type=\"hidden\" name=\"code1[]\" value=\"$code1\">");
        echo("\n<input type=\"hidden\" name=\"day1[]\" value=\"$day1\">");
        echo("\n<input type=\"hidden\" name=\"turno1[]\" value=\"$turno1\">");
        echo("\n<input type=\"hidden\" name=\"code2[]\" value=\"$code2\">");
        echo("\n<input type=\"hidden\" name=\"day2[]\" value=\"$day2\">");
        echo("\n<input type=\"hidden\" name=\"turno2[]\" value=\"$turno2\">\n");
}

$query->Close();

$sql = " select A.id, " .
       "        B.ref_disciplina, " .
       "        descricao_disciplina(B.ref_disciplina)," .
       "        B.ref_disciplina_subst, " .
       "        descricao_disciplina(B.ref_disciplina_subst)," .
       "        B.ref_curso_subst, " .
       "        professor_disciplina_ofer_todos(A.id), " .
       "        get_dia_semana_abrv(dia_disciplina_ofer_todos(A.id)), " .
       "        turno_disciplina_ofer_todos(A.id), " .
       "        B.status_disciplina " .
       " from disciplinas_ofer A, matricula B " .
       " where A.id = B.ref_disciplina_ofer and " .
       "       B.ref_pessoa='$ref_pessoa' and  " .
       "       B.ref_contrato='$ref_contrato' and  " .
       "       B.ref_periodo='$ref_periodo' and" .
       "       B.dt_cancelamento is null and " .
       "       A.id = '$ref_disciplina_ofer' ;";

$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

$query->MoveNext();
  
list ($ref_disciplina_ofer_mat,
      $ref_disciplina_mat,
      $descricao_disciplina_mat,
      $ref_disciplina_subst_mat,
      $descricao_disciplina_subst_mat,
      $ref_curso_subst_mat,
      $professor_mat,
      $dia_semana_mat,
      $turno_mat,
      $status_disciplina_mat) = $query->GetRowValues();

</script>

<table width="90%" align="center">
    <tr> 
      <td height=32 bgcolor="#000099" colspan=5><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Disciplina a ser Substituída</b></font> 
    </tr>
    <tr>
       <td width="20" bgcolor="#CCCCCC">&nbsp;</td>
       <td width="50" bgcolor="#CCCCCC"><font face="Arial, Helvetica, sans-serif" size="2">C&oacute;digo / Oferecida</font></td>
       <td bgcolor="#CCCCCC" width="290"><font face="Arial, Helvetica, sans-serif" size="2">Disciplina / Professor</font></td>
       <td bgcolor="#CCCCCC" width="50" align="center"><font face="Arial, Helvetica, sans-serif" size="2">Dia / Turno</font></td>
       <td bgcolor="#CCCCCC" width="50" align="right">&nbsp;</td>
    </tr>
    <tr valign="top"> 
      <td><img src="../images/redball.gif" width="16" height="16"></td>
      <td> 
        <input type="hidden" name="ref_disciplina_mat" size="8" value="<?echo($ref_disciplina_mat);?>"> <?echo($ref_disciplina_mat);?><br>
        <input type="hidden" name="ref_disciplina_ofer_mat" size="8" maxlength="8" value="<?echo($ref_disciplina_ofer_mat);?>"><?echo($ref_disciplina_ofer_mat);?>
      </td>
      <td> 
        <input type="hidden" name="descricao_disciplina_mat" size="40" value="<?echo($descricao_disciplina_mat);?>"><?echo($descricao_disciplina_mat);?><br>
        <input type="hidden" name="professor_mat" size="40" value="<?echo($professor_mat);?>"><?echo($professor_mat);?>
      </td>
      <td> 
        <input type="hidden" name="dia_semana_mat" size="3" value="<?echo($dia_semana_mat);?>"><?echo($dia_semana_mat);?><br>
        <input type="hidden" name="turno_mat" size="3" value="<?echo($turno_mat);?>"><?echo($turno_mat);?>
      </td>
    </tr>
    <?
    if (($ref_disciplina_subst_mat != '') && ($ref_disciplina_subst_mat != '0'))
    {
    ?>
    <tr valign="top"> 
      <td><img src="../images/yellowball.gif" width="16" height="16"></td>
      <td> 
        <input type="hidden" name="ref_disciplina_subst_mat" size="8" value="<?echo($ref_disciplina_subst_mat);?>"><?echo($ref_disciplina_subst_mat);?><br>
        <input type="hidden" name="ref_disciplina_ofer_subst_mat" size="8" maxlength="8" value="<?echo($ref_disciplina_ofer_mat);?>"><?echo($ref_disciplina_ofer_mat);?>
      </td>
      <td> 
        <input type="hidden" name="descricao_disciplina_subst_mat" size="40" value="<?echo($descricao_disciplina_subst_mat);?>"><?echo($descricao_disciplina_subst_mat);?><br>
        <input type="hidden" name="professor_subst_mat" size="40" value="<?echo($professor_mat);?>"><?echo($professor_mat);?>
      </td>
      <td> 
        <input type="hidden" name="dia_semana_subst_mat" size="3" value="<?echo($dia_semana_mat);?>"><?echo($dia_semana_mat);?><br>
        <input type="hidden" name="turno_subst_mat" size="3" value="<?echo($turno_mat);?>"><?echo($turno_mat);?>
      </td>
    </tr>
    <?
    }
    ?>
</table>
<table width="90%" align="center">
    <tr> 
      <td height=32 bgcolor="#000099" colspan=3><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Disciplina Substituta</b></font> 
      <td colspan="2" bgcolor="#000099" height="32" align="center"><font face="Verdana" size="2" color="#ffffff"><b>Verificação<br>
      <input type="hidden" name="verifica" value="1">
      <input type="radio" name="validacao" value="1" checked onClick="valor(0)">Sim
      <input type="radio" name="validacao" value="0" onClick="valor(1)">Não
      </b></font>
      </td>
    </tr>
    <tr>
       <td width="20" bgcolor="#CCCCCC">&nbsp;</td>
       <td width="50" bgcolor="#CCCCCC"><font face="Arial, Helvetica, sans-serif" size="2">C&oacute;digo / Oferecida</font></td>
       <td bgcolor="#CCCCCC" width="290"><font face="Arial, Helvetica, sans-serif" size="2">Disciplina / Professor</font></td>
       <td bgcolor="#CCCCCC" width="50" align="center"><font face="Arial, Helvetica, sans-serif" size="2">Dia / Turno</font></td>
       <td bgcolor="#CCCCCC" width="50" align="right">&nbsp;</td>
    </tr>
    <tr valign="top">
      <td valign="center">
       &nbsp;<img src="../images/redball.gif" width="16" height="16">
       <input type="checkbox" name="nao_oferecida" value="yes" onClick="alert('Clicando neste botao você selecionará disciplinas \n que fazem parte do curso do aluno mas que serao \nsubstituídas por autorizaçao do coordenador.')">
      </td>
      <td>
        <input type="hidden" name="creditos">
        <input type="hidden" name="status1">
        <input type="text" name="ref_disciplina" size="8" onChange="Busca_Ofer1_enter(this)">
        <input type="text" name="ref_disciplina_ofer" size="8" maxlength="8">
      </td>
      <td> 
        <input type="text" name="desc" size="40">
        <input type="text" name="prof" size="40">
      </td>
      <td> 
        <input type="text" name="day" size="3">
        <input type="text" name="turno" size="3">
      </td>
      <td> 
        <input type="button" value="..." onClick="Busca_Ofer1(this)" name="button2">
      </td>
    </tr>
  
    
    <tr valign="top"> 
      <td valign="center">
       &nbsp;<img src="../images/yellowball.gif" width="16" height="16"></td>
      <td> 
        <input type="hidden" name="creditos_ele">
        <input type="hidden" name="status2">
        <input type="text" name="ref_disciplina_ele" size="8" onChange="Busca_Ofer2_enter(this)">
        <input type="text" name="ref_disciplina_ofer_ele" size="8" maxlength="8">
      </td>
      <td> 
        <input type="text" name="desc_ele" size="40">
        <input type="text" name="prof_ele" size="40">
      </td>
      <td> 
        <input type="text" name="day_ele" size="3">
        <input type="text" name="turno_ele" size="3">
      </td>
      <td> 
        <input type="button" value="..." onClick="Busca_Ofer2(this)" name="button3">

      </td>
    </tr>
    <tr valign="top">
      <td colspan="5" align="center">
        <input type="button" name="salvar"  value="  Salvar  " onClick="TrocaDisciplina('<?=$creditos_diurno?>','<?=$creditos_noturno?>','<?=$creditos_disciplina_cancel?>','<?=$turno_disciplina_cancel?>','<?=$turno_curso?>')">
        <input type="reset" name="Submit2"  value="  Limpar  ">
        <input type="button" name="Button2" value="  Voltar  " onclick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
  </form>
  
</body>
</html>
