<?php

  require("../../../lib/common.php");
  require("../../../lib/properties.php");

?>

<html>
<head>
<title>Controle de Vagas por Curso</title>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" name="myform">

<?

if ( isset($submit) )
{

  // nova conexão com o db
  $conn = new Connection;
  $conn->open();

  // pega os cinco últimos períodos
  $ref_periodo1 = $ref_periodo;
  $periodos[] = $ref_periodo;
  for($x=0;$x<=9;$x++) // 10 semestres
  {
    $sql = "select ref_anterior from periodos where id = '$ref_periodo1';";
    $query = $conn->CreateQuery($sql);
    if( $query->MoveNext() )
    {
      $ref_periodo1 = $query->GetRowValues(1);
      $ref_periodo1 = $ref_periodo1[0];
      $periodos[] = $ref_periodo1;
    }
  }

  //coloca os periodos na ordem inversa
  $periodos = array_reverse($periodos);

  // pessoas matriculadas por curso e periodo num campus
  foreach ( $periodos as $per )
  {
    $total[$per] = 0;
    
    $sql = "select distinct " .
           "    A.ref_pessoa " .
           "  from " .
           "    matricula A, " .
           "    contratos B " .
           "  where " .
           "    B.dt_desativacao is null and " .
           "    A.dt_cancelamento is null and " .
           "    A.obs_aproveitamento is null and " . // aproveitamento externo
           "    A.ref_curso_subst = '' and " .       // aproveitamento interno
           "    B.id = A.ref_contrato and " .
           "    A.ref_curso = '$ref_curso' and " .
           "    A.ref_periodo = '$per' and " .
           "    A.ref_campus = '$ref_campus' ";

    $query = $conn->CreateQuery($sql);

    while( $query->MoveNext() )
    {
      $ref_pessoa = $query->GetRowValues(1);
      $ref_pessoa = $ref_pessoa[0];
      if ( !@in_array($ref_pessoa,$array_pessoas) )
      {
        $sql = "select fl_formando from contratos where ref_pessoa = '$ref_pessoa'";
        $query1 = $conn->CreateQuery($sql);
        $query1->MoveNext();
        $formando = $query1->GetRowValues(1);
        $formando = $formando[0];

        if ( $formando != 1 )
        {
          $array_pessoas[] = ref_pessoa;
          $total[$per] += 1;
        }
        else
          $total_formandos[$per] += 1;
      }
    }
  }

  // faz as totalizações
  echo "<b>Total de Vagas e Alunos no Curso $ref_curso ...</b><br><br><table border='1'><tr><td><b>Período</b></td>" .
       "<td><b>Vagas</b></td><td><b>Alunos</b></td><td><b>Formandos</b></td></tr>\n";
  foreach ( $total as $per => $qtde )
  {

    echo("  <tr>\n");
    unset($vagas);
    // pega o número de vagas oferecida por curso nos vestibulares
    $sql = "select distinct " .
           "    A.numero_vagas " .
           "  from " .
           "    vest_cursos_disp A, " .
           "    vestibular B" .
           "  where " .
           "    A.ref_curso = '$ref_curso' and " .
           "    A.ref_campus = '$ref_campus' and " .
           "    B.ref_periodo = '$per' and " .
           "    A.ref_vestibular = B.id " ;

    $query = $conn->CreateQuery($sql);
    if( $query->MoveNext() )
    {
      $vagas = $query->GetRowValues(1);
      $vagas = $vagas[0];
      $total_vagas += $vagas;
      $form = $total_formandos[$per];
    }
    echo("    <td>$per&nbsp;</td>\n");
    echo("    <td>$vagas&nbsp;</td>\n");
    echo("    <td>$qtde&nbsp;</td>\n");
    echo("    <td>$form&nbsp;</td>\n");
    echo("  </tr>\n");
    $total_alunos = $qtde;
  }
  echo("</table><br><b>Quantidade Final de Vagas:</b>&nbsp;$total_vagas<br><b>Quantidade Final de Alunos:</b>&nbsp;$total_alunos");
}
else
{

?>
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center">
        <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Controle de Vagas por Curso</b></font>
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF">
        <font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Último&nbsp;Período:</font>
      </td>
      <td>
        <input type="text" name="ref_periodo" size="8" value="">
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">
        <font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td>
        <input type="text" name="ref_curso" size="8" value="">
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF">
        <font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Campus:</font>
      </td>
      <td>
        <input type="text" name="ref_campus" size="8" value="">
      </td>
    </tr>
    <tr>
      <td colspan="2" align="center">
        <hr size="1">
        <input type="submit" name="submit"   value=" Gerar ">
        <input type="button" name="Submit22" value="  Sair  " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>

<?

}

?>

</form>
</body>
</html>
