-- exclui 175 funções não utilizadas pelo sistema
DROP FUNCTION aberto(character varying);
DROP FUNCTION abreviado_prova(character varying);
DROP FUNCTION campus_disciplina_ofer(integer);
DROP FUNCTION categoria_lvr_mat(integer);
DROP FUNCTION cntr_titulo(integer);
DROP FUNCTION creditos_professor(character varying, integer);
DROP FUNCTION curso_conta(integer);
DROP FUNCTION curso_contrato(integer, character varying, integer);
DROP FUNCTION curso_ini_conta(integer);
DROP FUNCTION cursoinperiodo(integer, character varying);
DROP FUNCTION curso_periodo(character varying, integer);
DROP FUNCTION desc_prova_vest(character varying);
DROP FUNCTION dia_disciplina_ofer(integer);
DROP FUNCTION disciplina_equivalente(integer, integer);
DROP FUNCTION dt_ativacao_contrato_antigo(character varying, integer);
DROP FUNCTION equivalencia(integer, integer);
DROP FUNCTION get_area_disciplina(integer, integer, integer);
DROP FUNCTION get_autorizacao_disciplina(integer, integer, integer);
DROP FUNCTION get_bolsa(integer);
DROP FUNCTION get_bolsa_(integer);
DROP FUNCTION get_bolsa_hist(integer);
DROP FUNCTION get_campus_antigo(character varying, integer, integer);
DROP FUNCTION get_campus_atual(character varying, integer);
DROP FUNCTION get_campus_cntr(integer);
DROP FUNCTION get_campus_contabil(integer);
DROP FUNCTION get_campus_contrato(integer);
DROP FUNCTION get_carga_horaria_total(integer, integer);
DROP FUNCTION get_cidade_pessoa(integer);
DROP FUNCTION get_cobranca(integer);
DROP FUNCTION get_cod_cidade(integer);
DROP FUNCTION get_cod_curso_cntr(integer);
DROP FUNCTION get_cod_externo(integer);
DROP FUNCTION get_complemento_disc(integer, integer);
DROP FUNCTION get_conta(character varying);
DROP FUNCTION get_conteudo_programatico(integer);
DROP FUNCTION get_cpf(integer);
DROP FUNCTION get_cred_tit(character varying);
DROP FUNCTION get_curso(integer, integer);
DROP FUNCTION get_curso_antigo(character varying, integer, integer);
DROP FUNCTION get_curso_atual(character varying, integer);
DROP FUNCTION get_curso_cntr(integer);
DROP FUNCTION get_curso_contrato(integer);
DROP FUNCTION get_curso_pessoa(integer);
DROP FUNCTION get_deb_tit(character varying);
DROP FUNCTION get_descr_ccusto(character varying);
DROP FUNCTION get_dia_disc_ofer(integer);
DROP FUNCTION get_disc_cancelada(integer);
DROP FUNCTION get_disciplina_equivalente(integer);
DROP FUNCTION get_disc_ofer(integer, character varying);
DROP FUNCTION get_doc_militar(integer);
DROP FUNCTION get_dt_exame(character varying, character varying);
DROP FUNCTION get_dt_exame(character varying, character);
DROP FUNCTION get_email(integer);
DROP FUNCTION get_endereco_pessoa(integer);
DROP FUNCTION get_estado(integer);
DROP FUNCTION get_filiacao(integer);
DROP FUNCTION get_grupo(integer, integer);
DROP FUNCTION get_horarios_todos(integer);
DROP FUNCTION get_turno_horario(integer);
DROP FUNCTION get_id_contrato(integer, integer, integer);
DROP FUNCTION get_id_matricula(integer, integer, character varying);
DROP FUNCTION get_incentivo(integer);
DROP FUNCTION get_inscricao(character varying, character varying);
DROP FUNCTION get_instituicao(integer);
DROP FUNCTION get_label_periodo(character varying);
DROP FUNCTION get_last_periodo(character varying);
DROP FUNCTION get_locais_pgto(integer);
DROP FUNCTION get_mae(integer);
DROP FUNCTION get_max_pontos(character varying);
DROP FUNCTION get_media(character varying);
DROP FUNCTION get_media_final(character varying);
DROP FUNCTION get_nacionalidade(integer);
DROP FUNCTION get_nota(integer, character varying, boolean);
DROP FUNCTION get_nota_disc_per(integer, integer, character varying);
DROP FUNCTION get_nota_final(integer, integer);
DROP FUNCTION get_num_contrato(integer, integer, integer);
DROP FUNCTION get_numdate(date);
DROP FUNCTION get_num_matr_vest(integer, integer, character varying, character varying);
DROP FUNCTION get_obs(integer);
DROP FUNCTION get_origem(integer);
DROP FUNCTION get_pai(integer);
DROP FUNCTION get_percentual_bolsa(integer, date);
DROP FUNCTION get_periodo_anterior(character varying);
DROP FUNCTION get_periodos_todos(integer);
DROP FUNCTION get_professor_disciplina_ofer(integer, integer);
DROP FUNCTION get_prova(character varying);
DROP FUNCTION get_quitacao_eleitoral(integer);
DROP FUNCTION get_ref_periodo(integer);
DROP FUNCTION get_rg(integer);
DROP FUNCTION get_semestre_curso(integer, integer, integer);
DROP FUNCTION get_senha(integer);
DROP FUNCTION get_sequencia_curso(integer);
DROP FUNCTION get_serie(integer, character varying);
DROP FUNCTION get_sexo(integer);
DROP FUNCTION get_signo(integer);
DROP FUNCTION get_status_contrato(integer);
DROP FUNCTION get_taxa(character varying);
DROP FUNCTION get_tipo_motivo(integer);
DROP FUNCTION get_turma(integer, character varying);
DROP FUNCTION get_turno_curso(integer, integer);
DROP FUNCTION get_turno_abrv(character varying);
DROP FUNCTION get_turno_abrv_(character varying);
DROP FUNCTION get_uf(integer);
DROP FUNCTION get_usename(integer);
DROP FUNCTION get_vagas(character varying, integer, integer);
DROP FUNCTION hist_desc(integer);
DROP FUNCTION inscricao_nome(integer);
DROP FUNCTION inscricao_nome2(integer);
DROP FUNCTION instituicao_nome_atual(integer);
DROP FUNCTION is_calouro(integer, character varying);
DROP FUNCTION is_cancelada(integer, character, character varying);
DROP FUNCTION is_inadimplente(integer, date);
DROP FUNCTION is_matriculado(character varying, integer);
DROP FUNCTION is_matriculado_cntr(character varying, integer);
DROP FUNCTION is_professor_periodo(character varying, integer);
DROP FUNCTION motivo(integer);
DROP FUNCTION motivo_inicial(integer);
DROP FUNCTION nome_curso(integer);
DROP FUNCTION nota_prova(character varying, integer);
DROP FUNCTION num_alunos_disc_ofet(character varying, integer);
DROP FUNCTION num_alunos_sexo(character varying, integer, integer, character, character);
DROP FUNCTION num_creditos(integer, character varying);
DROP FUNCTION num_creditos2(integer, character varying, date);
DROP FUNCTION num_creditos_curso_data(character varying, integer, character varying, date);
DROP FUNCTION num_creditos_curso_entrada(character varying, integer, character varying, date, date);
DROP FUNCTION num_creditos_curso_saida(character varying, integer, character varying, date, date);
DROP FUNCTION numdiscequiv(integer);
DROP FUNCTION num_disciplinas_sem(character varying, integer);
DROP FUNCTION num_disp_matr_pess_per_dt(integer, character varying, date);
DROP FUNCTION num_ensalados(character varying, character varying, character varying, character varying);
DROP FUNCTION num_matric(character varying, integer);
DROP FUNCTION num_matric_curso(integer, integer, character varying);
DROP FUNCTION num_matric_total(character varying, integer);
DROP FUNCTION num_matriculados(integer);
DROP FUNCTION num_matriculas_curso(integer, integer, character varying);
DROP FUNCTION num_meses(dataini date, datafim date);
DROP FUNCTION num_parcelas(integer, character varying);
DROP FUNCTION num_periodos(integer, integer, integer);
DROP FUNCTION num_sala_disciplina_ofer(integer);
DROP FUNCTION pega_curso(integer);
DROP FUNCTION pega_curso_x(integer);
DROP FUNCTION pessoa_cat(integer);
DROP FUNCTION pessoa_categoria(integer);
DROP FUNCTION pessoa_cidade(integer);
DROP FUNCTION pessoa_deficiencia(integer);
DROP FUNCTION pessoa_dtnasc(integer);
DROP FUNCTION pessoa_email(integer);
DROP FUNCTION pessoa_faixa_etaria(integer);
DROP FUNCTION pessoa_fone(integer);
DROP FUNCTION pessoa_idade_ultima_eleicao(integer);
DROP FUNCTION pessoa_nome2(integer);
DROP FUNCTION pessoa_sexo(integer);
DROP FUNCTION preco_curso(integer, character varying, integer);
DROP FUNCTION receita(character varying, integer, integer, integer);
DROP FUNCTION ref_professor_disciplina_ofer(integer);
DROP FUNCTION saldo(character varying);
DROP FUNCTION saldo_a_pagar(character varying, integer, integer, integer);
DROP FUNCTION saldo_previsao(integer, character varying, integer);
DROP FUNCTION saldo_previsao_credito(integer, integer, integer, character varying, character varying, character varying, integer, integer);
DROP FUNCTION saldo_previsao_credito(integer, integer, integer, character varying, character varying, character varying, integer, integer, integer);
DROP FUNCTION soma_pontos_vest(integer, character varying);
DROP FUNCTION status_ativacao_contrato(integer, character varying);
DROP FUNCTION sucinto_disciplina(integer);
DROP FUNCTION titulos_com_lcto(character varying, date, integer);
DROP FUNCTION total_taxa_banco(integer, integer, integer, character varying);
DROP FUNCTION trampa(integer);
DROP FUNCTION turno_curso(integer);
DROP FUNCTION turno_disciplina_ofer(integer);
DROP FUNCTION valor_semestre(integer, integer, integer, character varying, character varying);
DROP FUNCTION verifica_contratos(integer);
DROP FUNCTION vest_max_data(character varying);
DROP FUNCTION vest_min_data(character varying);
DROP FUNCTION x(integer, integer);
DROP FUNCTION xx(integer, integer);
DROP FUNCTION xx(integer);
