<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Calendário Acadêmico</title>
<?
    $op_result = SQLArray($sql_periodos_academico);
    $op1_opcoes = SQLArray("select nome, id from dias order by nome");
?>


<script language="JavaScript">
function Confirma_Exclui(arg1,arg2,arg3)
{
  url = 'post/calendario_academico_exclui.php3?id=' + arg1;

  if (confirm("Você tem certeza que deseja EXCLUIR a data de aula: "+arg3+"/"+arg2+" ?"))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
}
</script>

<script language="PHP">

$hasmore = false;

function MostraCalendario()
{  
    global $ref_periodo, $hasmore;
  
    if ( $ref_periodo != "" )
    {

        $conn = new Connection;

        $conn->Open();

        $sql= " select id, " .
              "        ref_periodo, " .
              "        get_dia_semana(dia_semana), " .
              "        to_char(data_aula,'dd-mm-yyyy') " .
              " from calendario_academico " .
              " where ref_periodo = '$ref_periodo' " .
              " order by dia_semana, " .
              "          data_aula";

        $query = $conn->CreateQuery($sql);

        echo("<center><table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
        echo("<tr bgcolor=\"#000000\">\n");
        echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
        echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Período</b></font></td>");
        echo ("<td width=\"40%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Dia Semana</b></font></td>");
        echo ("<td width=\"20%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Data Aula</b></font></td>");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo("  </tr>"); 

        $i=1;

        // cores fundo
        $bg0 = "#000000";
        $bg1 = "#EEEEFF";
        $bg2 = "#FFFFEE";

        // cores fonte
        $fg0 = "#FFFFFF";
        $fg1 = "#000099";
        $fg2 = "#000099";
 
        $dia_semana_aux = -1;
        $count = 0;
        $first = true;
        while( $query->MoveNext() )
        {
            list ($id,
                  $ref_periodo,
                  $dia_semana,
                  $data_aula) = $query->GetRowValues();

            $href  = "<a href=\"calendario_academico_altera.phtml?id=$id\"><img src=\"../images/update.gif\" title='Alterar Cadastro' align='absmiddle' border=0></a>";
            $href1 = "<a href=\"javascript:Confirma_Exclui('$id','$ref_periodo','$data_aula')\"><img src=\"../images/delete.gif\" title='Excluir Cadastro' align='absmiddle' border=0></a>";
            
            if ($dia_semana_aux != $dia_semana)
            {
                if ($first != 'true')
                {
                    echo("<tr><td colspan=\"6\" align=\"center\"><b>Número de $dia_semana_aux: $count</b></td></tr>");
                    $count = 0;
                }

                echo("<tr><td colspan=\"6\" align=\"center\"><hr></td></tr>");
                $dia_semana_aux = $dia_semana;
            }
            
            $count++;
            $first = false;

            if ( $i % 2)
            {
                $fg = $fg2;
                $bg = $bg1;
            }
            else
            {
                $fg = $fg1;
                $bg = $bg2;
            }
            
            echo("<tr bgcolor=\"$bg\">\n");
            echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$i</td>");
            echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$ref_periodo</td>");
            echo ("<td width=\"40%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$dia_semana</td>");
            echo ("<td width=\"20%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$data_aula</td>");
            echo ("<td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href</font></b></td>\n");
            echo ("<td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">&nbsp;$href1</font></b></td>\n");
            echo("  </tr>");


            $i++;

        }
        
        echo("<tr><td colspan=\"6\" align=\"center\"><b>Número de $dia_semana_aux: $count</b></td></tr>");
        echo("<tr><td colspan=\"6\" align=\"center\"><hr></td></tr>");

        echo("</table></center>");
        $query->Close();
        $conn->Close();
    }
    else
        echo("<br><center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center><br>");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="consulta_inclui_calendario_academico.phtml" name="myform">
  <div align="center"> 
    <p> 
      <input type="button" name="button"  value=" Incluir " onClick="location='calendario_academico_inclui.phtml'">
      <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
    </p>
   </div>
  <hr align="center" width="490">
  <p align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O DUPLICAR CADASTROS !</font></b></font> </p>
  <div align="center"> 
    <table width="500" border="0" cellspacing="0" cellpadding="2" height="100">
      <tr bgcolor="#0066CC"> 
        <td colspan="4" height="28"> 
          <div align="center"><font size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o de Calendário Acadêmico por Período</font></b></font></div>
        </td>
      </tr>
      <tr><td>&nbsp;</td></tr>
      <tr> 
        <td bgcolor="#CCCCFF" width="50"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp;Período:&nbsp;&nbsp;</font></td>
            <td>
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
        		ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script></font></td>	
            <td width="40"> 
          <input type="submit" name="botao" value="Localizar">
          </td>
      </tr>
      <tr> 
        <td colspan="4" align="center"> 
          <hr size="1" width="490">
        </td>
      </tr>
      <tr> 
        <td colspan="4"> <?PHP MostraCalendario(); ?> <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
          </font><font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000">
	  <?PHP  if ( $hasmore )
          echo("<BR>Se a informação não estiver listada, seja mais específico."); ?>
	  </font></b></font></font><font color="#FF0000"> 
          </font></b></font></font> </td>
      </tr>
      <tr align="center"> 
        <td colspan="4"> 
          <hr size="1" width="490">
        </td>
      </tr>
    </table>
  </div>
<center>
    <input type="button" name="Button3" value="Copiar Calendário" onClick="location='copiar_calendario.phtml'">
</center>
</form>
</body>
</html>
