<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<? require("../lib/CalcValorAtual.php3"); ?>
<? require("../lib/InvData.php3"); ?>

<html>
<head>

<?
    CheckFormParameters(array("pessoa"));
?>

<script language="JavaScript">
function pagamentos(ender)
{
  window.open(ender,'contratos','resizable=yes, toolbar=no,width=740,height=400,scrollbars=yes');
}

</script>

</head>
<body bgcolor="#FFFFFF">
<table border="0" width="100%" align="center" cellspacing="2" cellpadding="0">
  <tr bgcolor="#FFFFFF">
    <td colspan="7">
      <div align="center"><font size="4" face="Verdana, Arial, Helvetica, sans-serif">
      <font color="#000099">
      <b>T&iacute;tulos da Pessoa</b></font> <br>
        <font color="#FF3333" size="2">Pessoa:</font>
        <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">
        <?
          if ($pessoa != '')
          {
            $conn = new Connection;
            $conn->Open();

            $sql = " select nome, " .
		           "        fl_dbfolha, " .
                   "        fl_segurado, " .
                   "        seguro_meses " .
                   " from pessoas " .
                   " where id = '$pessoa'";
                   
            $query = $conn->CreateQuery($sql);

            if ($query->MoveNext())
            {
              list ($aluno_nome, 
                    $fl_dbfolha, 
                    $fl_segurado, 
                    $seguro_meses) = $query->GetRowValues();
              
              echo("<font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red>");
              echo("<b> $pessoa </b> - $aluno_nome <br>");
              echo("</font>");
              echo("<b> [<a href=JavaScript:pagamentos('/financeiro/mostra_pgtos.phtml?pessoa=$pessoa')>Pagamentos</a>] </b>");
              echo("<br>");

              if ($fl_dbfolha=='t')
              {  echo("<font color=black> &nbsp;&nbsp; funcionário &nbsp;&nbsp; </font>");  }

              if ($fl_segurado=='t')
              {  echo("<font color=black> &nbsp;&nbsp; FAE: " . str_replace("-","/",str_replace(",",", ",$seguro_meses)) . " &nbsp;&nbsp; </font>");  }

              $query->Close();
              $conn->Close();
            }
            else
            {
              $query->Close();
              $conn->Close();
              echo("Aluno não cadastrado");
            }
          }
          else
          {
             echo("Falta código do aluno");
          }
        ?></font></div>
    </td>
  </tr>
  <tr bgcolor="#000000">
    <td width="69">
      <p><font face="Verdana" size="2" color="#ffffff"><b>&nbsp;T&iacute;tulo</b></font></p>
    </td>
    <td width="87">
      <div align="center"><font face="Verdana" size="2" color="#ffffff"><b>Emiss&atilde;o</b></font></div>
    </td>
    <td width="82">
      <div align="center"><font face="Verdana" size="2" color="#ffffff"><b>Vcto</b></font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#ffffff"><b>Valor</b></font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#ffffff"><b>Aberto</b></font></div>
    </td>
    <td colspan=2>
      <div align="right"><font face="Verdana" size="2" color="#ffffff"><b>Atualizado</b></font></div>
    </td>
  </tr>
  <script language="PHP">

  $conn = new Connection;

  $conn->Open();

  $sql = "select A.id," .
         "       A.ref_pessoa," .
         "       A.ref_curso," .
         "       A.ref_campus," .
         "       A.ref_periodo," .
         "       A.seq_titulo," .
         "       A.ref_cobranca," .
         "       A.ref_local," .
         "       A.ref_origem," .
         "       A.ref_ocorrencia," .
         "       A.dt_emissao," .
         "       A.dt_remessa," .
         "       A.dt_vencimento," .
         "       A.dt_pagamento," .
         "       A.dt_baixa," .
         "       A.valor_nominal," .
         "       A.valor_pago," .
         "       A.valor_aberto," .
         "       A.observacao," .
         "       A.fl_aberto," .
         "       A.fl_aceite," .
         "       A.fl_dce," .
         "       A.fl_gera_manual," .
         "       A.cod_banco," .
         "       A.cod_retorno," .
         "       A.cod_letra," .
         "       get_cred_tit(A.id),".
         "       get_deb_tit(A.id),".
         "       B.desconto_mes," .
         "       B.multa_mes," .
         "       B.multa_pos," .
         "       B.dias_multa," .
         "       get_id_contrato(A.ref_pessoa, A.ref_curso, A.ref_campus)" .
         " from titulos_cr A, origens B".
         " where A.ref_pessoa='$pessoa' and" .
         "       A.ref_origem=B.id " .
         " order by A.dt_vencimento desc";

  $query = $conn->CreateQuery($sql);

  SaguAssert($query,"Nao foi possivel executar a consulta!");
  $grp_periodo=0;
  $Saldo_Bruto_Geral=0;
  $Saldo_Atual_Geral=0;
  for ( $row=0; $query->MoveNext(); $row++ )
  {
  list ($id,
        $ref_pessoa,
        $ref_curso,
        $ref_campus,
        $ref_periodo,
        $seq_titulo,
        $ref_cobranca,
        $ref_local,
        $ref_origem,
        $ref_ocorrencia,
        $dt_emissao,
        $dt_remessa,
        $dt_vencimento,
        $dt_pagamento,
        $dt_baixa,
        $valor_nominal,
        $valor_pago,
        $valor_aberto,
        $observacao,
        $fl_aberto,
        $fl_aceite,
        $fl_dce,
        $fl_gera_manual,
        $cod_banco,
        $cod_retorno,
        $cod_letra,
        $credito,
        $debito,
        $desconto_mes,
        $multa_mes,
        $multa_pos,
        $dias_multa,
        $ref_contrato) = $query->GetRowValues();

  if (($fl_gera_manual == 't') && ($observacao))
  {
    list($lixo1, $lixo2, $desconto_mes)=split("/",$observacao,3);
  }
  
  $saldo = $debito-$credito;

  $vlr_atual = CalcValorAtual($saldo, $dt_vencimento, $desconto_mes, $multa_pos, $multa_mes, $dias_multa, $dias);

  $dt_emissao = InvData($dt_emissao);
  $dt_remessa = InvData($dt_remessa);
  $dt_vencimento = InvData($dt_vencimento);
  $dt_pagamento  = InvData($dt_pagamento);
  $dt_baixa = InvData($dt_baixa);

  $valor_nominal = $valor_nominal*100;
  $valor_nominal = round($valor_nominal);
  settype($valor_nominal, "integer");
  $valor_nominal = $valor_nominal/100;

  $saldo = $saldo*100;
  $saldo = round($saldo);
  settype($saldo, "integer");
  $saldo = $saldo/100;

  $Saldo_Bruto_Geral += $saldo;
  $Saldo_Atual_Geral += $vlr_atual;

  if (( $grp_periodo!=$ref_periodo ))
  {
  </script>
  <tr bgcolor="#CCCCCC">
    <td colspan=7><font face="Verdana" size="2" color="#FF0000"><b><?echo("$ref_periodo");?></b></font></td>
  </tr>
  <script language="PHP">
  }

  $grp_periodo=$ref_periodo;

  if ( ( $row % 2 ) == 0 )
  {
  </script>
  <tr bgcolor="#FFFFEE">
    <td width="69"><font face="Verdana" size="2" color="#000099"><? echo("$id");?>&nbsp;</font>
    </td>
    <td width="87">
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_emissao);?>&nbsp;</font></div>
    </td>
    <td width="82">
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_vencimento);?>&nbsp;</font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($valor_nominal);?></font></div>
    </td>
    <td width="75">
      <p align="right"><font face="Verdana" size="2" color="#000099"><?echo($saldo);?></font></p>
    </td>
    <td width="50">
      <div align="right"><font face="Verdana" size="1" color="#FF0000">
<?php if ($saldo==0) { echo('(X)'); } else { echo("(&nbsp;$dias&nbsp;d)");  } ?>
&nbsp;</font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($vlr_atual);?></font></div>
    </td>
  </tr>
  <script language="PHP">
  }
  else
  {
  </script>
  <tr bgcolor="#EEEEFF">
    <td width="69"><font face="Verdana" size="2" color="#000099"><? echo("$id");?>&nbsp;</font>
    </td>
    <td width="87">
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_emissao);?>&nbsp;</font></div>
    </td>
    <td width="82"> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_vencimento);?>&nbsp;</font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($valor_nominal);?></font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($saldo);?></font></div>
    </td>
    <td width="50">
      <div align="right"><font face="Verdana" size="1" color="#FF0000">
<?php if ($saldo==0) { echo('(X)'); } else { echo("(&nbsp;$dias&nbsp;d)");  } ?>
&nbsp;</font></div>
    </td>
    <td width="75">
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($vlr_atual);?></font></div>
    </td>
  </tr>
  <script language="PHP">
  }
}

$query->Close();

$conn->Close();
</script>
  <tr>
    <td align=left bgcolor=black><font face="Arial" size=2 color=white> <b> &nbsp; Totais </b></font>
    </td>
    <td colspan=5 align=right bgcolor=black><font face="Arial" size=2 color=white><b> <? echo($Saldo_Bruto_Geral); ?> </b></font>
    </td>
    <td align=right bgcolor=black><font face="Arial" size=2 color=white><b> <? echo($Saldo_Atual_Geral); ?> </b></font>
    </td>
  </tr>

  <tr><td colspan=7 align=center><hr></td></tr>
  
  <tr bgcolor="#FFFFFF">
    <td colspan="7">
      <div align="center"><font size="4" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>Multas da Biblioteca</b></font><br>
        <font color="#FF3333" size="2">Pessoa:</font>
         <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color=red>
         <b> <?=$pessoa?> </b> - <?=$aluno_nome?> <br>
        </font></div>
    </td>
  </tr>
 
  <tr bgcolor="#000000">
    <td><font face="Verdana" size="2" color="#ffffff"><b>Código Multa</b></font></td>
    <td colspan="2"><font face="Verdana" size="2" color="#ffffff"><b>Empréstimo</b></font></td>
    <td><div align="center"><font face="Verdana" size="2" color="#ffffff"><b>Data da Multa</b></font></div></td>
    <td><font face="Verdana" size="2" color="#ffffff"><b>Foi Paga?</b></font></td>
    <td colspan="2" align="right"><font face="Verdana" size="2" color="#ffffff"><b>Valor</b></font></td>
  </tr>

<script language="PHP">

$conn_gtc = pg_connect("host=$gtc_HOST port=$gtc_PORT user=$gtc_UID password=$gtc_PWD dbname=$gtc_DB");

$sql = " select codigodapessoa, " .
       "        codigodoemprestimo, " .
       "        codigodamulta, " .
       "        valor, " .
       "        datahora, " .
       "        foipaga " .
       " from gtc_multa " .
       " where codigodapessoa = '$pessoa' and " .
       "       foipaga is false and " .
       "       foiabonada is false and " .
       "       valor < 1000000 ";

$result = @pg_exec($conn_gtc, $sql);
$row = 0;

$Total_Multas = 0;

while ($row < @pg_numrows($result))
{
    $codigodapessoa     = pg_result($result, $row, 0);
    $codigodoemprestimo = pg_result($result, $row, 1);
    $codigodamulta      = pg_result($result, $row, 2);
    $valordamulta       = pg_result($result, $row, 3);
    $datahora           = pg_result($result, $row, 4);
    $foipaga            = pg_result($result, $row, 5);
   
   $Total_Multas += $valordamulta;
   if ($row % 2)
     $bg = "#EEEEFF";
   else
     $bg = "#FFFFEE";

  </script>
  <tr bgcolor="<?echo($bg)?>">
    <td><font face="Verdana" size="2" color="#000099"><?echo($codigodamulta)?></td>
    <td colspan="2"><font face="Verdana" size="2" color="#000099">Multa referente ao empréstimo <?echo($codigodoemprestimo)?></td>
    <td><font face="Verdana" size="2" color="#000099"><?echo($datahora)?></td>
    <td align="center"><font face="Verdana" size="2" color="#000099"><?echo($opcoes[$foipaga])?></td>
    <td colspan="2" align="right"><font face="Verdana" size="2" color="#000099"><?echo($valordamulta)?></td>
  </tr>
  <script language="PHP">
  $row++;
}
if ($row == 0)
{
    echo("<tr><td colspan=\"7\"><div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"red\"><b>Aluno sem multas na biblioteca</b></font></div></td></tr>");
}
</script>

  <tr>
    <td colspan=6 align=left bgcolor=black><font face="Arial" size=2 color=white><b> &nbsp; Totais </b></font>
    </td>
    <td align=right bgcolor=black><font face="Arial" size=2 color=white><b> <? echo($Total_Multas); ?> </b></font>
    </td>
  </tr>

  <tr><td colspan=7 align=center><hr></td></tr>

  <tr bgcolor="#FFFFFF">
    <td colspan="7">
      <div align="center"><font size="4" face="Verdana, Arial, Helvetica, sans-serif" color="#000099"><b>Incentivos</b></font><br>
        <font color="#FF3333" size="2">Pessoa:</font>
         <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color=red>
         <b> <?=$pessoa?> </b> - <?=$aluno_nome?> <br>
        </font></div>
    </td>
  </tr>
  <tr bgcolor="#000000"> 
    <td width="97"><font face="Verdana" size="2" color="#ffffff"><b>Código</b></font></td>
    <td width="69"><font face="Verdana" size="2" color="#ffffff"><b>Contrato</b></font></td>
    <td width="56"><div align="center"><font face="Verdana" size="2" color="#ffffff"><b>Início</b></font></div></td>
    <td width="68"><font face="Verdana" size="2" color="#ffffff"><b>Validade</b></font></td>
    <td width="181"><font face="Verdana" size="2" color="#ffffff"><b>Tipo de Bolsa</b></font></td>
    <td colspan="2" width="43"><font face="Verdana" size="2" color="#ffffff"><b>Percentual(%)</b></font></td>
  </tr>
  <script language="PHP">

  $conn = new Connection;

  $conn->Open();

  $sql = " select A.id," .
         "        A.ref_contrato, " .
         "        B.ref_curso, " .
         "        get_curso_cntr(A.ref_contrato)," .
         "        A.dt_inicio," .
         "        A.dt_validade," .
         "        A.ref_pessoa," .
         "        A.ref_tipo_bolsa, " .
         "        get_bolsa(A.ref_tipo_bolsa)," .
         "        A.percentual, " .
         "        B.ref_campus, " .
         "        B.ref_last_periodo, " .
         "        A.ref_pessoaj" .
         " from bolsas A, contratos B" .
         " where A.ref_pessoa='$pessoa' and " .
         "       A.ref_contrato=B.id";

  $query = $conn->CreateQuery($sql);

  SaguAssert($query,"Nao foi possivel executar a consulta!");

  for ( $row=0; $query->MoveNext(); $row++ )
  {
    list ($id,
          $ref_contrato,
          $curso_cntr,
          $curso_cntr_desc,
          $dt_inicio,
          $dt_validade,
          $ref_pessoa,
          $ref_tipo_bolsa,
          $tipo_bolsa,
          $percentual,
          $ref_campus,
          $ref_periodo, 
          $ref_pessoaj) = $query->GetRowValues();

  $dt_inicio = InvData($dt_inicio);
  $dt_validade = InvData($dt_validade);

  if ( ( $row % 2 ) == 0 )
  {

</script>
  <tr bgcolor="#FFFFEE">
    <td width="97" height="23"><font face="Verdana" size="2" color="#000099"><?echo($id);?></font></td>
    <td width="69" height="23"> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($ref_contrato);?></font></div>
    </td>
    <td width="56" height="23"> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_inicio);?></font></div>
    </td>
    <td width="68" height="23"> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_validade);?>&nbsp;</font></div>
    </td>
    <td width="181" height="23"><font face="Verdana" size="2" color="#000099"><?echo($ref_tipo_bolsa);
echo(" - ");
echo($tipo_bolsa);?>&nbsp;</font></td>
    <td width="43" colspan="2"> 
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($percentual);?>&nbsp;</font></div>
    </td>
  </tr>
  <script language="PHP">
  }
  else
  {
</script>
  <tr bgcolor="#EEEEFF">
    <td width="97"><font face="Verdana" size="2" color="#000099"><?echo($id);?></font></td>
    <td width="69"><div align="center"><font face="Verdana" size="2" color="#000099"><?echo($ref_contrato);?></font></div></td>
    <td width="56">
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_inicio);?></font></div>
    </td>
    <td width="68"> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_validade);?>&nbsp;</font></div>
    </td>
    <td width="181"><font face="Verdana" size="2" color="#000099"><?echo($ref_tipo_bolsa);
echo(" - ");
echo($tipo_bolsa);?>&nbsp;</font></td>
    <td width="43" colspan="2"> 
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($percentual);?>&nbsp;</font></div>
    </td>
  </tr>
  <script language="PHP">
  }
}
if ($row == 0)
{
    echo("<tr><td colspan=\"7\"><div align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"red\"><b>Aluno sem nenhum tipo de incentivo</b></font></div></td></tr>");
}

$query->Close();

$conn->Close();

echo("<form>");
echo("<tr><td colspan=7 align=center><hr>");
echo("<input type=button name=Button value=Fechar onClick=\"javascript:window.close()\">");
echo("</td></tr>");
echo("</form>");

</script>
</table>
</body>
</html>
