<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Horários por Período</title>
<?
    $op_result = SQLArray($sql_periodos_academico);
    $op1_opcoes = SQLArray("select nome, id from turnos order by nome");
?>


<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function Confirma_Exclui(arg1)
{
  url = 'post/horarios_exclui.php3?id=' + arg1;

  if (confirm("Você tem certeza que deseja EXCLUIR o Horário: "+arg1+" ?"))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
}
</script>

<script language="PHP">

$hasmore = false;

function MostraHorarios()
{  
    global $ref_periodo, $hasmore;
  
    if ( $ref_periodo != "" )
    {

        $conn = new Connection;

        $conn->Open();

        $sql= " select id, " .
              "        descricao, " .
              "        turno, " .
              "        hora_ini, " .
              "        hora_fim, " .
              "        to_char(dt_inicial,'dd-mm'), " .
              "        to_char(dt_final,'dd-mm'), " .
              "        hora_aula_dia, " .
              "        num_encontros_minimo " .
              " from horarios " .
              " where ref_periodo = '$ref_periodo' " .
              " order by descricao, turno";

        $query = $conn->CreateQuery($sql);

        echo("<center><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
        echo("<tr bgcolor=\"#000000\">\n");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;Cód.&nbsp;</b></font></td>");
        echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;Descrição&nbsp;</b></font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;Turno&nbsp;</b></font></td>");
        echo ("<td width=\"15%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Hora Início</b></font></td>");
        echo ("<td width=\"15%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Hora Final</b></font></td>");
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Dia/Mês Início</b></font></td>");
        echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;Dia/Mês &nbsp;&nbsp;Fim&nbsp;</b></font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;H/A &nbsp;&nbsp;dia&nbsp;</b></font></td>");
        echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;Número &nbsp;de &nbsp;&nbsp;Encontros&nbsp;</b></font></td>");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\">&nbsp;</font></td>");
        echo("  </tr>"); 

        $i=1;

        // cores fundo
        $bg0 = "#000000";
        $bg1 = "#EEEEFF";
        $bg2 = "#FFFFEE";

        // cores fonte
        $fg0 = "#FFFFFF";
        $fg1 = "#000099";
        $fg2 = "#000099";
  
        while( $query->MoveNext() )
        {

            $registro = $query->GetValue(1);
            $href  = "<a href=\"altera_horario.phtml?id=$registro\"><img src=\"../images/update.gif\" title='Alterar Cadastro' align='absmiddle' border=0></a>";
            $href1 = "<a href=\"javascript:Confirma_Exclui('$registro')\"><img src=\"../images/delete.gif\" title='Excluir Cadastro' align='absmiddle' border=0></a>";

            if ( $i % 2)
            {

                echo("<tr bgcolor=\"$bg1\">\n");
                echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(1) . "</td>");
                echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(2) . "</td>");
                echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(3) . "</td>");
                echo ("<td width=\"15%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(4) . "</td>");
                echo ("<td width=\"15%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(5) . "</td>");
                echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(6) . "</td>");
                echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(7) . "</td>");
                echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(8) . "</td>");
                echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . $query->GetValue(9) . "</td>");
                echo ("<td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$bg1\">$href</font></b></td>\n");
                echo ("<td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$bg1\">$href1</font></b></td>\n");

                echo("  </tr>");

            }
            else
            {
                echo("<tr bgcolor=\"$bg2\">\n");
                echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(1) . "</td>");
                echo ("<td width=\"25%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(2) . "</td>");
                echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(3) . "</td>");
                echo ("<td width=\"15%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(4) . "</td>");
                echo ("<td width=\"15%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(5) . "</td>");
                echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(6) . "</td>");
                echo ("<td width=\"10%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(7) . "</td>");
                echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(8) . "</td>");
                echo ("<td width=\"5%\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . $query->GetValue(9) . "</td>");
                echo ("<td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$bg1\">$href</font></b></td>\n");
                echo ("<td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$bg1\">$href1</font></b></td>\n");
                echo("  </tr>");
            }

            $i++;

        }

        echo("</table></center>");
        $query->Close();
        $conn->Close();
    }
    else
        echo("<br><center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center><br>");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="consulta_inclui_horarios.phtml" name="myform">
  <div align="center"> 
    <p> 
      <input type="button" name="button"  value=" Incluir " onClick="location='horarios_inclui.phtml'">
      <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
    </p>
  </div>
  <hr align="center" width="540">
  <p align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O DUPLICAR CADASTROS !</font></b></font> </p>
  <div align="center"> 
    <table width="540" border="0" cellspacing="0" cellpadding="2" height="100">
      <tr bgcolor="#0066CC"> 
        <td colspan="4" height="28"> 
          <div align="center"><font size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o de Horários por Período</font></b></font></div>
        </td>
      </tr>
      <tr><td>&nbsp;</td></tr>
      <tr> 
        <td bgcolor="#CCCCFF" width="50"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp;Período:&nbsp;&nbsp;</font></td>
            <td>
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
        		ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script></font></td>	
            <td width="40"> 
          <input type="submit" name="botao" value="Localizar">
          </td>
      </tr>
      <tr> 
        <td colspan="4" align="center"> 
          <hr size="1" width="500">
        </td>
      </tr>
      <tr> 
        <td colspan="4"> <?PHP MostraHorarios(); ?> <font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000"> 
          </font><font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font color="#FF0000">
	  <?PHP  if ( $hasmore )
          echo("<BR>Se a informação não estiver listada, seja mais específico."); ?>
	  </font></b></font></font><font color="#FF0000"> 
          </font></b></font></font> </td>
      </tr>
      <tr align="center"> 
        <td colspan="4"> 
          <hr size="1" width="500">
        </td>
      </tr>
    </table>
  </div>
</form>
</body>
</html>
