<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<?
    $op_result = SQLArray($sql_periodos_academico);
?>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
     fld.value = opt.options[i].value;
  else
     fld.value = '';
}
	      
function ChangeOp_de()
{
  ChangeOption(document.myform.op1,document.myform.periodo_de);
}

function ChangeOp_para()
{
  ChangeOption(document.myform.op2,document.myform.periodo_para);
}

function ChangeCode(fld_name,op_name)
{
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/copiar_calendario.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099"> 
      <td height="35" colspan="3"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Copiar Calendário Acadêmico de um período para outro</font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td height="20" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Do Período:</font>
      </td> 
      <td>
        <input type="text" name="periodo_de" size="8" onChange="ChangeCode('periodo_de','op1')" value="<?echo($periodo_de);?>">
      </td>
      <td><font color="#000000">
         <script language="PHP">
            ComboArray("op1",$op_result,$periodo_de,"ChangeOp_de()");
      </script></font>
      </td>
    </tr>
    <tr> 
      <td height="20" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Para o Período:</font>
      </td>
      <td>
        <input type="text" name="periodo_para" size="8" onChange="ChangeCode('periodo_para','op2')" value="<?echo($periodo_para);?>">
      </td>
      <td><font color="#000000">
         <script language="PHP">
            ComboArray("op2",$op_result,$periodo_para,"ChangeOp_para()");
      </script></font>
      </td>
    </tr>
    <tr> 
      <td colspan="3"> 
        <hr size="1">
      </td>
    </tr>
    </table>
    <table align="center">
    <tr> 
      <td colspan="3" align="center"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="reset"  name="Submit2" value=" Limpar ">
        <input type="button" name="Button2" value=" Voltar " onClick="location='consulta_inclui_calendario_academico.phtml'">
      </td>
    </tr>
    </table>
</form>
</body>
</html>
