<? require("../../../lib/common.php"); ?>
<html>
<head>
<script language="PHP">

CheckFormParameters(array("id"));

$conn = new Connection;

$conn->Open();

$sql = "select " .
       "    id," .
       "    nome," .
       "    sucinto," .
       "    obs" .
       "  from cursos_externos where id = '$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $nome,
       $sucinto,
       $obs) = $query->GetRowValues();

$query->Close();

$conn->Close();

</script>
<script language="JavaScript">
function _init()
{
  document.myform.nome.focus();
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/curso_externo_altera.php3" name="myform">
  <div align="center">
    <table width="90%" align="center">
      <tr bgcolor="#000099"> 
        <td height="35" colspan="2"> 
          <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF"> 
            Altera&ccedil;&atilde;o de Cursos Externos</font></b></font></div>
        </td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo&nbsp;</font></td>
        <td> <font face="Verdana, Arial, Helvetica, sans-serif" color="#FF0033"> 
          <input type="hidden" name="id" value="<? echo($id); ?>">
          <?php echo($id); ?></font></td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nome do Curso Externo&nbsp;</font></td>
        <td> 
          <input name="nome" type=text value="<?echo($nome);?>" size="40">
        </td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Abreviatura&nbsp;</font></td>
        <td> 
          <input name="sucinto" type=text value="<?echo($sucinto);?>" size="40">
        </td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Observações&nbsp;</font></td>
        <td> 
          <input name="obs" type=text value="<?echo($obs);?>" size="40">
        </td>
      </tr>
      <tr> 
        <td colspan="2"> 
          <hr size="1">
        </td>
      </tr>
      <tr> 
        <td colspan="2" align="center"> 
          <input type="submit" name="Submit"  value=" Salvar ">
          <input type="button" name="Submit2" value=" Voltar " onclick="javascript:history.go(-1)">
        </td>
      </tr>
    </table>
  </div>
</form>
</body>
</html>
