<? require("../../../lib/common.php"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<? require("../lib/InvData.php3"); ?>
<?  $nome = GetPessoaNome($ref_pessoa,true); ?>

<html>
<head>
<title>Regime Especial</title>

<script language="PHP">
function Mostra_Disciplinas($nome)
{
  global $ref_pessoa;

  $conn = new Connection;

  $conn->Open();

  $sql = " select C.id, " .
         "        C.ref_pessoa, " .
         "        pessoa_nome(C.ref_pessoa), " .
         "        A.ref_disciplina, " .
         "        descricao_disciplina(A.ref_disciplina), " .
         "        get_creditos(A.ref_disciplina), " .
         "        get_carga_horaria(A.ref_disciplina), " .
         "        A.id " .
         " from disciplinas_ofer A, disciplinas_ofer_compl B, matricula C " .
         " where A.id = B.ref_disciplina_ofer and " .
         "       A.id = C.ref_disciplina_ofer and " .
         "       B.ref_disciplina_ofer = C.ref_disciplina_ofer and " .
         "       B.observacao ilike 'REGIME ESPECIAL%' and " .
         "       A.is_cancelada <> '1' and " .
         "       C.ref_pessoa = '$ref_pessoa' and " .
         "       C.dt_cancelamento is null " .
         " order by pessoa_nome(C.ref_pessoa)";
  
  $query = $conn->CreateQuery($sql);

  $n = $query->GetColumnCount();

  echo("<center><table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

  $i=1;

  // cores fundo
  $bg0 = "#000000";
  $bg1 = "#EEEEFF";
  $bg2 = "#FFFFEE";

  // cores fonte
  $fg0 = "#FFFFFF";
  $fg1 = "#000099";
  $fg2 = "#000099";

  echo("<tr bgcolor=\"#000099\">\n");
  echo ("<td colspan=\"5\" align=\"center\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Disciplinas Cursadas em Regime Especial por <br>$nome</b></font></td>");
  echo("  </tr>"); 

  echo("<tr bgcolor=\"#000000\">\n");
  echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
  echo ("<td width=\"45%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Nome da Disciplina</b></font></td>");
  echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Créditos</b></font></td>");
  echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Carga Horária</b></font></td>");
  echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Ofer.</b></font></td>");
  echo("  </tr>"); 
  
  while( $query->MoveNext() )
  {
    $id_matricula         = $query->GetValue(1);
    $ref_pessoa           = $query->GetValue(2);
    $nome_pessoa          = $query->GetValue(3);
    $ref_disciplina       = $query->GetValue(4);
    $descricao_disciplina = $query->GetValue(5);
    $num_creditos         = $query->GetValue(6);
    $carga_horaria        = $query->GetValue(7);
    $ref_disciplina_ofer  = $query->GetValue(8);
    
    if ( $i % 2)
    {
        $bg = $bg1;
        $fg = $fg2;
    }
    else
    {
        $bg = $bg2;
        $fg = $fg1;
    }
    echo("<tr bgcolor=\"$bg\">\n");
    echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$ref_disciplina</td>");
    echo ("<td width=\"45%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$descricao_disciplina</td>");
    echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$num_creditos</td>");
    echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$carga_horaria</td>");
    echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg\">$ref_disciplina_ofer</td>");
    echo("  </tr>");
    
    $i++;

  }

  if ($i == 1)
  {
  echo("<tr><td colspan=\"5\" align=\"center\"><font face=\"Verdana, Arial, Helvetica, sans-serif\"><font color=\"#FF0000\"><b>Aluno não cursou nenhuma disciplina em Regime especial</b></font></font></td></tr>");
  }

  echo("<tr><td colspan=\"5\" align=\"center\")<hr></td></tr>");
  echo("</table></center>");

  $query->Close();

  $conn->Close();
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<?
    Mostra_Disciplinas($nome); 
?>
<div align="center">
  <form method="post" action="">
    <input type="button" name="Submit" value=" Voltar " onClick="javascript:window.close();">
  </form>
</div>
</body>
</html>
