<? header("Cache-Control: no-cache"); ?>
<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Cadernos de Chamada</title>
<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $periodo_id == '' )
{
  list ( $periodo_id ) = QueryExecute($sql_periodos_academico);
  $periodo_id = trim(substr($periodo_id, 0, strpos($periodo_id, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

/*
$sql-novo = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$periodo_id' " .
       " order by A.id;" ;

*/


$sql = " select distinct A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, matricula B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$periodo_id' " .
       " order by A.id;" ;

$op_result1 = SQLArray($sql);

</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);

  document.myform.action = 'cadernos_chamada_periodo.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.curso_id);
}

function ChangeCode(fld_name,op_name)
{
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'periodo_id')
      {
        document.myform.action = 'cadernos_chamada_periodo.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="cadernos_chamada_disc.phtml" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Cadernos de Chamada / Atas de Exame</b></font></td>
    </tr>
    <tr>
      <td width="92" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td width="296"> <font color="#000000"> </font>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="periodo_id" size="8" onChange="ChangeCode('periodo_id','op')" value="<?echo($periodo_id);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td width="92" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td width="296"> <font color="#000000"> </font>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="curso_id" size="8" onChange="ChangeCode('curso_id','op1')">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                ComboArray("op1",$op_result1,$curso_id,"ChangeOp1()");
              </script>
              </font></td>
          </tr>
        </table>
    <tr>
      <td width="92" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Emissão:</font></td>
      <td width="296"> <font color="#000000"> </font>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="data_em" size="10" value='<?echo(date("d\/m\/Y"))?>'>
            </td>
            <td colspan="2">&nbsp;</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td width="92" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Modo de Impressão:</font></td>
       <td>
      	<INPUT type="radio" name="opcao" value="1" checked>Por Disciplina&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="opcao" value="2">Por Dia, Turno e Campus
       </td>
    </tr>
    <tr>
      <td colspan="2" align="center">
        <hr size="1">
        <input type="submit" name="Submit"  value=" Prosseguir ">
        <input type="button" name="Button2" value="    Sair    " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
