<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../generico/busca_nome.php3"); ?>
<?
  $op_opcoes1 = SQLArray("select cod_bolsa || '  ' || descricao," .
                         "       id" .
                         " from  aux_bolsas");
  $op_opcoes2 = SQLArray("$sql_periodos_academico");
  $op_opcoes3 = SQLArray("select id || '  ' || substr(descricao,1,30)," .
                         "       id" .
                         " from  motivos" .
                         " where ref_tipo_motivo in (select conteudo" .
                         "                           from   conf_finan_cont" .
                         "                           where  chave in ('CONTRATO_ATIVA','CONTRATO_DESATIVA'))" .
                         " order by id");
?>
<html>
<head>
<script language="JavaScript">

function seta_campo(ref_pessoa)
{
url = 'canc_reat_contrato.phtml' +
      '?ref_pessoa=' + escape(document.myform.ref_pessoa.value);

self.location=(url);
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp2()
{
  ChangeOption(document.myform.op4,document.myform.ref_periodo);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.motivo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
<script language="JavaScript">
function Confirma_Exclui(arg1)
{
  url = 'post/delete_previsao.php3?id=' + arg1;
  if (confirm("Você tem certeza que deseja excluir a previsão: "+arg1))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
<script language="JavaScript">
function submete(x)
{
  if (x == '1')
  {
    if (document.myform.desativacao.value == '105' || 
        document.myform.desativacao.value == '152' || 
        document.myform.desativacao.value == '550' || 
        document.myform.desativacao.value == '6' || 
        document.myform.desativacao.value == '10' || 
        document.myform.desativacao.value == '16'
       )
    {
         url = "canc_reat_contrato.phtml";

         if (confirm("Aluno com Transferência para outra Instituição, Guia de Tranferência Expedida, \nTranferido internamente para outro Curso, Vestibulando Desistente de Vaga ou\n Aluno com registro de Óbito. Deseja alterar o contrato dele???"))
         {
            alert("Não esqueça de mudar o Motivo de Ativação e o \nStatus do Livro Matrícula do Contrato do Aluno.");
            document.myform.opcao.value = x;
            document.myform.submit();
         }
         else
         {
            location=(url);
         }
    }
    else
    {
        document.myform.opcao.value = x;
        document.myform.submit();
    }
  }
  else
  {
     document.myform.opcao.value = x;
     document.myform.submit();
  }
}

function BuscaPessoa()
{
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.ref_pessoa.value = id;
  document.myform.aluno_nome.value = nome;
}

function buscaContrato()
{
  var pessoa = document.myform.ref_pessoa.value;

  if ( pessoa == '' )
  {
    alert("Código da pessoa inválido ou não especificado!");
    return;
  }

  var title = 'Seleção Contrato';

  var sql = " select A.id as id, " +
            "        A.ref_curso as Curso, " +
            "        A.ref_campus as Campus, " +
            "        B.descricao as Descricao, " +
            "        A.ref_motivo_desativacao as Desativacao" +
            " from contratos A, cursos B" +
            " where A.ref_pessoa = " + pessoa + " and " +
            "       A.ref_curso = B.id";

  var url = "../generico/post/lista_sql.php3?title=" + escape(title) + "&sql=" + escape(sql);

  window.setResultCallback = window.setContrato;
  
  var wnd = window.open(url,'buscaContrato','toolbar=no,width=550,height=350,scrollbars=yes');

}

function setContrato(id,curso,campus,descricao,desativacao)
{
  document.myform.ref_contrato.value = id;
  document.myform.curso.value = curso;
  document.myform.campus.value = campus;
  document.myform.desativacao.value = desativacao;
  
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/canc_reat_contrato.php3" name="myform">
  <table width="90%" align="center">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Cancela/Reativa Contrato </b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="ref_pessoa" size="8" onChange="javascript:seta_campo(ref_pessoa)" value="<?echo($ref_pessoa);?>">
              <input type="text" name="aluno_nome" size="40" value="<?echo($aluno_nome);?>">
            </td>
            <td>
              <input type="button" value="..." onClick="BuscaPessoa()" name="button">
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input name="ref_contrato" type=text size="8" maxlength="8" value="<?echo($ref_contrato);?>">
             </td>
             <td width="14%" bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Curso</font>
             </td>
             <td>
              <input type="text" name="curso" size="10" maxlength="32" value="<?echo($curso);?>">
             </td>
             <td width="14%" bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Campus</font>
             </td>
             <td>
              <input type="text" name="campus" size="5" maxlength="32" value="<?echo($campus);?>">
              <input type="hidden" name="desativacao" value="<?echo($desativacao);?>">
            </td>
            <td><a href="javascript:buscaContrato()"><img src="../images/find.gif" width="16" height="16" border="0"></a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo&nbsp;</font></td>
      <td>
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td colspan="2"> <font color="#000000">
              <input name="ref_periodo" type=text onChange="ChangeCode('ref_periodo','op4')" value="<?echo($ref_periodo);?>" size="8" maxlength="8">
              </font> <font color="#000000"> </font><font color="#000000">
              <script language="PHP">
		ComboArray("op4",$op_opcoes2,$ref_periodo,"ChangeOp2()");
	      </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Motivo</font></td>
      <td>
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td colspan="2"> <font color="#000000">
              <input name="motivo" type=text onChange="ChangeCode('motivo','op3')" value="<?echo($ref_motivo);?>"
size="8" maxlength="8">
              </font> <font color="#000000"> </font><font color="#000000">
              <script language="PHP">
        		ComboArray("op3",$op_opcoes3,$motivo,"ChangeOp3()");
	          </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <?if (!empty($ref_pessoa))
      { $nome = Busca_Nome($ref_pessoa);
      ?>
      <script language="javascript">
          document.myform.aluno_nome.value="<? echo($nome); ?>";
      </script>
      <?
      }
    ?>
    <tr>
      <td colspan="2">
        <hr size="1">
      </td>
    </tr>
    <tr>
      <td colspan="2" align="center"> 
        <input type="hidden" name="opcao">
        <input type="button" name="op1" value=" Reativar contrato " onclick="javascript:submete(1)">
        <input type="button" name="op2" value=" Cancelar contrato " onclick="javascript:submete(2)">
        <input type="button" name="Button2" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
  </form>
</body>
</html>
