<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
  $ref_curso = $properties->Get("ref_curso");
  $op1_opcoes = SQLArray("$sql_periodos_academico");
  $op2_opcoes = SQLArray("$sql_periodos_academico");
?>

<HTML>
<head>

<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.periodo_atual);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.last_periodo);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.last_periodo1);
}

function ChangeOp4()
{
  ChangeOption(document.myform.op4,document.myform.last_periodo2);
}

function ChangeOp5()
{
  ChangeOption(document.myform.op5,document.myform.last_periodo3);
}

function ChangeOp6()
{
  ChangeOption(document.myform.op6,document.myform.last_periodo4);
}

function ChangeCode(fld_name,op_name)
{
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

</script>
</HEAD>
<BODY bgcolor="#FFFFFF" marginwidth="20" marginheight="20"> 
<FORM method="post" action="../relat/carta_trancados_ps.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099">
      <td colspan="2" height="28">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp; Carta para Alunos Trancados</b></font></div>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Per&iacute;odo Atual:</font>
      </td>
      <td>
        <input name="periodo_atual" type=text size="8" onChange="ChangeCode('periodo_atual','op1')" value="<?echo($periodo_atual)?>"><font color="#000000">
        <script language="PHP">ComboArray("op1",$op1_opcoes,$periodo_atual,"ChangeOp1()");</script></font>
      </td>
    </tr>
    <tr>
      <td colspan="2"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C"><b>Per&iacute;odos a serem Tiradas as Cartas</b></font></td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Per&iacute;odo Anterior 1:</font>
      </td>
      <td>
        <input name="last_periodo" type=text size="8" onChange="ChangeCode('last_periodo','op2')" value="<?echo($last_periodo)?>">
        <font color="#000000">
        <script language="PHP">ComboArray("op2",$op2_opcoes,$last_periodo,"ChangeOp2()");</script></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Per&iacute;odo Anterior 2:</font>
      </td>
      <td>
        <input name="last_periodo1" type=text size="8" onChange="ChangeCode('last_periodo1','op3')" value="<?echo($last_periodo1)?>">
        <font color="#000000">
        <script language="PHP">ComboArray("op3",$op2_opcoes,$last_periodo1,"ChangeOp3()");</script></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Per&iacute;odo Anterior 3:</font>
      </td>
      <td>
        <input name="last_periodo2" type=text size="8" onChange="ChangeCode('last_periodo2','op4')" value="<?echo($last_periodo2)?>">
        <font color="#000000">
        <script language="PHP">ComboArray("op4",$op2_opcoes,$last_periodo2,"ChangeOp4()");</script></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Per&iacute;odo Anterior 4:</font>
      </td>
      <td>
        <input name="last_periodo3" type=text size="8" onChange="ChangeCode('last_periodo3','op5')" value="<?echo($last_periodo3)?>">
        <font color="#000000">
        <script language="PHP">ComboArray("op5",$op2_opcoes,$last_periodo3,"ChangeOp5()");</script></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Per&iacute;odo Anterior 5:</font></td>
      <td>
        <input name="last_periodo4" type=text size="8" onChange="ChangeCode('last_periodo4','op6')" value="<?echo($last_periodo4)?>">
        <font color="#000000">
        <script language="PHP">ComboArray("op6",$op2_opcoes,$last_periodo4,"ChangeOp6()");</script>
        </font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Semestre de Reingresso: </font></td>
      <td>
        <input type="text" name="sem_reing" size="8" value="<?echo($sem_reing)?>">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Data Para Solicitaç&atilde;o<br>&nbsp;de Reingresso: (dd/mm/aaaa) </font></td>
      <td>
        <input type="text" name="dia_sol" size="2" maxlength="2" value="<?echo($dia_sol)?>">/
        <input type="text" name="mes_sol" size="2" maxlength="2" value="<?echo($mes_sol)?>">/
        <input type="text" name="ano_sol" size="4" maxlength="4" value="<?echo($ano_sol)?>">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;&Eacute;poca para Rematr&iacute;cula: </font></td>
      <td>
        <input type="text" name="periodo_rematricula" size="40" maxlength="100" value="99 de xxxxxxxx à 99 de xxxxxxxx de 9999">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">
        &nbsp;Data Pag. 1ª Matr&iacute;cula: <br> (dd/m/aaaa) </font></td>
      <td>
        <input type="text" name="dia_prim_mens" size="2" maxlength="2" value="<?echo($dia_prim_mens)?>">/
        <input type="text" name="mes_prim_mens" size="2" maxlength="2" value="<?echo($mes_prim_mens)?>">/
        <input type="text" name="ano_prim_mens" size="4" maxlength="4" value="<?echo($ano_prim_mens)?>">
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <hr size="1">
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <div align="center">
          <input type="submit" name="Submit"   value=" Imprimir ">
          <input type="reset"  name="Submit2"  value="  Limpar  ">
          <input type="button" name="Submit22" value="   Sair   " onClick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
</form>
</BODY>
</HTML>
