<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/InvData.php3"); ?>

<html>
<head>
<title>Inclusão de Data de Exame</title>
<script language="JavaScript">
 function _init()
 {
   document.selecao.ref_periodo.focus();
 }
</script>
<script language="JavaScript">
 function Confirma_Exclui(arg1, arg2, arg3, arg4)
 {
   url = 'post/exames_periodo_exclui.php3?ref_periodo=' + arg4 + '&ref_campus=' + arg1 + '&dt_exame=' + arg2 + '&dia_semana=' + arg3;

   if (confirm("Você tem certeza que deseja EXCLUIR a Data de Exame: \n Campus: " +arg1 +"\n Data: "+arg2+"\n Dia Semana: "+arg3))
     location=(url)
   else
     alert("Exclusão Cancelada.");
 }
</script>
<script language="PHP">
function ListaDiaExames()
{
  global $ref_periodo, $hasmore;

  $count = 0;
    
    if ( $ref_periodo != '')
    {
    // cores fundo
    $bg0 = "#000000";
    $bg1 = "#EEEEFF";
    $bg2 = "#FFFFEE";

    // cores fonte
    $fg0 = "#FFFFFF";
    $fg1 = "#000099";
    $fg2 = "#000099";

    $conn = new Connection;
  
    $conn->Open();

    // note the parantheses in the where clause !!!
    $sql = " select ref_campus," .
           " dt_exame," .
           " descricao," .
           " dia_semana " .
           " from dt_exames_periodos where ref_periodo = '$ref_periodo' " .
           " order by dt_exame";

    $query = $conn->CreateQuery($sql);

    echo("<table width=\"490\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
    
    echo("  <tr bgcolor=\"$bg0\">\n");
    echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Data</font></b></td>\n");
    echo("    <td width=\"70%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Descrição</font></b></td>\n");
    echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Campus</font></b></td>\n");
    echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
    echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
    echo("  </tr>\n");

    for ( $i=0; $query->MoveNext(); $i++ )
    {
    
      list ( $ref_campus, 
             $dt_exame, 
	     $descricao, 
	     $dia_semana ) = $query->GetRowValues();
      
      $dt_exame = InvData($dt_exame);
      
      if ( $i % 2 )
      {
        $bg = $bg1;
        $fg = $fg1;
      }
      
      else
      {
        $bg = $bg2;
        $fg = $fg2;
      }

      if ( empty($campo) )
          $campo = '';

      $href  = "<a href=\"exames_periodo_edita.phtml?ref_periodo=$ref_periodo&ref_campus=$ref_campus&dt_exame=$dt_exame&dia_semana=$dia_semana \"><img src=\"../images/update.gif\" alt='Alterar Cadastro' align='absmiddle' border=0></a>";
      $href1 = "<a href=\"javascript:Confirma_Exclui($ref_campus, '$dt_exame', $dia_semana, '$ref_periodo')\"><img src=\"../images/delete.gif\" alt='Excluir' align='absmiddle' border=0></a>";

      echo("  <tr bgcolor=\"$bg\">\n");
      echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$dt_exame</font></b></td>\n");
      echo("    <td width=\"70%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">&nbsp;&nbsp;$descricao</font></b></td>\n");
      echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$ref_campus</font></b></td>\n");
      echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href</font></b></td>\n");
      echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href1</font></b></td>\n");
      echo("  </tr>\n");
    }

    echo("<tr><td colspan=5><hr></td></tr>");
    echo("</table>");


    $hasmore = @$query->MoveNext();

    @$query->Close();

    @$conn->Close();
    }
    else
    echo("<center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center>");
    
    $count = $i;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="consulta_exames_periodo_inclui.phtml" name="selecao">
  <div align="center"> 
    <p> 
      <input type="button" value="  Incluir  " onClick="location='exames_periodo_inclui.phtml'" name="button">
      <input type="button" value="   Sair   " onClick="javascript:history.go(-1)" name="Button">
    </p>
    <hr width="500">
    <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O DUPLICAR CADASTROS !</font></b></font> </p>
    <table width="500" border="0" cellspacing="0" cellpadding="2">
      <tr bgcolor="#0066CC"> 
        <td colspan="4" height="28">
          <div align="center"><font size="2" color="#FFFFFF"><b><font face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o de Datas de Exames</font></b></font></div>
        </td>
      </tr>
      <tr> 
        <td width="1">&nbsp;</td>
        <td width="102"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp;Período:</font> 
        </td>
        <td width="311"><INPUT type="text" name="ref_periodo" size="30" value="<?echo($ref_periodo)?>"> 
        </td>
        <td width="74"><INPUT type="submit" name="botao" value="Localizar">&nbsp; </td>
      </tr>
      <tr> 
        <td colspan="4" align="center"> 
          <hr size="1" width="490">
        </td>
      </tr>
      <tr> 
        <td colspan="4"> 
          <?PHP
            ListaDiaExames(); 
          ?>
        </td>
      </tr>
    </table>
</form>
</body>
</html>
