<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>

<? $op1_opcoes = SQLArray("select descricao || ' - ' || id, id from regimes_disciplinas order by id");?>
<? $op3_opcoes = SQLArray("select nome, id from dias order by 1");?>

<html>
<head>
<script language="PHP">
  $op2_opcoes = SQLArray($sql_periodos_academico);
</script>

<script language="Javascript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_regime);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.periodo_id);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.ref_dia);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/lista_regimes_horarios.php3" name="myform">
  <table cols=2 width="90%" align="center">
    <tr> 
      <td colspan="2" height="28" bgcolor="#000099"><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Disciplinas Oferecidas</b></font></td>
    </tr>

    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="periodo_id" onChange="ChangeCode('periodo_id','op2')" size="8" value="<?echo($periodo_id)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                 ComboArray("op2",$op2_opcoes,$periodo_id,"ChangeOp2()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;<input type=radio value=rad_regime name=rad_opcoes checked>&nbsp;Regime</font>
      </td>
      <td width="70%"> 
        <input name="ref_regime" type=text size="6" value="" onChange="ChangeCode('ref_regime','op1')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op1",$op1_opcoes,$ref_regime,"ChangeOp1()");</script>
        </font>
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;<input type=radio name=rad_opcoes value=rad_dia>&nbsp;Dia</font>
      </td>
      <td width="70%"> 
        <input name="ref_dia" type=text size="6" value="" onChange="ChangeCode('ref_dia','op3')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op3",$op3_opcoes,$ref_dia,"ChangeOp3()");</script>
        </font>
      </td>
    </tr>

    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"   value=" Consultar ">
          <input type="button" name="Submit22" value=" Voltar " onClick="history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
</form>
</body>
</html>
