<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Consultas de Número de Alunos por Cidade</title>

<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $ref_periodo == '' )
{
  list ( $ref_periodo ) = QueryExecute($sql_periodos_academico);
  $ref_periodo = trim(substr($ref_periodo, 0, strpos($ref_periodo, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

$sql = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$ref_periodo' " .
       " order by A.id;" ;

$op_result1 = SQLArray($sql);

$sql = " select nome_campus, id from campus" .
       " order by id;" ;

$op_result2 = SQLArray($sql);

</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);
  document.myform.action = 'cons_numalu_cidade.phtml';
  document.myform.submit();
      
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'ref_periodo')
      {
        document.myform.action = 'cons_numalu_cidade.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="cons_numalu_cidade.php3" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta do N&uacute;mero de Alunos por Cidade</b></font></td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_periodo" size="8" onChange="ChangeCode('ref_periodo','op')" value="<?echo($ref_periodo);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>

    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099"> &nbsp; Curso:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_curso" onChange="ChangeCode('ref_curso','op1')" size="8" value="">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op1",$op_result1,$ref_curso,"ChangeOp1()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Campus:</font></td>
      <td width="296"> <font color="#000000"> </font>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="ref_campus" size="8" onChange="ChangeCode('ref_campus','op2')" value="<?echo($ref_campus);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                  ComboArray("op2",$op_result2,$ref_campus,"ChangeOp2()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Calouros?</font></td>
      <td width="296"> <font color="#000000"> </font>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td colspan="3">
	          <select name="bixo">
                 <option value="nao" selected>Não</option>
                 <option value="sim">Sim</option>
              </select>
            </td>
          </tr>
        </table>
      </td>
   </tr>
   <tr>
      <td colspan="2"><hr></td>
   </tr>
   <tr>
      <td colspan="2" align="center">
        <input type="submit" name="Submit" value="  Gerar  ">
        <input type="button" name="voltar" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
  </tr>
  <tr>
    <td colspan="2" align="center"> <hr> </td>
  </tr>
  <tr> 
    <td colspan="2">
    
      <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="red"><b>&nbsp;(*)&nbsp;</b></font><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099">Somente é obrigatório o campo <i>Período</i>. Os campos "Curso" e "Campus" não são obrigatórios mas poderão servir como filtro.<br>
      <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="red"><b>&nbsp;(*)&nbsp;</b></font><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099">O campo <i>Calouro</i> indica que você quer tirar o relatório somente dos alunos calouros. Caso você informe "Não", será gerado o relatório de <b>todos</b> os alunos, inclusive os calouros.
    </td>
  </tr>
  <tr>
    <td colspan="2" align="center"> <hr> </td>
  </tr>
</table>
</form>
</body>
</html>
