<html>
<head>
<title>Contratos de Prestação de Serviços Educacionais</title>
</head>

<body bgcolor="#FFFFFF" link="#000000" vlink="#000000" alink="#000000">
<P><BR>
<BR>
</P>
<table width="500" border="0" cellspacing="4" cellpadding="1" align="center">

  <tr>
      <TD bgcolor="#FFCC33" height="24" valign="middle">

      <div align="center"><FONT color="#0000cc"><B>Contratos para:</B></FONT><FONT size="+1"></FONT></div>

      </td>
    </tr>

  <tr>
      <TD width="50%" bgcolor="#0099FF" valign="middle">
      <DIV align="center" style="top : 60px;left : 9px;"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="contrato_graduacao.phtml"><font color="#FFFFFF">Cursos de Graduação</font></a></b></font></div>
      </td>
  </tr>
  <tr>
      <TD width="50%" bgcolor="#0099FF" valign="middle">
      <DIV align="center" style="top : 60px;left : 9px;"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="contrato_graduacao2.phtml"><font color="#FFFFFF">Cursos de Graduação (V. 2)</font></a></b></font></div>
      </td>
  </tr>
  <tr>
      <TD width="50%" bgcolor="#0099FF" valign="middle">
      <DIV align="center" style="top : 60px;left : 9px;"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="contrato_aditivo.phtml"><font color="#FFFFFF">Termo Aditivo Contrato</font></a></b></font></div>
      </td>
  </tr>
  <tr>
      <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="contrato_extensao.phtml"><font color="#FFFFFF">Cursos de Extensão</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  <tr>
      <TD width="50%" bgcolor="#0099FF" valign="middle">
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="contrato_tecnico.phtml"><font color="#FFFFFF">Cursos Técnicos</font></a></b></font><font color="#000000" face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>
      </b></font></div>
    </td>
  </tr>
  <tr>
      <TD width="50%" bgcolor="#0099FF" valign="middle">
      <DIV align="center" style="top : 60px;left : 9px;"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><A href="contrato_tecnico2.phtml"><font color="#FFFFFF">Cursos Técnicos (V. 2)</font></a></b></font></div>
      </td>
  </tr>
  <tr>
      <TD width="100%" align="center" bgcolor="#0099FF" valign="middle"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><A href="#" onClick="javascript:history.go(-1)"><b><font color="#FFFFFF">Voltar</font></b></a></font></td>
  </tr>
  </table>

<h2>&nbsp;</h2>

</body>

</html>

