<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
   $op1_opcoes = SQLArray($sql_periodos_academico);
?>
<html>
<head>
<script language="PHP">
CheckFormParameters(array("id"));

$conn = new Connection;

$conn->Open();

$sql = " select id, " .
       "        ref_periodo, " .
       "        ref_disciplina_ofer, " .
       "        ref_disciplina_ofer_compl, " .
       "        get_disciplina_de_disciplina_of(ref_disciplina_ofer), " .
       "        descricao_disciplina(get_disciplina_de_disciplina_of(ref_disciplina_ofer)), " .
       "        to_char(data_nova,'dd-mm-yyyy'), " .
       "        to_char(data_antiga,'dd-mm-yyyy') " .
       " from calendario_academico_compl " . 
       " where id = '$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $ref_periodo,
       $ref_disciplina_ofer,
       $ref_disciplina_ofer_compl,
       $ref_disciplina,
       $descricao_disciplina,
       $data_nova,
       $data_antiga) = $query->GetRowValues();

$query->Close();
$conn->Close();

</script>

</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/datas_aula_altera.php3" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> 
      <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>Alteraçao de Datas de Aulas Remanejadas</b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Código 
        </font>
      </td>
      <td width="80%"> 
        <input name="id" type="hidden" value="<?echo($id)?>">
        <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF">
        <?echo($id);?>
        </font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo 
        </font>
      </td>
      <td width="80%"> 
        <input name="ref_periodo" type="hidden" value="<?echo($ref_periodo)?>">
        <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF">
        <?echo($ref_periodo);?>
        </font>
      </td>
    </tr>

    <tr>
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Código da Disciplina Oferecida&nbsp;</font></td>
      <td colspan="3" width="70%">
       <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
         <td>
            <input type="hidden" name="ref_disciplina_ofer" value="<?echo($ref_disciplina_ofer)?>">
            <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF">
            <? echo("$ref_disciplina_ofer - $descricao_disciplina");?>
            </font>
         </td>
        </tr>
       </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Código da Disciplina Oferecida Compl</font></td>
      <td> 
        <input name="ref_disciplina_ofer_compl" type="hidden" value="<?echo($ref_disciplina_ofer_compl)?>">
        <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF">
        <?echo($ref_disciplina_ofer_compl);?>
        </font>
      </td>
    </tr>
    
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Nova<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td> 
        <input name="data_nova" type=text size="10" maxlength="10" value="<?echo($data_nova)?>">
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Antiga<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td> 
        <input name="data_antiga" type=text size="10" maxlength="10" value="<?echo($data_antiga)?>">
      </td>
    </tr>

    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"  value=" Salvar ">
          <input type="button" name="Submit2" value=" Voltar " onclick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
  </form>
  </body>
</html>
