<?php

require("../../../lib/common.php");
require("../lib/SQLCombo.php3");
require("../lib/GetDescDisciplina.php3");


print_r($_GET);

$id_disciplina_ofer = $_GET['id_disciplina_ofer'];
$ref_campus         = $_GET['ref_campus'];
$ref_curso          = $_GET['ref_curso'];
$ref_periodo        = $_GET['ref_periodo'];
$ref_disciplina     = $_GET['ref_disciplina'];
$turma              = $_GET['turma'];
$ref_periodo_turma  = $_GET['ref_periodo_turma'];
$num_alunos         = $_GET['num_alunos'];
$fixar_num_sala     = $_GET['fixar_num_sala'];
$conteudo           = $_GET['conteudo'];

CheckFormParameters(array("ref_campus","ref_curso" ,"ref_periodo"));

$op1_opcoes = SQLArray("select nome, id from dias order by id");
$op2_opcoes = SQLArray("select turno || ' - ' || hora_ini || ' às ' || hora_fim || ' / ' || descricao, id from horarios where ref_periodo = '$ref_periodo' order by id;");
$op3_opcoes = SQLArray("select descricao || ' - ' || id, id from regimes_disciplinas order by id");


$nome_disciplina = GetDescDisciplina($ref_disciplina, true);

$conn = new Connection;

$conn->Open();
 
$sql = "select nome_campus from campus where id = $ref_campus;";
 
$query = $conn->CreateQuery($sql);
 
SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");
 
list ($nome_campus) = $query->GetRowValues();

$query->Close();
 
$sql = "select descricao from cursos where id = $ref_curso;";
 
$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");
 
list ($nome_curso) = $query->GetRowValues();

$query->Close();

?>

<html>
<head>
<script language="Javascript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.dia_semana);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_horario);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.ref_regime);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  field.focus();

  return true;
}

var cmp;

function buscaPessoa()
{
  cmp = '2';

  var url = '../generico/post/lista_pessoas.php3' +
            '?pnome=' + escape(document.myform.ref_professor_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function buscaProfessor()
{
  cmp = '2';

  var url = '../generico/post/lista_professores.php3' +
            '?pnome=' + escape(document.myform.ref_professor_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}
function buscaSala()
{
  cmp = '3';

  var url = '../generico/post/lista_salas.php3' +
            '?ref_campus=' + escape(document.myform.ref_campus.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2,arg3)
{
  if (cmp=='2')
  {
    document.myform.ref_professor.value = arg1;
    document.myform.ref_professor_nome.value = arg2;
  }

  else if (cmp=='3')
  {
    document.myform.num_sala.value = arg1;
    document.myform.num_alunos.value = arg2;
  }
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/disciplina_ofer_compl.php3"
	name="myform">
<table cols=2 width="90%" align="center">
	<tr bgcolor="#000099">
		<td colspan="2" height="40">
		<div align="center"><font size="3"
			face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">
		&nbsp;Disciplinas Oferecidas</font></b></font></div>
		</td>
	</tr>
	<tr>
		<td colspan="2" height="28">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" height="28" bgcolor="#000099"><font size="2"
			face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Dados
		Gerais</b></font></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Campus</font></td>
		<td width="70%"><font color="#000000"
			face="Verdana, Arial, Helvetica, sans-serif" size="2"><?echo($ref_campus)?>
		- <?echo($nome_campus)?> <input type="hidden" name="ref_campus"
			value="<?echo($ref_campus)?>"> <input type="hidden"
			name="nome_campus" value="<?echo($nome_campus)?>"> </font></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Curso</font></td>
		<td width="70%"><font color="#000000"
			face="Verdana, Arial, Helvetica, sans-serif" size="2"><?echo($ref_curso)?>
		- <?echo($nome_curso)?></font> <input type="hidden" name="ref_curso"
			value="<?echo($ref_curso)?>"> <input type="hidden" name="nome_curso"
			value="<?echo($nome_curso)?>"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo</font></td>
		<td width="70%"><font color="#000000"
			face="Verdana, Arial, Helvetica, sans-serif" size="2"><?echo($ref_periodo)?>
			<?echo($nome_periodo)?></font> <input type="hidden"
			name="ref_periodo" value="<?echo($ref_periodo)?>"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Turma</font></td>
		<td width="70%"><font color="#000000"
			face="Verdana, Arial, Helvetica, sans-serif" size="2"><?echo($turma)?><i>(<?echo($ref_periodo_turma)?>)</i></font>
		<input type="hidden" name="id_disciplina_ofer"
			value="<?echo($id_disciplina_ofer)?>"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Oferecida</font></td>
		<td width="70%"><font color="#000000"
			face="Verdana, Arial, Helvetica, sans-serif" size="2"><?echo($id_disciplina_ofer)?></font>
		<input type="hidden" name="id_disciplina_ofer"
			value="<?echo($id_disciplina_ofer)?>"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Disciplina</font></td>
		<td width="70%"><font color="#000000"
			face="Verdana, Arial, Helvetica, sans-serif" size="2"><?echo($ref_disciplina)?>
		- <?echo($nome_disciplina)?></font> <input type="hidden"
			name="ref_disciplina" value="<?echo($ref_disciplina)?>"> <input
			type="hidden" name="fixar_num_sala" value="<?echo($fixar_num_sala)?>">
		<input type="hidden" name="conteudo" value="<?echo($conteudo)?>"></td>
	</tr>
	<tr>
		<td colspan="2">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" height="28" bgcolor="#000099"><font size="2"
			face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Dados
		Complementares da Disciplina</b></font></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Professor</font></td>
		<td width="70%" valign="middle" align="left">
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td><font color="#000000"> <input name="ref_professor" type=text
					size="6"> <input name="ref_professor_nome" type=text size="40"> </font></td>
				<td><font color="#000000"> <input type="button" value="..."
					onClick="buscaProfessor()" name="button"> </font></td>
			</tr>
		</table>
		</td>
	</tr>

	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Dia
		da Semana</font></td>
		<td width="70%"><input name="dia_semana" type=text size="6" value=""
			onChange="ChangeCode('dia_semana','op1')"> <font color="#000000"> <script
			language="PHP">ComboArray("op1",$op1_opcoes,$dia_semana,"ChangeOp1()");</script>
		</font></td>
	</tr>

	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Horário</font>
		</td>
		<td width="70%"><input name="ref_horario" type=text size="6" value=""
			onChange="ChangeCode('ref_horario','op2')"> <font color="#000000"> <script
			language="PHP">ComboArray("op2",$op2_opcoes,$ref_horario,"ChangeOp2()");</script>
		</font></td>
	</tr>

	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Regime</font>
		</td>
		<td width="70%"><input name="ref_regime" type=text size="6" value=""
			onChange="ChangeCode('ref_regime','op3')"> <font color="#000000"> <script
			language="PHP">ComboArray("op3",$op3_opcoes,$ref_regime,"ChangeOp3()");</script>
		</font></td>
	</tr>

	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nº
		Créditos</font></td>
		<td width="70%"><input name="num_creditos_desconto" type=text size="6">
		</td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Desconto
		(%)</font></td>
		<td width="70%"><input name="desconto" type=text size="6"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;N&ordm;
		Sala </font></td>
		<td width="70%">
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td width="9%"><font color="#000000"> <input name="num_sala"
					type=text size="6" onChange="ChangeCode('ref_disciplina','op3')"></td>
				<td width="100%">&nbsp;</td>
				<td><input type="button" value="..." onClick="buscaSala()"
					name="button2"></td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Numéro
		máximo de Alunos</font></td>
		<td width="70%"><input type="text" name="num_alunos" size="10"
			value="<?echo($num_alunos)?>"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Observação</font></td>
		<td width="70%"><input name="observacao" type=text size="20"></td>
	</tr>
	<tr>
		<td bgcolor="#CCCCFF" width="30%"><font
			face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data
		do Exame<br>
		&nbsp;(Campo Opcional)<br>
		&nbsp;(dd-mm-aaaa)</font></td>
		<td width="70%"><input name="dt_exame" type=text size="10"
			maxlength="10"></td>
	</tr>

	<tr>
		<td colspan="2">
		<hr size="1">
		</td>
	</tr>
	<tr>
		<td colspan="2">
		<div align="center"><input type="submit" name="Submit"
			value=" Salvar "> <input type="reset" name="Submit2" value=" Limpar ">
		<input type="button" name="Submit22" value=" Voltar "
			onClick="history.go(-1)"></div>
		</td>
	</tr>
</table>
</form>
</body>
</html>
