<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Estatísticas Acadêmicas</title>
    
<script language="JavaScript">
function Relatorio1()
{
    location="post/lista_estatisticas_ensino.php3?periodo_id=" + document.myform.periodo_id.value + "&dt_inicial=" + document.myform.dt_inicial.value + "&dt_final=" + document.myform.dt_final.value;
}
</script>

<script language="JavaScript">
function Relatorio2()
{
    location="post/lista_estatisticas_finan.php3?periodo_id=" + document.myform.periodo_id.value + "&dt_inicial=" + document.myform.dt_inicial.value + "&dt_final=" + document.myform.dt_final.value + "&campus_id=" + document.myform.campus_id.value;
}
</script>

<script language="PHP">

$op_result = SQLArray($sql_periodos_academico);

$sql = " select nome_campus, id from campus" .
       " order by id;" ;

$op_result2 = SQLArray($sql);

</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeOp1()
{
  ChangeOption(document.myform.op2,document.myform.campus_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();
  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/lista_estatisticas.php3" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Estat&iacute;sticas Acad&ecirc;micas</b></font></td>
    </tr>
    <tr> 
      <td width="35%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td width="65%"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="periodo_id" size="8" onChange="ChangeCode('periodo_id','op')" value="<?echo($periodo_id);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
	           ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
	      </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Campus Desejado:</font><br><font face="Arial, Helvetica, sans-serif" size="1" color="#000099">&nbsp;(Relatório Financeiro)</font></td>
      <td width="296"> <font color="#000000"> </font>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="campus_id" size="8" onChange="ChangeCode('campus_id','op2')" value="<?echo($campus_id);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                   ComboArray("op2",$op_result2,$campus_id,"ChangeOp1()");
	      </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="35%"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Inicial<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td width="65%">
        <input name="dt_inicial" type=text size="10" maxlength="10">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="35%"><font face="Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Final<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td width="65%">
        <input name="dt_final" type=text size="10" maxlength="10">
      </td>
    </tr>   
    <tr>
      <td colspan="2" align="center"><hr></td>
    </tr>
    <script language="PHP">
      $ref_periodo=$periodo_id;
    </script>
    <tr>
      <td colspan="2" align="center">
        <input type="submit" name="Submit" value="Relatório Acadêmico I">
        <input type="button" name="Submit" value="Relatório Acadêmico II" onClick="javascript:Relatorio1()">
        <input type="button" name="Submit" value="Relatório Financeiro" onClick="javascript:Relatorio2()">
        <input type="button" name="Button2" value=" Sair " onClick="javascript:history.go(-1)">

      </td>
    </tr>
  </table>
</form>
</body>
</html>
