<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
$op_result2 = SQLArray("select id||' - '||nome_campus as d,id from campus order by d");
$op_result3 = SQLArray("select id,id from vestibular order by dt_ordem desc");

?>
<html>
<head>
<title>Etiquetas para Pastas dos Alunos</title>
<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $ref_periodo == '' )
{
  list ( $ref_periodo ) = QueryExecute($sql_periodos_academico);
  $ref_periodo = trim(substr($ref_periodo, 0, strpos($ref_periodo, "/")));
}
$op_result = SQLArray($sql_periodos_academico);
/*
$sql = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$ref_periodo' " .
       " order by A.id;" ;
*/
$sql = " select distinct A.id||' / '||A.abreviatura as d, " .
      "        A.id " .
      " from cursos A, matricula B " .
      " where A.id = B.ref_curso and " .
      "       B.ref_periodo = '$ref_periodo' " .
      " order by A.id;" ;

$op_result1 = SQLArray($sql);

</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);

  document.myform.action = 'etiquetas_pastas_alunos_ps.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.ref_vestibular);
}

function EmiteMensagem(mensagem, tipo)
{
  alert(mensagem);
  document.myform.action = 'etiquetas_pastas_alunos_ps.phtml';
  document.myform.submit();
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'ref_periodo')
      {
        document.myform.action = 'etiquetas_pastas_alunos_ps.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="../relat/etiquetas_pastas_alunos_ps.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099">
      <td colspan="3" height="28">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp; Etiquetas Para as Pastas dos Alunos por Curso</b></font></div>
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_periodo" onChange="ChangeCode('ref_periodo','op')" size="8" value="<?echo($ref_periodo)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_curso" onChange="ChangeCode('ref_curso','op1')" size="8" value="<?echo($ref_curso)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op1",$op_result1,$ref_curso,"ChangeOp1()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <TD bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Campus:</font></td>
      <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="ref_campus" onChange="ChangeCode('ref_campus','op2')" size="8" value="<?echo($ref_campus)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                ComboArray("op2",$op_result2,$ref_campus,"ChangeOp2()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>    

    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Vestibular:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_vestibular" size="8"  onChange="ChangeCode('ref_vestibular','op3')" value="<?echo($ref_vestibular);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
	        	ComboArray("op3",$op_result3,$ref_vestibular,"ChangeOp3()");
	          </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>

    <tr>
      <td bgcolor="#CCCCFF" width="85"><font face="Verdana, Arial, Helvetica, sans-serif" size="3" color="#00009C">&nbsp;Alunos: </font>
      </td>
	  <td>
         <font face="Arial, Helvetica, sans-serif" size="2" color="#000099">
         
         <?if ($tipo=='todos'){?>
         <INPUT type="radio" name="tipo" value="todos" checked onClick="EmiteMensagem('Clicando neste botao você imprimirá as estiquetas de todos \nos alunos de acordo com as especificações acima.','todos')">Todos&nbsp;&nbsp;&nbsp;&nbsp;
         <?}else{?>
         <INPUT type="radio" name="tipo" value="todos" onClick="EmiteMensagem('Clicando neste botao você imprimirá as estiquetas de todos \nos alunos de acordo com as especificações acima.','todos')">Todos&nbsp;&nbsp;&nbsp;&nbsp;

         <?}if ($tipo=='calouros'){?>
         <INPUT type="radio" name="tipo" value="calouros" checked onClick="EmiteMensagem('Clicando neste botao você imprimirá as etiquetas de todos \nos alunos calouros de acordo com as especificações acima.','calouros')">Calouros&nbsp;&nbsp;&nbsp;&nbsp;
         <?}else{?>
         <INPUT type="radio" name="tipo" value="calouros" onClick="EmiteMensagem('Clicando neste botao você imprimirá as etiquetas de todos \nos alunos calouros de acordo com as especificações acima.','calouros')">Calouros&nbsp;&nbsp;&nbsp;&nbsp;
         
         <?}if ($tipo=='veteranos'){?>
         <INPUT type="radio" name="tipo" value="veteranos" checked onClick="EmiteMensagem('Clicando neste botao você imprimirá as etiquetas de todos \nos alunos veteranos de acordo com as especificações acima.','veteranos')">Veteranos&nbsp;&nbsp;&nbsp;&nbsp;
         <?}else{?>
         <INPUT type="radio" name="tipo" value="veteranos" onClick="EmiteMensagem('Clicando neste botao você imprimirá as etiquetas de todos \nos alunos veteranos de acordo com as especificações acima.','veteranos')">Veteranos&nbsp;&nbsp;&nbsp;&nbsp;
         
         <?}if ($tipo=='avulso'){?>
         <INPUT type="radio" name="tipo" value="avulso" checked onClick="EmiteMensagem('Clicando neste botao você imprimirá as etiquetas de todos \nos alunos com o código informado no campo abaixo.','avulso')">Avulso
         <?}else{?>
         <INPUT type="radio" name="tipo" value="avulso" onClick="EmiteMensagem('Clicando neste botao você imprimirá as etiquetas de todos \nos alunos com o código informado no campo abaixo.','avulso')">Avulso
         <?}?>
       </font>
	   </td>
	</tr>

    <?
    if ($tipo == 'avulso')
    {
    ?>
    <tr>
      <td colspan="2" align="center">
        <hr><b>Somente para as pessoas informadas abaixo:<br>(Campo obrigatório quando selecionado a opção <i>Avulso</i>)</b>
      <td>
    </tr>
    <tr>
      <td width="40%">
          Código de pessoa dos alunos que você deseja imprimir as etiquetas. Se for mais de uma pessoa, informe os códigos separados por vírgula (,):
      </td>
      <td width="60%">
        <textarea rows="3" cols="50" name="ref_mult_pes"></textarea>
      </td>
    </tr>
    <?
    }
    ?>
    
    <tr>
      <td colspan="2">
        <hr size="1">
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <div align="center">
          <input type="submit" name="Submit"   value=" Imprimir ">
          <input type="reset"  name="Submit2"  value="  Limpar  ">
          <input type="button" name="Submit22" value="   Sair   " onClick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
</form>
</body>
</html>
