<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
  $op1_opcoes = SQLArray("select id||' '||substr(descricao,1,30) as d,id from periodos order by d");
  $op2_opcoes = SQLArray("select nome_campus, id from campus order by nome_campus");
  $op3_opcoes = SQLArray("select nome, id from dias order by id");
?>  
<html>
<head>
<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_periodo);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.dia_semana);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<FORM method="POST" action="post/exames_periodo_inclui.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099"> 
      <td colspan="2" height="28"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Inclusão de Datas de Exame</font></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo 
        </font>
      </td>
      <td width="80%"> 
        <input name="ref_periodo" type=text size="7" onChange="ChangeCode('ref_periodo','op1')" value="<?echo($ref_periodo)?>">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op1",$op1_opcoes,$ref_periodo,"ChangeOp1()");</script>
        </font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Campus</font>
      </td>
      <td width="80%"> 
        <input name="ref_campus" type=text size="7" value="" onChange="ChangeCode('ref_campus','op2')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op2",$op2_opcoes,$ref_campus,"ChangeOp2()");</script>
        </font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data do Exame&nbsp;<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td><input name="dt_exame" type=text></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descrição&nbsp;</font></td>
      <td><input name="descricao" type=text></td>
    </tr>
<!--    <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Flag Exame</font></td>
      <td width="70%"> 
        <select name="fl_exame">
          <option value="" selected>---- Selecione ----</option>
          <option value="0">Não</option>
          <option value="1">Sim</option>
        </select>
      </td>
    </tr>-->
    <input type=hidden name=fl_exame value=1>

    <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Dia da Semana</font>
      </td>
      <td width="70%"> 
        <input name="dia_semana" type=text size="6" value="" onChange="ChangeCode('dia_semana','op3')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op3",$op3_opcoes,$dia_semana,"ChangeOp3()");</script>
        </font>
      </td>
    </tr>
    <tr>
       <td colspan="2">
          <hr size="1">
       </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="reset"  name="Reset"   value=" Limpar ">
        <input type="button" name="Button2" value=" Voltar " onClick="location='consulta_exames_periodo_inclui.phtml'">
      </td>
    </tr>
  </table>
  </form>
</body>
</html>
