<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? $op1_opcoes = SQLArray("select descricao,id from cursos order by descricao"); ?>
<? $op2_opcoes = SQLArray("select nome_campus, id from campus order by nome_campus"); ?>

<html>
<head>
<script language="PHP">

$conn = new Connection;

$conn->Open();

$sql = "select " .
       " id," .
       " descricao" .
       " from grupos_disciplinas where id='$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $descricao) = $query->GetRowValues();

$query->Close();

$conn->Close();

</script>
<script language="JavaScript">
function _init()
{
document.myform.descricao.focus();
}
</script>

<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.descricao);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/grupos_disciplinas_altera.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099">
      <td height="35" colspan="2" align="center">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Altera&ccedil;&atilde;o de Grupo de Disciplina</font></b></font></div>
      </td>
    </tr>
    <tr>
        <td bgcolor="#CCCCFF" width="114"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo&nbsp;</font></td>
        <td width="374"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#FF0033">
          <input type="hidden" name="id" value="<? echo($id); ?>">
          <?php echo($id); ?></font></td>
      </tr>
      <tr>
        <td bgcolor="#CCCCFF" width="114"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descri&ccedil;&atilde;o&nbsp;</font></td>
        <td width="374">
          <input name="descricao" type=text value="<?echo($descricao);?>" size="40">
        </td>
      </tr> 
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"  value=" Salvar ">
          <input type="button" name="Submit2" value=" Voltar " onClick="history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
</form>
</body>
</html>
