<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<html>
<head>
<script language="JavaScript">
function _init()
{
  document.myform.descricao.focus();
}
</script>
</head>
<body bgcolor="#FFFFFF" leftmargin="20" topmargin="20" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/grupos_disciplinas.php3" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="35"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Inclus&atilde;o de Grupo de Disciplinas</b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="84"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Descri&ccedil;&atilde;o</font></td>
      <td width="404"> 
        <input name="descricao" type=text size="40">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"  value=" Salvar ">
          <input type="reset"  name="Submit2" value=" Limpar ">
          <input type="button" name="Button2" value=" Voltar " onClick="location='consulta_inclui_grupos_disciplinas.phtml'">
        </div>
      </td>
    </tr>
  </table>
</form>
</body>
</html>
