<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../generico/busca_nome.php3"); ?>
<?
  $op_opcoes1 = SQLArray("select cod_bolsa || '  ' || descricao,id from aux_bolsas");
  $op_opcoes3 = SQLArray("select nome, texto from carimbos order by nome");
?>
<html>
<head>
<script language="JavaScript">

function seta_campo(ref_pessoa)
{
url = 'historico_escolar.phtml' +
      '?ref_pessoa=' + escape(document.myform.ref_pessoa.value);

self.location=(url);
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.func1);
  document.myform.carimb1.value = document.myform.op3[document.myform.op3.selectedIndex].text;
}

function ChangeOp4()
{
  ChangeOption(document.myform.op4,document.myform.func2);
  document.myform.carimb2.value = document.myform.op4[document.myform.op4.selectedIndex].text;
}

function BuscaPessoa()
{
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
  
}

function setContrato(id,curso,descricao,campus)
{
  document.myform.ref_contrato.value = id;
  document.myform.curso.value = curso;
  document.myform.campus.value = campus;
}

function buscaContrato()
{
  var pessoa = document.myform.ref_pessoa.value;

  if ( pessoa == '' )
  {
    alert("Código da pessoa inválido ou não especificado!");
    return;
  }

  var title = 'Seleção Contrato';

  var sql = " select A.id as Id, " +
            "        A.ref_curso as Curso, " +
    	    "        B.descricao as Descricao, " +
    	    "        A.ref_campus as Campus, " +
    	    "        A.dt_desativacao as Desativacao" +
            "  from contratos A, cursos B" +
            "  where A.ref_pessoa = " + pessoa + " and " +
            "        A.ref_curso = B.id";

  var url = "../generico/post/lista_sql.php3?title=" + escape(title) + "&sql=" + escape(sql);

  window.setResultCallback = window.setContrato;

  var wnd = window.open(url,'buscaContrato','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.ref_pessoa.value = id;
  document.myform.aluno_nome.value = nome;
}

</SCRIPT>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="../relat/historico_escolar.php3" name="myform">
  <table cols=2 width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>Hist&oacute;rico Escolar </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Aluno</font></td>
      <td width="84%"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_pessoa" size="10" onChange="javascript:seta_campo(ref_pessoa)" value="<?echo($ref_pessoa);?>">
            </td>
            <td> 
              <input type="text" name="aluno_nome" size="30" value="<?echo($aluno_nome);?>">
            </td>
            <td> 
              <input type="button" value="..." onClick="BuscaPessoa()" name="button">
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="16%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Contrato</font></td>
      <td width="84%"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td width="25%"> 
              <input name="ref_contrato" type=text size="10" maxlength="10" value="<?echo($ref_contrato);?>">
            </td>
            <td width="10%" bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Curso</font> 
            </td>
            <td width="20%"><font face="Verdana, Arial, Helvetica, sans-serif"> 
              <input type="text" name="curso" size="5" maxlength="5" value="<?echo($curso);?>">
              </font> </td>
            <td width="10%" bgcolor="#CCCCFF"> <font face="Verdana, Arial, Helvetica, sans-serif" color="#000099" size="2">&nbsp;Campus</font> 
            </td>
            <td width="20%"><font face="Verdana, Arial, Helvetica, sans-serif"> 
              <input type="text" name="campus" size="5" maxlength="5" value="<?echo($campus);?>">
              </font> </td>
            <td width="15%"><a href="javascript:buscaContrato()"><img src="../images/find.gif" width="16" height="16" border="0" alt="Selecionar Contrato"></a> 
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="2"> 
        <p><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#000099"><br>
          Op&ccedil;&otilde;es de Impress&atilde;o:</font></b><br>
      </td>
    </tr>
    <tr>
       <td colspan="2">
          <input type="checkbox" name="discipminim" value="sim">
          Imprimir as disciplinas substitu&iacute;das no Curr&iacute;culo M&iacute;nimo<br>
       </td>
    </tr>
    <tr>
       <td width="80%">
          <input type="checkbox" name="discipcompl" value="sim" checked>
          Imprimir as disciplinas substitu&iacute;das no Curr&iacute;culo Complementar ou imprimir disciplinas substituídas:
       </td>
       <td width="20%">
	      <input size="25" type="text" name="discipcompl1" value="" OnFocus="window.status='Informe o código das disciplinas, separadas por vírgula'; return true;"><br>
        </td>
    </tr>
    <tr>
       <td width="80%">
          <input type="checkbox" name="edfisica" value="sim" checked> Imprimir texto dispensa Educação F&iacute;sica:
       </td>
       <td width="20%">
          <input size="25" type="text" name="textoedfisica" value="EDUCAÇÃO FÍSICA: DISPENSADA EM TODOS OS SEMESTRES, CONFORME LEI Nº 7692/88 ARTIGO 1º, ALÍNEA 'a'."><br>
       </td>
    </tr>
    <tr>
       <td colspan="2">
          <input type="checkbox" name="discipncurs" value="sim" checked> Imprimir &quot;Não Curs.&quot; em disciplinas n&atilde;o cursadas<BR>
       </td>
    </tr>
    <tr>
       <td colspan="2">
          <input type="checkbox" name="datapostila" value="sim"> Imprimir Data Expedição Apostila (Matemática e Biologia)<br>
       </td>
    </tr>
    <tr>
       <td colspan="2">
          <input type="checkbox" name="outras_disciplinas" value="sim" checked> Imprimir Outras Disciplinas Cursadas<br>
       </td>
    </tr>
    <tr>
       <td width="80%">
          <input type="checkbox" name="curso_concluido" value="nao">
          Não imprimir disciplinas de curso concluído:
       </td>
       <td width="20%">
	      <input size="25" type="text" name="curso_concluido1" value="" OnFocus="window.status='Informe o código dos cursos, separadas por vírgula'; return true;"><br>
       </td>
    </tr>
    
    <tr>
       <td colspan="2">
          <input type="checkbox" name="sub_judice" value="sim"> Aluno não está Sub-Júdice<br>
        </td>
    </tr>
    
    <tr>
       <td colspan="2">
          <input type="checkbox" name="hist_final" value="sim"> É Histórico Final<br>
        </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr> 
      <td colspan="2"><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#000099">Carimbos:</font></b></font></td>
    </tr>
    <tr> 
      <td colspan="2"><font size="2" face="Verdana, Arial, Helvetica, sans-serif">&nbsp;Nome:</font>
        <SCRIPT language="PHP">ComboArray("op3",$op_opcoes3,"0","ChangeOp3()");</SCRIPT>
        <input type="text" name="func1" size="25">
      <input type="hidden" name="carimb1" size="25"></td>
    </tr>
    <tr> 
      <td colspan="2"><font face="Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp;Nome:</font>
        <SCRIPT language="PHP">ComboArray("op4",$op_opcoes3,"0","ChangeOp4()");</SCRIPT>
        <input type="text" name="func2" size="25">
      <input type="hidden" name="carimb2" size="25"></td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <font face="Verdana, Arial, Helvetica, sans-serif" size="2">Data Emissão do Histórico: <input type="text" name="DataImpressao" value="<? echo date("d/m/Y") ?>" size="10"></font>
        <hr size="1">
      </td>
    </tr>
    <?if (!empty($ref_pessoa))
      { $nome = Busca_Nome($ref_pessoa);
      ?>
      <script language="javascript">
           document.myform.aluno_nome.value="<? echo($nome); ?>";
      </script>
      <?
      }
    ?>
    <tr> 
      <td colspan="2"> 
        <div align="center"> 
          <input type="submit" name="Submit"   value="Imprimir">
          <input type="reset" name="Submit2"   value=" Limpar ">
          <input type="button" name="Submit22" value="  Sair  " onclick="javascript:history.go(-1)">
        </div>
      </td>
    </tr>
  </table>
  </form>
</body>
</html>
