<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
    $sql = " select id||' / '||abreviatura as d,id from cursos order by id" ;
    $op_result1 = SQLArray($sql);

    $sql = "select id||' / '||nome_campus as d,id from campus order by d";
    $op_result2 = SQLArray($sql);
?>

<html>
<head>
   <title>Alunos por Deficientes</title>
</head>

<script language="JavaScript">

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/lista_deficientes.php3" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Listagem de Alunos Deficientes</b></font></td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_curso" onChange="ChangeCode('ref_curso','op1')" size="8" value="<?echo($ref_curso)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op1",$op_result1,$ref_curso,"ChangeOp1()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <TD width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Campus:</font></td>
      <td width="296">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="ref_campus" onChange="ChangeCode('ref_campus','op2')" size="8" value="<?echo($ref_campus)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000">
              <script language="PHP">
                ComboArray("op2",$op_result2,$ref_campus,"ChangeOp2()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>   
    <tr>
      <td colspan="2"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">Deixe os campos em branco caso deseje realizar uma consulta completa.</font></td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <hr size="1">
        <input type="submit" name="Submit"  value="  Gerar  ">
        <input type="button" name="Button2" value="  Sair  " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
