<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Listagem de Alunos por Faixa Etária</title>
<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $periodo_id == '' )
{
  list ( $periodo_id ) = QueryExecute($sql_periodos_academico);
  $periodo_id = trim(substr($periodo_id, 0, strpos($periodo_id, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

</script>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="listagem_faixa_etaria.php3" name="myform">
<table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
  <tr> 
    <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Consulta do N&uacute;mero de Alunos por Curso e Faixa Etária</b></font></td>
  </tr>
  <tr> 
    <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
    <td width="296"> <font color="#000000"> </font> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td> 
            <input type="text" name="periodo_id" size="8" onChange="ChangeCode('periodo_id','op')" value="<?echo($periodo_id);?>">
          </td>
          <td width="100%"><font color="#000000"> 
            <script language="PHP">
              ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
            </script>
            </font>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td colspan="2"><hr></td>
  </tr>
  
  <tr> 
    <td colspan="2" align="center">
        <input type="submit" name="Submit" value="  Gerar  ">
        <input type="button" name="Button" value="  Sair  " onClick="javascript:history.go(-1)">
    </td>
  </tr>
  
  <tr> 
    <td colspan="2"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="red"><b>&nbsp;(*)&nbsp;</b></font><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#000099">Dados retirados dos livros matrículas já processados. Este relatório não servirá para períodos onde o livro matrícula não foi gerado. Mas se desejarem saber os dados atuais ou destes períodos (períodos em que não foi gerado o livro matrícula) utilize o link <i>Idade</i> no relatório de Número de Alunos por Curso</td>
  </tr>
</table>
</form>
</body>
</html>
