<? require("../../../lib/common.php"); ?>
<? require("../../../lib/properties.php"); ?>

<html>
<head>
<title>Configuração de Exibição dos Cursos no Livro de Matrícula</title>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" name="myform" action="post/livro_matricula_config_exibicao.php3">
<script language="PHP">

  $conn = new Connection;
  $conn->open();

  $sql = "select distinct" .
         "     A.ref_curso_atual," .
         "     B.descricao," .
         "     B.sequencia" .
         " from livro_matricula A, cursos B " .
         " where A.ref_curso_atual = B.id and " .
         "       A.ref_periodo = '$ref_periodo'" .
         " order by B.descricao";

  $query = $conn->CreateQuery($sql);

</script>
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr>
      <td bgcolor="#000099" colspan="3" height="28" align="center">
        <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Configuração de Exibição dos Cursos no Livro de Matrícula</b></font>
      </td>
    </tr>
       <td bgcolor="#000000" align="right">
          <font face="Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b>Cód. Curso&nbsp;</b></font>
       </td>
       <td bgcolor="#000000" align="left">
          <font face="Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b>&nbsp;Curso</b></font>
       </td>
       <td bgcolor="#000000" align="center">
          <font face="Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><b>Grupo</b></font>
       </td>
    <tr>
    </tr>
    <?
    while ( $query->MoveNext() )
    {
       list ( $ref_curso,
              $curso,
              $seq ) = $query->GetRowValues();
              
       echo("<tr>\n");
       echo("  <td bgcolor=\"#CCCCFF\" align=\"right\">\n");
       echo("    <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#000099\">" . $ref_curso . "&nbsp;</font>\n");
       echo("  </td>\n");
       echo("  <td bgcolor=\"#CCCCFF\" align=\"left\">\n");
       echo("    <font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#000099\">&nbsp;" . $curso . "</font>\n");
       echo("  </td>\n");
       echo("  <td>\n");
       echo("    <input type=\"hidden\" name=\"ref_curso[]\" size=\"8\" value=\"" . $ref_curso . "\">\n");
       echo("    <input type=\"text\"   name=\"seq[]\"   size=\"8\" value=\"" . $seq  . "\">\n");
       echo("  </td>\n");
       echo("</tr>\n");
    }
    ?>
    <tr>
      <td colspan="3" align="center">
        <hr size="1">
      </td>
    </tr>

    <tr>
      <td colspan="3" align="center">
      <div align="left">
      <font name="Verdana" size="3" color="#CC0000"><u><b>Utilização:</b></u><br>
       <p>Crie grupos de cursos preenchendo as caixas de texto com números iguais para cursos que deseja que apareçam próximos. Por exemplo:<br>
        <ul>
         <li>Se desejar que os cursos 16 e 400 apareçam um após o outro, entre com 1 na caixa de texto correspondente a cada um dos dois.</li>
         <li>Se desejar que os cursos 120 e 350 apareçam após os cursos 16 e 400 (que pertencem ao grupo 1), numere-os com 2 nas caixas de texto correspondentes.</li>
        </ul>
       </font>
      </div>
      </td>
    </tr>
    <tr>
      <td align="center" colspan="3">
        <input type="submit" name="submit" value="  Salvar  ">
        <input type="button" name="Button" value="  Voltar  " onClick="javascript:history.go(-1)">
        <input type="hidden" name="ref_periodo" value="<? echo($ref_periodo); ?>">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
