<? require("../lib/common_not_login.php3"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<html>
<head>
<title>Matrícula dos Bixos</title>
<script language="JavaScript">
function _init()
{
  document.myform.aluno_id.focus();
}
</script>

<script language="PHP">
function SQL_Combo($nome,$sql,$default,$onchange)
{
  $conn = new Connection;
  
  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $onchange != "" )
    echo("<select name=\"$nome\" onchange=\"$onchange\">");
  else
    echo("<select name=\"$nome\">");
    
  for ( $i=1; $query->MoveNext(); $i++ )
  {
    list ( $text, $value ) = $query->GetRowValues();
      
    if ( $value == $default )
      echo("  <option value=\"$value\" selected>$text</option>\n");
    else
      echo("  <option value=\"$value\">$text</option>\n");
  }

  echo("</select>");

  $query->Close();

  $conn->Close();
}

</script>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function _busca()
{
  var url = "/generico/post/lista_bixos.php3" +
            "?pnome=" + escape(document.myform.aluno_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');
}

function setResult(id,nome)
{
  document.myform.aluno_id.value = id;
  document.myform.aluno_nome.value = nome;
}

</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20"  onload="_init()">
<form method="post" action="matricula_curso_bixo.phtml" name="myform">
<table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
  <tr> 
    <td colspan="2" height="32" align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><font color="#000000"><b>Início</b> :: Selecione Contrato :: Selecione Disciplinas :: Confirmação :: Finalização</font></font>
    </td>
  </tr>
  <tr bgcolor="#000099"> 
    <td colspan="2" height="32"> 
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF"> Matr&iacute;culas dos Calouros</font></b></font></div>
    </td>
  </tr>
  <tr bgcolor="#CCCCFF"> 
    <td colspan="2" height="32"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099"><b>&nbsp;&nbsp;Identifica&ccedil;&atilde;o Aluno </b></font></td>
  </tr>
  
  <?
  $periodo_id = '2004B';
  ?>
  
  <tr> 
    <td width="35%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
    <td width="65%"> 
      <input type="hidden" name="periodo_id" size="10" value="<?echo($periodo_id);?>">
      <script language="PHP">
      echo("<b>$periodo_id</b>");
      </script>
    </td>
  </tr>
  <tr> 
    <td width="35%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Digite o Código de Aluno:</font></td>
    <td width="65%"> 
      <input type="text" name="aluno_id" size="10" value="<?echo($aluno_id);?>">
    </td>
  </tr>
  <tr> 
    <td colspan="2" align="center"><hr></td>
  </tr>
  <tr> 
    <td colspan="2" align="center"> 
      <input type="submit" name="Submit" value=" Seguir >> ">
    </td>
  </tr>
</table>
</form>
</body>
</html>
