<?
  require("../../../lib/common.php");
  require("../../../lib/properties.php");
  require("../lib/GetPessoaNome.php3");
  require("../lib/CalcValorAtual.php3");

  CheckFormParameters(array('periodo_id','aluno_id'));

  $properties->Set('periodo_id',$periodo_id);
  $properties->Set('aluno_id',$aluno_id);
  $properties->Save();

  // em caso apenas o código da pessoa foi digitado,
  // buscamos o nome do aluno agora
  $aluno_nome = GetPessoaNome($aluno_id,true);
?>
<HTML>
<HEAD>
<script language="JavaScript">
function mostra_cadastro(id)
{
  var url = "pessoaf_edita.phtml?id=" + escape(id);

  window.open(url,'pessoas','resizable=yes, toolbar=no,width=840,height=620,scrollbars=yes');
}

function mostra_disciplinas(id,desc,id_contrato,campus,semestre,turma,ref_periodo_turma)
{
  document.myform.curso_id.value = id;
  document.myform.curso_nome.value = desc;
  document.myform.id_contrato.value = id_contrato;
  document.myform.ref_campus.value = campus;
  document.myform.semestre.value = semestre;
  document.myform.turma.value = turma;
  document.myform.ref_periodo_turma.value = ref_periodo_turma;
  document.myform.submit();
}

function mostra_contrato(id)
{
  var url = "alterar_contrato.phtml?id=" + escape(id); 

  window.open(url,'contratos','resizable=yes, toolbar=no,width=840,height=620,scrollbars=yes');
}
</script>

<script language="PHP">
/************************** Verifica Saldo do Aluno ************************/
  $conn = new Connection;
  $conn->Open();

  $sql = " select fl_Segurado from pessoas where id='$aluno_id'";
  $query = $conn->CreateQuery($sql);
  if ($query->MoveNext())
  { list( $segurado ) = $query->GetRowValues(); }
  $query->Close();

  $sql = " select saldo(A.id), ".
         "        A.dt_vencimento, " .
         "        B.desconto_mes, " .
         "        B.multa_mes, " .
         "        B.multa_pos, " .
         "        B.dias_multa " .
         " from titulos_cr A, origens B ".
         " where A.ref_origem=B.id and " .
         "       A.ref_pessoa='$aluno_id' and " .
         "       saldo(A.id) > 0 and " .
         "       A.dt_vencimento < date(now()) " .
         " order by dt_vencimento desc";

  $query = $conn->CreateQuery($sql);
  
  $ValorTotalAtual = 0;
  
  for ( $i=0; $query->MoveNext(); $i++ )
  {
    list ($saldo_titulo,
          $dt_vencimento,
          $desconto_mes,
          $multa_mes,
          $multa_pos,
          $dias_multa) = $query->GetRowValues();
          
    $vlr_atual = CalcValorAtual($saldo_titulo, $dt_vencimento, $desconto_mes, $multa_pos, $multa_mes, $dias_multa, $dias);
    
    $ValorTotalAtual += $vlr_atual;
  
  }
  
  $conn->Close();

  if (($segurado=='f') && ($ValorTotalAtual>0))
  {
    SaguAssert( (!$ValorTotalAtual), "Aluno $aluno_id (não segurado) com saldo negativo de R$ $ValorTotalAtual!");
  }

/***************************************************************************/
</script>  <title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</HEAD>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<CENTER>
<TABLE width="500" border="0" cellspacing="0" cellpadding="0" height="40">
  
    <tr bgcolor="#000099">
      <TD height="35">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">
        Cursos da Matr&iacute;cula</font></b></font></div>
      </td>
    </tr>
  
</table>
</CENTER>
<br>
<FORM method="post" action="matricula_disciplinas_internet.phtml" name="myform">
<CENTER>
<TABLE width="500" border="0" cellspacing="2" cellpadding="0">
  
    <tr>
      <td colspan="5" height="32" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099"><b>&nbsp;&nbsp;Identifica&ccedil;&atilde;o
        Aluno
        <?/*
           if ($segurado=='f')
           { echo("  (não segurado)"); }
           else
           { echo("  (segurado)"); }*/
        ?>

        </b></font></td>
    </tr>
    <tr>
      <td width="122" bgcolor="#CCCCFF" colspan="2"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td colspan="3"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($periodo_id)?>
        <input type="hidden" name="periodo_id" size="8" value="<?echo($periodo_id)?>">
        </font></td>
    </tr>
    <tr>
      <td width="122" bgcolor="#CCCCFF" colspan="2"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Aluno:</font></td>
      <td colspan="2"> <font face="Arial, Helvetica, sans-serif" size="2"><?echo($aluno_id)?> 
        <?echo($aluno_nome)?> 
        <input type="hidden" name="aluno_id" size="8" value="<?echo($aluno_id)?>">
        <input type="hidden" name="aluno_nome" size="32" value="<?echo($aluno_nome)?>">
        </font></td>
      <td width="97"> 
        <input type=button value="Cadastro..." onClick="mostra_cadastro(<?echo($aluno_id);?>)">
      </td>
    </tr>
    <tr>
      <td colspan="5"> 
        <input type="hidden" name="curso_id">
        <input type="hidden" name="curso_nome">
        <input type="hidden" name="id_contrato">
        <input type="hidden" name="ref_campus">
        <input type="hidden" name="semestre">
        <input type="hidden" name="turma">
        <input type="hidden" name="ref_periodo_turma">
        &nbsp; 
        <input type="hidden" name="first" value="1">
      </td>
    </tr>
    <tr>
      <td colspan="5" height="32" bgcolor="#CCCCFF"><font color="#000099"><b><font face="Arial, Helvetica, sans-serif" size="2">&nbsp;&nbsp;Contratos</font></b></font>
<?
$sql = "select A.ref_campus, A.ref_curso, B.descricao, A.id, A.semestre, A.turma, A.ref_periodo_turma" .
       "  from contratos A, cursos B" .
       "  where A.ref_pessoa = $aluno_id and" .
       "        A.dt_desativacao is null and" .
       "        A.ref_curso = B.id";

$conn = new Connection;
$conn->Open();
$query = $conn->CreateQuery($sql);

while ( $query->MoveNext() )
{
  list ( $campus, $id, $desc, $id_contrato, $semestre, $turma, $ref_periodo_turma ) = $query->GetRowValues();

?></td>
    </tr>
    <tr>
      <td width="90"><font face="Arial, Helvetica, sans-serif" size="2">
        <?echo($turma);?><i>(<?echo($ref_periodo_turma);?>)</i></font>
      </td>
      <td width="61"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($id);?></font></td>
      <td width="337"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($desc);?> 
        </font></td>
      <td width="97"> 
        <input type=button value="Disciplinas..." onClick="mostra_disciplinas(<?echo($id);?>,'<?echo($desc);?>',<?echo($id_contrato);?>,'<?echo($campus);?>','<?echo($semestre)?>','<?echo($turma)?>','<?echo($ref_periodo_turma)?>')">
      </td>
      <td width="97"> 
        <input type="button" value="Contrato..." onClick="mostra_contrato(<?echo($id_contrato);?>)">
      <?
} // while

$query->Close();
$conn->Close();
?>
</td>
    </tr>
</table>
</CENTER>
</form>
<FORM method="post" action="novo_contrato.phtml">
<CENTER>
<TABLE width="500" border="0" cellspacing="2" cellpadding="0">
  
    <tr>
      <td colspan="4">
      <hr size="1">
      </td>
    </tr>
    <tr>
      <td colspan="4" align="center"> 
        <input type="button" value="Outro Aluno" onClick="location='matricula_aluno_internet.phtml'">
        <input type="submit" value="Novo Contrato">
        <input type="hidden" name="id" size="32" value="<?echo($aluno_id)?>">
        <input type="hidden" name="nome" size="8" value="<?echo($aluno_nome)?>">
        <font face="Arial, Helvetica, sans-serif" size="2"> 
        <input type="hidden" name="periodo_id" size="8" value="<?echo($periodo_id)?>">
        <input type="hidden" name="ref_campus" size="8" value="<?echo($ref_campus)?>">
        </font> </td>
    </tr>
</table>
</CENTER>
</form>
<p>&nbsp;</p>
</body>
</HTML>
