<html>
<head>
<title>PHP List</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="PHP">
$count = count($code1);
</script>
</head>

<body bgcolor="#FFFFFF">
<table width="500" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr> 
    <td width="26%" height="91"> 
      <div align="center"><img src="images/logo_ies.gif" width="104" height="94"></div>
    </td>
    <td width="46%" height="91"> 
      <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="3"><b><font size="4" color="#0066CC">Salvar 
        Disciplinas</font><br>
        <font size="2">Sistema Administrativo</font></b></font></div>
    </td>
    <td width="28%" height="91"> 
      <div align="right"><img src="../images/academico.jpg" width="154" height="111"></div>
    </td>
  </tr>
</table>
<br>
<form name="form2" method="post" action="list2.phtml">
  <table width="500" align="center">
    <tr bgcolor="#CCCCFF"> 
      <td colspan="3" height="32"><font face="Arial, Helvetica, sans-serif" size="2" color="#000066"><b>&nbsp;&nbsp;Disciplinas 
        Selecionadas</b></font></td>
    </tr>
    <tr bgcolor="#CCCCCC"> 
      <td width="16">&nbsp;</td>
      <td width="60"><font face="Arial, Helvetica, sans-serif" size="2">C&oacute;digo</font></td>
      <td><font face="Arial, Helvetica, sans-serif" size="2">Curso</font></td>
    </tr>
    <script language="PHP"> 
if ( $count != 0 ) 
{
  for ( $i=0; $i<$count; $i++ )
  {
    if ( $code1[$i] == '' )
      continue;
</script>
    <tr> 
      <td width="16"><img src="../images/redball.gif" width="16" height="16"></td>
      <td width="60"> <font face="Arial, Helvetica, sans-serif" size="2"><?echo($code1[$i]);?></font></td>
      <td> <font face="Arial, Helvetica, sans-serif" size="2"><?echo($desc1[$i]);?></font> 
        <input type="hidden" name="code1[]" size="40" value="<?echo($code1[$i]);?>">
        <input type="hidden" name="desc1[]" size="40" value="<?echo($desc1[$i]);?>">
        <input type="hidden" name="code2[]" size="40" value="<?echo($code2[$i]);?>">
        <input type="hidden" name="desc2[]" size="40" value="<?echo($desc2[$i]);?>">
      </td>
    </tr>
    <script language="PHP"> 
    if ( $code2[$i] != '' )
    {
</script>
    <tr> 
      <td width="16"><img src="../images/yellowball.gif" width="16" height="16"></td>
      <td width="60"><font face="Arial, Helvetica, sans-serif" size="2"><?echo($code2[$i]);?></font></td>
      <td><font face="Arial, Helvetica, sans-serif" size="2"><?echo($desc2[$i]);?></font></td>
    </tr>
    <script language="PHP"> 
     } // if


     // row separator
     if ( $i + 1 < $count )
     {
</script>
    <tr> 
      <td colspan=3> 
        <hr size="1">
      </td>
    </tr>
    <script language="PHP"> 
    } // if
  } // for
} // if

else 
{
</script>
    <tr> 
      <td colspan="3"> 
        <div align="center"><font face="Arial, Helvetica, sans-serif" size="2"><b><font color="#CC0000"><br>
          Nenhuma disciplina selecionada<br>
          &nbsp; </font></b></font></div>
      </td>
    </tr>
    <script language="PHP"> 
} // else
</script>
    <tr bgcolor="#CCCCCC" align="center"> 
      <td colspan="3"> 
        <input type="submit" value="Salvar Disciplinas" name="Submit">
      </td>
    </tr>
  </table>
</form>
<p>&nbsp;</p>
</body>
</html>
