<? require("../../../lib/common.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<? require("../lib/CalcValorAtual.php3");?>
<?

CheckFormParameters(array('periodo_id','curso_id','aluno_id'));

$aluno_nome = GetPessoaNome($aluno_id,true);

?>
<HTML>
<HEAD>

<script language="JavaScript">

function PedeParcelas(curso_id,desc,id_contrato,campus)
{
  var p_m=prompt("Qual o número de parcelas?","10")

  var p_2=prompt("Qual o código do status?","19")
  
  if (p_m == "" || p_m == 0 || p_m < 0 || p_2 == "" || p_2 == 0 || p_2 < 0) 
  { 
     alert("Matricula Cancelada!!!");
  }
  else
  {
     document.myform.curso_id.value = curso_id;
     document.myform.curso_nome.value = desc;
     document.myform.id_contrato.value = id_contrato;
     document.myform.ref_campus.value = campus;
     document.myform.num_parcelas.value = p_m;
     document.myform.cod_status.value = p_2;
     document.myform.submit(); 
  }
}

function altera_contrato(id)
{
   location = 'alterar_contrato.phtml?id=' + escape(id)
}
</script>

<script language="PHP">

  /************************** Verifica Saldo do Aluno ************************/
  $conn = new Connection;
  $conn->Open();
 
  $sql = " select fl_Segurado from pessoas where id='$aluno_id'";
  $query = $conn->CreateQuery($sql);
  if ($query->MoveNext())
  { list( $segurado ) = $query->GetRowValues(); }
  $query->Close();

  $sql = " select saldo(A.id), ".
         "        A.dt_vencimento, " .
         "        B.desconto_mes, " .
         "        B.multa_mes, " .
         "        B.multa_pos, " .
         "        B.dias_multa " .
         " from titulos_cr A, origens B ".
         " where A.ref_origem=B.id and " .
         "       A.ref_pessoa='$aluno_id' and " .
         "       saldo(A.id) > 0 and " .
         "       A.dt_vencimento < date(now()) " .
         " order by dt_vencimento desc";

  $query = $conn->CreateQuery($sql);
  
  $ValorTotalAtual = 0;
  
  for ( $i=0; $query->MoveNext(); $i++ )
  {
    list ($saldo_titulo,
          $dt_vencimento,
          $desconto_mes,
          $multa_mes,
          $multa_pos,
          $dias_multa) = $query->GetRowValues();
          
    $vlr_atual = CalcValorAtual($saldo_titulo, $dt_vencimento, $desconto_mes, $multa_pos, $multa_mes, $dias_multa, $dias);
    
    $ValorTotalAtual += $vlr_atual;
  
  }
  
  $conn->Close();

  if (($segurado=='f') && ($ValorTotalAtual>0))
  {
    SaguAssert( (!$ValorTotalAtual), "Aluno $aluno_id (não segurado) com saldo negativo de R$ $ValorTotalAtual!");
  }

/***************************************************************************/
</script>

<title>Matricula dos Cursos Técnicos</title>
</HEAD>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="efetuar_matricula_tecnico.php3" name="myform">
<TABLE width="90%" border="0" cellspacing="2" cellpadding="0" align="center">   
    <tr bgcolor="#000099">
      <td colspan="5" height="35">
      <div align="center"><font size="3" face="Helvetica"><b><font color="#CCCCFF">Matr&iacute;cula dos Cursos Técnicos</font></b></font></div>
      </td>
    </tr>
    <tr>
      <td colspan="5" height="32" bgcolor="#CCCCFF"><font face="Helvetica" size="2" color="#000099"><b>&nbsp;&nbsp;Identifica&ccedil;&atilde;o Aluno
        <?
         if ($segurado=='f')
         { echo("  (não segurado)"); }
         else
         { echo("  (segurado)"); }
        ?>
        </b></font></td>
    </tr>
    <tr>
      <td width="122" bgcolor="#CCCCFF" colspan="2"><font face="Helvetica" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td colspan="3"><font face="Helvetica" size="2" color="#0000cc"><?echo($periodo_id)?>
        <input type="hidden" name="periodo_id" size="8" value="<?echo($periodo_id)?>"></font>
      </td>
    </tr>
    <tr>
      <td width="122" bgcolor="#CCCCFF" colspan="2"><font face="Helvetica" size="2" color="#000099">&nbsp;&nbsp;Aluno:</font>
      </td>
      <td colspan="3"> <font face="Helvetica" size="2" color="#0000cc"><?echo($aluno_id)?> 
        <input type="hidden" name="aluno_id" size="8" value="<?echo($aluno_id)?>">
        <input type="hidden" name="aluno_nome" size="32" value="<?echo($aluno_nome)?>">
        <?echo($aluno_nome)?></font>
      </td>
    </tr>
    <tr>
      <td colspan="5" align="center"> 
        <font size="2" face="Helvetica"><input type="hidden" name="curso_id" size="8"></font>
        <font size="2" face="Helvetica"><input type="hidden" name="curso_nome" size="32"></font>
        <font size="2" face="Helvetica"><input type="hidden" name="id_contrato" size="32"></font>
        <font size="2" face="Helvetica"><input type="hidden" name="ref_campus" size="32"></font>
    	<font size="2" face="Helvetica"><input type="hidden" name="num_parcelas"></font>
    	<font size="2" face="Helvetica"><input type="hidden" name="cod_status"></font>
      </td>
    </tr>
    <tr>
      <td colspan="5" height="32" bgcolor="#CCCCFF"><font color="#000099" size="2" face="Helvetica"><b>&nbsp;&nbsp;Contratos</b></font><font size="2" face="Helvetica">
<script language="PHP">
       $sql = "select A.ref_campus, " .
              "       A.ref_curso, " .
    	      "       B.descricao, " .
    	      "       A.id" .
              "  from contratos A, cursos B " .
              "  where A.ref_curso = B.id and " .
              "        A.ref_pessoa = '$aluno_id' and" .
              "        A.ref_curso = '$curso_id' and" .
              "        A.dt_desativacao is null and " .
              "        B.agrupo_curso = '1'"; // Curso que foram cadastrados com a opção de agrupar disciplinas
	      
       $conn = new Connection;
       $conn->Open();
       $query = $conn->CreateQuery($sql);
 
       while ( $query->MoveNext() )
       {
          list ($ref_campus, 
    	        $curso_id, 
        		$desc, 
        		$id_contrato ) = $query->GetRowValues();
 
</script>
</font>
    </td>
    </tr>
    <tr>
      <td width="61"><font face="Helvetica" size="2" color="#000000"><?echo($id_contrato);?></font></td>
      <td width="61"><font face="Helvetica" size="2" color="#000000"><?echo($curso_id);?></font></td>
      <td width="150"><font face="Helvetica" size="2" color="#000000"><?echo($desc);?> 
        </font></td>
      <td width="150" colspan="2"> 
        <font size="2" face="Helvetica">
        <input type="button" value="Efetuar Matricula" onClick="PedeParcelas(<?echo($curso_id);?>,'<?echo($desc);?>',<?echo($id_contrato);?>,<?echo($ref_campus);?>)"></font>
        <font size="2" face="Helvetica" color="#000000">
    	<input type="button" value="Altera Contrato" onclick="javascript:altera_contrato('<? echo $id_contrato ?>')">
      <script language="PHP">

} // while

$query->Close();
$conn->Close();
</script>
</font>
</td>
    </tr>
</table>
</form>
<form method="post" action="novo_contrato.phtml">
<TABLE width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
  
    <tr>
      <td colspan="4">
      <hr size="1">
      </td>
    </tr>
    <tr>
      <td colspan="4" align="center"> 
        <font color="#000000" size="2" face="Helvetica"><input type="button" value="Outro Aluno" onClick="location='matricula_aluno_tecnico.phtml'"></font>
        <input type="hidden" name="id" size="32" value="<?echo($aluno_id)?>">
        <input type="hidden" name="nome" size="8" value="<?echo($aluno_nome)?>">
        <font color="#000000" size="2" face="Helvetica"><input type="submit" value="Novo Contrato"></font>
      </td>
    </tr>
</table>
</form>
</body>
</HTML>
