<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<html>
<head>
<script language="JavaScript">
function _init()
{
    document.myform.descricao.focus();
}
</script>

<script language="PHP">

$conn = new Connection;

$conn->Open();

$sql = "select id," .
       "       ref_periodo," .
       "       texto," .
       "       fonte," .
       "       tamanho," .
       "       sequencia," .
       "       ref_status," .
       "       fl_ouvinte" .
       "  from mensagens where id = '$id' and ref_periodo = '$ref_periodo'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $ref_periodo,
       $texto,
       $fonte,
       $tamanho,
       $sequencia,
       $ref_status,
       $fl_ouvinte) = $query->GetRowValues();

$query->Close();

$conn->Close();

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/mensagens_altera.php3" name="myform">
  <table width="90%" align="center">
    <tr bgcolor="#000099"> 
      <td height="35" colspan="2"> 
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Altera&ccedil;&atilde;o de Mensagens</font></b></font><font size="4" face="Verdana, Arial, Helvetica, sans-serif"><b></b></font></div>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo</font></td>
      <td> <font face="Verdana, Arial, Helvetica, sans-serif" color="#FF0033"> 
        <input type="hidden" name="id" value="<? echo($id); ?>">
        <?php echo($id); ?> </font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Periodo</font></td>
      <td> <font face="Verdana, Arial, Helvetica, sans-serif" color="#FF0033"> 
        <input type="hidden" name="ref_periodo" value="<? echo($ref_periodo); ?>">
        <?php echo($ref_periodo); ?> </font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Mensagem&nbsp;</font></td>
      <td> 
        <textarea name="texto" cols="50" rows="4"><?echo($texto);?></textarea>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Fonte&nbsp;</font></td>
      <td>
        <select name="fonte">
          <option selected><?echo($fontes[$fonte]); ?></option>
          <option value="P">Padrão</option>
          <option value="N">Negrito</option>
          <option value="I">Itálico</option>
        </select>
      </td>
    </tr> 
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Número de caracteres<br>&nbsp;por linha</font></td>
      <td>
        <input name="tamanho" type=text value="<?echo($tamanho);?>" size="5">
      </td>
    </tr>

    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Seqüência<br>&nbsp;(1,2,3 ...)</font></td>
      <td>
        <input name="sequencia" type=text value="<?echo($sequencia);?>" size="5">
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Status&nbsp;</font></td>
      <td>
        <select name="ref_status">
          <option selected><?echo($status_aluno[$ref_status]); ?></option>
          <option value="G">Graduacao</option>
          <option value="C">Calouro</option>
          <option value="O">Outros</option>
        </select>
      </td>
    </tr> 
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;É Ouvinte&nbsp;</font></td>
      <td>
        <select name="fl_ouvinte">
          <option selected><?echo($opcoes[$fl_ouvinte]); ?></option>
          <option value="t">Sim</option>
          <option value="f">Não</option>
        </select>
      </td>
    </tr> 
    <tr> 
      <td colspan="2"><hr></td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit" value=" Salvar ">
        <input type="button" name="Button" value=" Voltar " onClick="location='cadastra_mensagens.phtml'">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
