<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? $op_opcoes = SQLArray("select descricao, id from tipos_motivos order by descricao"); ?>
<html>
<head>
<script language="JavaScript">
function _init()
{
  document.myform.descricao.focus();
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_tipo_motivo);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
<script language="PHP">
function Mostra_Motivos()
{

  $conn = new Connection;

  $conn->Open();

  $sql= " select id, " .
        "        descricao, " .
        "        get_tipo_motivo(ref_tipo_motivo) " .
        " from motivos " .
        " order by descricao";

  $query = $conn->CreateQuery($sql);

  $n = $query->GetColumnCount();

  echo("<center><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

  $i=1;

  // cores fundo
  $bg0 = "#000000";
  $bg1 = "#EEEEFF";
  $bg2 = "#FFFFEE";

  // cores fonte
  $fg0 = "#FFFFFF";
  $fg1 = "#000099";
  $fg2 = "#000099";
  
  while( $query->MoveNext() )
  {
    list ($id,
          $motivo,
          $tipo_motivo) = $query->GetRowValues();

    $href  = "<a href=\"motivos_altera.phtml?id=$id\"><img src=\"../images/update.gif\" title='Alterar Motivo' align='absmiddle' border=0></a>";
    $href1 = "<a href=\"javascript:Confirma_Exclui($id)\"><img src=\"../images/delete.gif\" title='Excluir Motivo' align='absmiddle' border=0></a>";

    if ($i == 1)
    {
      echo("<tr bgcolor=\"#000000\">\n");
      echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
      echo ("<td width=\"60%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Descrição do Motivo</b></font></td>");
      echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Tipo</b></font></td>");
      echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;</b></font></td>");
      echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;</b></font></td>");
      echo("  </tr>"); 
    }

    if ( $i % 2)
    {
       echo("<tr bgcolor=\"$bg1\">\n");
       echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$id</td>");
       echo ("<td width=\"60%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$motivo</td>");
       echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$tipo_motivo</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href1</td>");
       echo("  </tr>");

    }
    else
    {
       echo("<tr bgcolor=\"$bg2\">\n");
       echo ("<td width=\"10%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$id</td>");
       echo ("<td width=\"60%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$motivo</td>");
       echo ("<td width=\"20%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$tipo_motivo</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href1</td>");
       echo("  </tr>");
    }

    $i++;

  }

  echo("</table></center>");

  $query->Close();

  $conn->Close();
}


Function Exclui_Motivo($arg)
{
$conn = new Connection;

$conn->Open();

$sql = "delete from motivos where id='$arg';";

$ok = $conn->Execute($sql);  // tire o @ para visualizar mensagens de error do sistema DB

$conn->Close();

SaguAssert($ok,"Não foi possível de excluir o registro!");

}
</script>
<script language="JavaScript">
function Confirma_Exclui(arg1)
{
  url = 'post/motivos_exclui.php3?id=' + arg1;

  if (confirm("Você tem certeza que deseja excluir o motivo: "+arg1))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/motivos.php3" name="myform">
<table width="90%" align="center">
  <tr bgcolor="#000099"> 
    <td height="35" colspan="2"> 
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Motivos</font></b></font></div>
    </td>
  </tr>
  <tr> 
    <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descri&ccedil;&atilde;o</font></td>
    <td> 
      <input name="descricao" type=text size="35">
    </td>
  </tr>
  <tr>
    <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Tipo de Motivo</font></td>
    <td>
       <input name="ref_tipo_motivo" type=text size="7">
       <script language="PHP">ComboArray("op",$op_opcoes,"0","ChangeOp()");</script>
    </font></td>
  </tr>
  <tr> 
    <td colspan="2"> 
      <hr size="1">
    </td>
  </tr>
  <tr> 
    <td height="33" colspan="2"> 
      <div align="center"> 
        <input type="submit" name="Submit"  value="  Incluir  ">
        <input type="reset"  name="Submit2" value="  Limpar  ">
        <input type="button" name="Button2" value="   Sair   " onClick="javascript:history.go(-1)">
      </div>
    </td>
  </tr>
  <tr>
    <td height="13" colspan="2">
      <hr size="1">
    </td>
  </tr>
  <tr> 
    <td height="33" colspan="2"> 
      <div align="center">
        <?PHP Mostra_Motivos(); ?>
      </div>
    </td>
  </tr>
</table>
</form>
</body>
</html>
