<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Digitação de Notas</title>

<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $periodo_id == '' )
{
  list ( $periodo_id ) = QueryExecute($sql_periodos_academico);
  $periodo_id = trim(substr($periodo_id, 0, strpos($periodo_id, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

$sql = " select distinct A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A ";
      // " where " .
      // "       B.ref_last_periodo = '$periodo_id' " .
      // "       and B.ref_curso = A.id' " .
      // " order by A.id;" ;
/*
$sql = " select distinct A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, contratos B ".
       " where " .
       "       B.ref_last_periodo = '$periodo_id' " .
       "       and B.ref_curso = A.id' " .
       " order by A.id;" ;
*/
$op_result1 = SQLArray($sql);

</script>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);

  document.myform.action = 'notas.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.curso_id);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'periodo_id')
      {
        document.myform.action = 'notas.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="notas_disc.phtml" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Cadastro de Notas</b></font></td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="periodo_id" size="8" onChange="ChangeCode('periodo_id','op')" value="<?echo($periodo_id);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099"> 
        &nbsp; Curso:</font></td>
      <td width="296"> <font color="#000000"> </font> 
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td>
              <input type="text" name="curso_id" onChange="ChangeCode('curso_id','op1')" size="8">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op1",$op_result1,$curso_id,"ChangeOp1()");
              </script>
              </font></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
        <td colspan="2" align="center"><hr></td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"  value=" Prosseguir ">
        <input type="button" name="Button2" value="    Sair    " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
