<? header("Cache-Control: no-cache"); ?>
<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<html>
<head>
<title>Material de Matrícula</title>

<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $periodo_id == '' )
{
  list ( $periodo_id ) = QueryExecute($sql_periodos_academico);
  $periodo_id = trim(substr($periodo_id, 0, strpos($periodo_id, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

$sql = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$periodo_id' " .
       " order by A.id;" ;

$op_result1 = SQLArray($sql);

$sql   = "select id||' / '||nome_campus as d,id from campus order by d";
$op_result2 = SQLArray($sql);

$sql = "select id || ' - ' || descricao,id from aux_bolsas where ativo is true";
$op_result3 = SQLArray($sql);

</script>

<script language="JavaScript">

function buscaPessoa()
{
  var url = '../generico/post/lista_pessoas.php3' +
            '?pnome=' + escape(document.myform.nome_aluno.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2)
{
   document.myform.id_aluno.value = arg1;
   document.myform.nome_aluno.value = arg2;
}

function acao(cod_acao)
{
  if (cod_acao == 'g') 
  {
    var aluno = document.myform.id_aluno.value;
    var curso = document.myform.curso_id.value;
    var periodo = document.myform.periodo_id.value;

    if (aluno)
    {
        if (confirm("Você tem certeza que deseja gerar o material de matrícula para o aluno "+ aluno +" do curso "+ curso +" no período "+ periodo +"?\n\nOBS.: Caso tenha sido feito alguma liberação de pré-requisito para este aluno, esta informação será perdida."))
        {
            var NOVAWIN = window.open("/aguarde.html", "NOVAWIN", "status=no,toolbar=no,location=no,menu=no,scrollbars=no,width=260,height=105,left=280,top=235");
            window.document.myform.action="possibilidades_matricula.php3";
        }
        else
        {
            alert("Geração Cancelada.");
        }
    }
    else
    {
        if (confirm("Você tem certeza que deseja gerar o material de matrícula para TODOS OS ALUNOS do curso "+ curso +" no período "+ periodo +"? No entanto, se foi feito alguma liberação de pré-requisito, esta informação será perdida após gerar o material.\n\nOBS.: Caso queira gerar o material para somente um aluno deste curso, preencha o campo Aluno."))
        {
            var NOVAWIN = window.open("/aguarde.html", "NOVAWIN", "status=no,toolbar=no,location=no,menu=no,scrollbars=no,width=260,height=105,left=280,top=235");
            window.document.myform.action="possibilidades_matricula.php3";
        }
        else
        {
            alert("Geração Cancelada.");
        }
    }
  }

  if (cod_acao == 'p') 
  {
    window.document.myform.action = "possibilidades_matricula_lista.php3";
  }

  if (cod_acao == 'm') 
  {
    var NOVAWIN = window.open("/aguarde.html", "NOVAWIN", "status=no,toolbar=no,location=no,menu=no,scrollbars=no,width=260,height=105,left=280,top=235");
    window.document.myform.action = "/relat/material_matricula.php3";
  }
}

function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )

    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.periodo_id);
  document.myform.action = 'possibilidades_matricula.phtml';
  document.myform.submit();
    
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.curso_id);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.campus_id);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.ref_tipo_bolsa);
  document.myform.curso_id.value = null;
  document.myform.campus_id.value = null;
  document.myform.id_aluno.value = null;
  document.myform.nome_aluno.value = null;
  alert('Material de Matrícula para alunos \ncom a Bolsa Selecionada...');

}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'periodo_id')
      {
        document.myform.action = 'possibilidades_matricula.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

</script>

</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<DIV align="right">
<form name="myform">
<CENTER>
<TABLE width="95%" border="0" cellspacing="2" cellpadding="0">
    <tr>
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Possibilidades e Material de Matrícula</b></font></td>
    </tr>
    <tr>
      <td width="20%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Per&iacute;odo:</font></td>
      <td width="80%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="periodo_id" size="8" onChange="ChangeCode('periodo_id','op')" value="<?echo($periodo_id);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
                 ComboArray("op",$op_result,$periodo_id,"ChangeOp()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td width="20%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Curso:</font></td>
      <td width="80%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="curso_id" onChange="ChangeCode('curso_id','op1')" size="8">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
        		ComboArray("op1",$op_result1,$curso_id,"ChangeOp1()");
	          </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    <tr>
      <TD width="20%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Campus:</font></td>
      <td width="80%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="campus_id" size="8" onChange="ChangeCode('campus_id','op2')" value="">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
        		ComboArray("op2",$op_result2,$campus_id,"ChangeOp2()");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>
    

    <tr>
      <TD width="20%" bgcolor="#CCCCFF"><font face="Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;&nbsp;Alunos:</font></td>
      <TD width="80%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
       <td>
      	<INPUT type="radio" name="bixo" value="nao" checked>Graduação&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="bixo" value="sim" onClick="Javascript:alert('AVISO! \nVocê está tentando Gerar ou Imprimir o Material de Matrícula para calouros.\nPara isso ser possível, informe o código do Vestibular no campo Período. \nAlém disso escolha ao lado a opção pela qual o candidato aprovou.')">Calouros&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="bixo" value="outros" onClick="Javascript:alert('AVISO! \nEste botão gera o material de matricula para Reingressos, Transferências, Portador de Diploma ...')">Outros
       </td>
       <td>
      	<INPUT type="radio" name="opcao" value="1" checked>1ª Opção&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="opcao" value="2">2ª Opção&nbsp;&nbsp;&nbsp;&nbsp;
      	<INPUT type="radio" name="opcao" value="3">3ª Opção
       </td>
      </tr>
      </table> 
    </TD>
    </tr>
</table>
<script language="PHP">
$ref_periodo = $periodo_id;
</script>
</CENTER>
<CENTER>
<TABLE>
  <TBODY>
    <TR>
      <TD><INPUT type="submit" name="Submit" value="Gerar Arquivo de Informações" onclick="javascript:acao('g')"></TD>
      <TD><INPUT type="submit" name="possibilidade" value="Ver Possibilidades" onclick="javascript:acao('p')"></TD>
      <TD><INPUT type="submit" name="material" value="Material de Matrícula" onclick="javascript:acao('m')"></TD>
      <TD><INPUT type="button" name="sair" value="   Sair   " onClick="javascript:history.go(-1)"></TD>

    </TR>
  </TBODY>
</TABLE>
</CENTER>
<center>
<INPUT type="checkbox" name="doc" value="1" unchecked> Verificar Documentos &nbsp;&nbsp;&nbsp;
<INPUT type="checkbox" name="formandos" value="1" unchecked onClick="Javascript:alert('AVISO! \nSe você marcar esta opção, digite no campo \nNúmero de Créditos Limite Formandos o limite \nde créditos para imprimir mensagens \npara formandos.')"> Mensagem Formandos &nbsp;&nbsp;&nbsp;
Número de Créditos Limite Formandos:&nbsp;<INPUT size="4" type="text" name="num_creditos"><br><br>
</center>
<CENTER>
<TABLE width="95%">
    <tr> 
      <TD><FONT face="Arial, Helvetica, sans-serif" size="2">Tipo de Incentivo:</FONT></TD>
      <td width="80%">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td> 
              <input type="text" name="ref_tipo_bolsa" size="6" onChange="ChangeCode('ref_tipo_bolsa','op3')">
            </td>
            <td>&nbsp;</td>
            <td width="100%"><font color="#000000"> 
              <script language="PHP">
        		ComboArray("op3",$op_result3,$ref_tipo_bolsa,"ChangeOp3()");
                echo("&nbsp;&nbsp;Não Obrigatório");
              </script>
              </font></td>
          </tr>
      </table>
      </td>
    </tr>

  
    <TR>
      <TD><FONT face="Arial, Helvetica, sans-serif" size="2">Descrição do Período:</FONT></TD>
      <script language="PHP">
      $month = date("n");
      $year  = date("Y");
      // Dados fornecidos pela Néri
      // Janeiro a Junho  - O Material de Matrícula é impresso entre os meses 4 e 8
      // Julho a Dezembro - O Material de Matrícula é impresso entre os meses 9 e 3
      if (($month > 3) && ($month < 9))
      {
        $mensagem = "julho/$year a dezembro/$year";
      }
      else
      {
        if ($month >= 9)
	{
	    $year = $year + 1;
	}
        $mensagem = "janeiro/$year a junho/$year";
      }
      </script>
      
      <TD width="80%"><INPUT size="40" type="text" name="descr_periodo" value="<? echo($mensagem); ?>"></TD>
    </TR>
    <TR>
      <TD><FONT size="2" face="Helvetica">Aluno:</FONT></TD>
      <TD width="80%">
         <INPUT size="6" type="text" name="id_aluno" value="<?echo($id_aluno)?>">
         <input size="33" type="text" name="nome_aluno" value="<?echo($nome_aluno)?>">
         <input type="button" value="..." onClick="buscaPessoa()" name="button">
      </TD>
    </TR>
</TABLE>
</CENTER>
</form>
</DIV>
</body>

</html>

