<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../../../lib/properties.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
$op_result2 = SQLArray("select id||' - '||nome_campus as d,id from campus order by d");
$op_result3 = SQLArray("select id || '  ' || substr(descricao,1,35),id from motivos order by id");
$op_result4 = SQLArray("select id,id from vestibular order by dt_ordem desc");

?>
<html>
<head>
<title>Registro Acadêmico</title>
<script language="PHP">
function QueryExecute($sql)
{
  $conn = new Connection;

  $conn->Open();

  $query = $conn->CreateQuery($sql);

  if ( $query->MoveNext() )
    $obj = $query->GetRowValues();

  $query->Close();

  $conn->Close();

  return $obj;
}

if ( $ref_periodo == '' )
{
  list ( $ref_periodo ) = QueryExecute($sql_periodos_academico);
  $ref_periodo = trim(substr($ref_periodo, 0, strpos($ref_periodo, "/")));
}
$op_result = SQLArray($sql_periodos_academico);

$sql = " select A.id||' / '||A.abreviatura as d, " .
       "        A.id " .
       " from cursos A, precos_curso B " .
       " where A.id = B.ref_curso and " .
       "       B.ref_periodo = '$ref_periodo' " .
       " order by A.id;" ;

$op_result1 = SQLArray($sql);

</script>

</script>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp()
{
  ChangeOption(document.myform.op,document.myform.ref_periodo);

  document.myform.action = 'registro_academico.phtml';
  document.myform.submit();
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_campus);
}

function ChangeOp3()
{
  ChangeOption(document.myform.op3,document.myform.ref_motivo);
}

function ChangeOp4()
{
  ChangeOption(document.myform.op4,document.myform.ref_vestibular);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      if (fld_name == 'ref_periodo')
      {
        document.myform.action = 'registro_academico.phtml';
        document.myform.submit();
      }
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function BuscaPessoa()
{
  var url = "/generico/post/lista_pessoas.php3" +
            "?pnome=" + escape(document.myform.pessoa_nome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=530,height=350,scrollbars=yes');

}

function setResult(id,nome)
{
  document.myform.ref_pessoa.value = id;
  document.myform.pessoa_nome.value = nome;
}

</script>
</head>

<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="../relat/registro_academico.php3" name="myform">
  <table width="90%" border="0" cellspacing="2" cellpadding="0" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Impressão da capa do Registro Acadêmico dos Alunos por Curso</b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Per&iacute;odo:</font></td>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_periodo" onChange="ChangeCode('ref_periodo','op')" size="8" value="<?echo($ref_periodo)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%">
              <script language="PHP">
                ComboArray("op",$op_result,$ref_periodo,"ChangeOp()");
              </script>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Curso:</font></td>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_curso" onChange="ChangeCode('ref_curso','op1')" size="8" value="<?echo($ref_curso)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%">
              <script language="PHP">
                ComboArray("op1",$op_result1,$ref_curso,"ChangeOp1()");
              </script>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <TD bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Campus:</font></td>
      <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
              <input type="text" name="ref_campus" onChange="ChangeCode('ref_campus','op2')" size="8" value="<?echo($ref_campus)?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%">
              <script language="PHP">
                ComboArray("op2",$op_result2,$ref_campus,"ChangeOp2()");
              </script>
            </td>
          </tr>
      </table>
      </td>
    </tr>    
    <tr>
      <td bgcolor="#CCCCFF" width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
      <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td colspan="3">
              <input type="text" name="ref_pessoa" size="8" value="<?echo($ref_pessoa);?>">
              <input type="text" name="pessoa_nome" size="40" value="<?echo($pessoa_nome);?>">
              <input type="button" value="..." onClick="BuscaPessoa()" name="button">
           </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF" width="119"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Motivo</font></td>
      <td width="377">
        <table width="100%%" border="0" cellspacing="0" cellpadding="0">
          <tr>
           <td colspan="2">
           <input name="ref_motivo" type="text" onChange="ChangeCode('ref_motivo','op3')" size="8" maxlength="8" value="<?echo($ref_motivo);?>">
	       <script language="PHP">
               ComboArray("op3",$op_result3,$motivo,"ChangeOp3()");
           </script>
           </td>
          </tr>
        </table>
      </td>
    </tr>
   
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Tipo de Curso</font></td>
      <td>
        <INPUT type="radio" name="tipo_curso" value="1" checked>Cursos de Graduação&nbsp;&nbsp;&nbsp;&nbsp;
        <INPUT type="radio" name="tipo_curso" value="2">Cursos Técnicos&nbsp;&nbsp;&nbsp;&nbsp;
      </td>
    </tr>
    <tr>
      <TD bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Situação Alunos</font></td>
      <TD>
        <INPUT type="radio" name="situacao" value="veteranos" onClick="alert('Clicando neste botao você imprimirá as capas dos registros \nacadêmicos de todos os alunos do curso e campus selecionados\n que estão efetivamente matriculados no período selecionado, exceto \nos calouros do vestibular selecionado.')">Veteranos&nbsp;&nbsp;&nbsp;&nbsp;
        <INPUT type="radio" name="situacao" value="calouros" onClick="alert('Clicando neste botao você imprimirá as capas dos registros \nacadêmicos de todos os calouros do curso, campus, período e vestibular \nselecionados. Para esta opção, é necessário selecionar um motivo.')">Calouros&nbsp;&nbsp;&nbsp;&nbsp;
        <INPUT type="radio" name="situacao" value="trancados" onClick="alert('Clicando neste botao você imprimirá as capas dos registros \nacadêmicos de todos os alunos do curso selecionado que\nestão com contrato fechado.')">Trancados
      </TD>
    </tr>
    <tr> 
      <td width="81" bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000099">&nbsp;Vestibular:</font></td>
      <td width="296">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td> 
              <input type="text" name="ref_vestibular" size="8"  onChange="ChangeCode('ref_vestibular','op4')" value="<?echo($ref_vestibular);?>">
            </td>
            <td>&nbsp;</td>
            <td width="100%">
              <script language="PHP">
	        	ComboArray("op4",$op_result4,$ref_vestibular,"ChangeOp4()");
	          </script>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <hr>
      </td>
    </tr>
    <tr>
      <td colspan="2" align="center">
        <input type="submit" name="Submit"  value=" Imprimir ">
        <input type="button" name="limpar"  value="  Limpar  ">
        <input type="button" name="Button2" value="   Sair   " onClick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
