<? require("../../../../lib/common.php"); ?>
<? require("../../lib/vestibular/common.php3"); ?>

<html>
<head>
<script language="PHP">
CheckFormParameters(array(
                          "cobr_ref_folha_titular",
                          "cobr_bairro",
                          "cobr_cidade",
                          "cobr_rua",
                          "cobr_cep",
                          "cobr_complemento",
                          "cobr_banco",
                          "cobr_agencia",
                          "cobr_conta",
                          "cobr_identificador",
                          "cobr_dia",
                          "cobr_mes",
                          "cobr_ano"));

$cobr_dt_autorizacao = sprintf("%02d-%02d-%4d",$cobr_dia,$cobr_mes,$cobr_ano);

if ( $cobr_folha_debito == "yes" )
{
  $folha_debito    = "SIM";
  $cobr_folha_debito = '1';
}
  
else
{
  $folha_debito    = "NAO";
  $cobr_folha_debito = '0';
}


list ( $nome_pessoa, $tmp1, $tmp2 ) = GetPessoaNome($cobr_ref_folha_titular,true);
</script>
</head>
<body bgcolor="#FFFFFF">
<table border="0" width="500" align="center" cellspacing="2" cellpadding="0">
  <tr bgcolor="#FFFFFF">
    <td width="27%">
      <div align="center"><img src="images/logo_ies.gif" width="104" height="94"></div>
    </td>
    <td width="73%">
      <div align="center"><font size="4" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#000099">Confirma&ccedil;&atilde;o 
        de Opera&ccedil;&atilde;o</font></b></font></div>
    </td>
  </tr>
</table>
<br>
<form method="post" action="cobranca_inclui.php3" name="myform">
  <table cols=2 width="500" align="center">
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">D&eacute;bito 
        em Folha</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">
echo($folha_debito);
</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Titular 
        da Folha (ref)</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">
echo($cobr_ref_folha_titular . "  " . $nome_pessoa);
</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Bairro 
        de Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_bairro);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Cidade 
        de Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_cidade);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Rua 
        de Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_rua);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">CEP 
        de Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_cep);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Complemento 
        da Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_complemento);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Banco 
        de Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_banco);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Ag&ecirc;ncia 
        da Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_agencia);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Conta 
        da Cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_conta);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Identificador 
        da cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">echo($cobr_identificador);</script>
        </b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="42%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">Dt 
        autoriza&ccedil;&atilde;o cobran&ccedil;a</font></td>
      <td bgcolor="#FFFFFF" width="58%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C"><b> 
        <script language="PHP">
echo($cobr_dt_autorizacao);
</script>
        </b></font></td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td width="42%"> 
        <input type="hidden" name="id" value="<?echo($id);?>">
        <input type="hidden" name="cobr_folha_debito" value="<?echo($cobr_folha_debito);?>">
        <input type="hidden" name="cobr_ref_folha_titular" value="<?echo($cobr_ref_folha_titular);?>">
        <input type="hidden" name="cobr_bairro" value="<?echo($cobr_bairro);?>">
        <input type="hidden" name="cobr_cidade" value="<?echo($cobr_cidade);?>">
        <input type="hidden" name="cobr_rua" value="<?echo($cobr_rua);?>">
        <input type="hidden" name="cobr_cep" value="<?echo($cobr_cep);?>">
        <input type="hidden" name="cobr_complemento" value="<?echo($cobr_complemento);?>">
        <input type="hidden" name="cobr_banco" value="<?echo($cobr_banco);?>">
        <input type="hidden" name="cobr_agencia" value="<?echo($cobr_agencia);?>">
        <input type="hidden" name="cobr_conta" value="<?echo($cobr_conta);?>">
        <input type="hidden" name="cobr_identificador" value="<?echo($cobr_identificador);?>">
        <input type="hidden" name="cobr_dt_autorizacao" value="<?echo($cobr_dt_autorizacao);?>">
        &nbsp;</td>
      <td width="58%"> 
        <input type="submit" name="Submit" value="Incluir">
        <input type="reset" name="Submit2" value="Corrigir">
      </td>
    </tr>
  </table>
</form>
<p>&nbsp;</p></body>
</html>
