<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
   $op1_opcoes = SQLArray($sql_periodos_academico);
   $op2_opcoes = SQLArray("select nome, id from turnos order by nome");
?>

<html>
<head>

<script language="Javascript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_periodo);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.ref_turno);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>


<script language="PHP">
CheckFormParameters(array("id"));

$conn = new Connection;

$conn->Open();

$sql = " select " .
       "    id," .
       "    descricao, " .
       "    turno," .
       "    hora_ini," .
       "    hora_fim, " .
       "    to_char(dt_inicial, 'dd-mm'), " .
       "    to_char(dt_final, 'dd-mm'), " .
       "    hora_aula_dia, " .
       "    num_encontros_minimo, " .
       "    ref_periodo " .
       " from horarios " .
       " where id = '$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $descricao,
       $ref_turno,
       $hora_ini,
       $hora_fim,
       $dt_inicial,
       $dt_final,
       $hora_aula_dia,
       $num_encontros_minimo,
       $ref_periodo) = $query->GetRowValues();

$query->Close();
$conn->Close();

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/altera_horario.php3" name="myform">
  <table border="0" width="90%" align="center" cellspacing="2" height="40" align="center">
    <tr bgcolor="#000099" align "center">
      <td height="35" colspan="2" align="center">
        <font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Altera&ccedil;&atilde;o de Horário</font></b></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo&nbsp;</font></td>
      <td> <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><? echo($id); ?>
        <input type="hidden" name="id" value="<? echo($id); ?>">
        </font></td>
    </tr> 
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo 
        </font>
      </td>
      <td width="80%"> 
        <input name="ref_periodo" type=text size="7" onChange="ChangeCode('ref_periodo','op1')" value="<?echo($ref_periodo)?>">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op1",$op1_opcoes,$ref_periodo,"ChangeOp1()");</script>
        </font>
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Descricao</font></td>
      <td> 
        <input name="descricao" type=text size="40" value="<? echo($descricao); ?>">
      </td>
    </tr>

     <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Turno</font>
      </td>
      <td width="70%"> 
        <input name="ref_turno" type=text size="6" value="<? echo($ref_turno); ?>" onChange="ChangeCode('ref_turno','op2')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op2",$op2_opcoes,$ref_turno,"ChangeOp2()");</script>
        </font>
      </td>
    </tr>
   
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Hora Inicial<br>&nbsp;(hh:mm:ss)</font></td>
      <td> 
        <input name="hora_ini" value="<? echo($hora_ini); ?>" type=text size="8" maxlength="8">
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Hora Final<br>&nbsp;(hh:mm:ss)</font></td>
      <td> 
        <input name="hora_fim" type=text value="<? echo($hora_fim); ?>" size="8" maxlength="8">
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Inicial<br>&nbsp;(dd-mm)</font></td>
      <td> 
        <input name="dt_inicial" type=text value="<? echo($dt_inicial); ?>" size="8" maxlength="5">
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Final<br>&nbsp;(dd-mm)</font></td>
      <td> 
        <input name="dt_final" type=text value="<? echo($dt_final); ?>" size="8" maxlength="5">
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Horas Aula Dia</font></td>
      <td> 
        <input name="hora_aula_dia" type=text value="<? echo($hora_aula_dia); ?>" size="5" maxlength="5">
      </td>
    </tr>

    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Número mínimo de encontros por semestre</font></td>
      <td> 
        <input name="num_encontros_minimo" type=text value="<? echo($num_encontros_minimo); ?>" size="5" maxlength="5">
      </td>
    </tr>

    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td align="center" colspan="2"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="button" name="Submit2" value=" Voltar " onclick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
