<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<?
   $op1_opcoes = SQLArray($sql_periodos_academico);
   $op2_opcoes = SQLArray("select nome, id from dias order by nome");
?>

<html>
<head>

<script language="Javascript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_periodo);
}

function ChangeOp2()
{
  ChangeOption(document.myform.op2,document.myform.dia_semana);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>


<script language="PHP">
CheckFormParameters(array("id"));

$conn = new Connection;

$conn->Open();

$sql = " select " .
       "    id," .
       "    ref_periodo, " .
       "    dia_semana, " .
       "    to_char(data_aula, 'dd-mm-yyyy') " .
       " from calendario_academico " .
       " where id = '$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro não encontrado!");

list ( $id,
       $ref_periodo,
       $dia_semana,
       $data_aula) = $query->GetRowValues();

$query->Close();
$conn->Close();

</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/calendario_academico_altera.php3" name="myform">
  <table border="0" width="90%" align="center" cellspacing="2" height="40" align="center">
    <tr bgcolor="#000099" align "center">
      <td height="35" colspan="2" align="center">
        <font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Altera&ccedil;&atilde;o de Data do Calendário Acadêmico</font></b></font>
      </td>
    </tr>
    <tr>
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo&nbsp;</font></td>
      <td> <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#0000FF"><? echo($id); ?>
        <input type="hidden" name="id" value="<? echo($id); ?>">
        </font></td>
    </tr> 
    <tr> 
      <td bgcolor="#CCCCFF" width="20%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Per&iacute;odo 
        </font>
      </td>
      <td width="80%"> 
        <input name="ref_periodo" type=text size="7" onChange="ChangeCode('ref_periodo','op1')" value="<?echo($ref_periodo)?>">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op1",$op1_opcoes,$ref_periodo,"ChangeOp1()");</script>
        </font>
      </td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF" width="30%"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Turno</font>
      </td>
      <td width="70%"> 
        <input name="dia_semana" type=text size="6" value="<? echo($dia_semana); ?>" onChange="ChangeCode('dia_semana','op2')">
        <font color="#000000"> 
        <script language="PHP">ComboArray("op2",$op2_opcoes,$dia_semana,"ChangeOp2()");</script>
        </font>
      </td>
    </tr>
   
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Data Aula<br>&nbsp;(dd-mm-aaaa)</font></td>
      <td> 
        <input name="data_aula" type=text value="<? echo($data_aula); ?>" size="10" maxlength="10">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1">
      </td>
    </tr>
    <tr> 
      <td align="center" colspan="2"> 
        <input type="submit" name="Submit"  value=" Salvar ">
        <input type="button" name="Submit2" value=" Voltar " onclick="javascript:history.go(-1)">
      </td>
    </tr>
  </table>
</form>
</body>
</html>
