<? require("../../../lib/common.php"); ?>
<? require("../lib/SQLCombo.php3"); ?>
<? require("../lib/InvData.php3"); ?>

<? $op_opcoes1 = SQLArray("select cod_bolsa || '  ' || descricao,id from aux_bolsas"); ?>
<html>
<head>
<script language="JavaScript">
function ChangeOption(opt,fld)
{
  var i = opt.selectedIndex;

  if ( i != -1 )
    fld.value = opt.options[i].value;
  else
    fld.value = '';
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_tipo_bolsa);
}

function ChangeCode(fld_name,op_name)
{ 
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}
</script>
<script language="JavaScript">
function Confirma_Exclui(arg1)
{
  url = 'post/delete_bolsa.php3?id=' + arg1;
  if (confirm("Você tem certeza que deseja excluir a bolsa: "+arg1))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
<script language="JavaScript">
function InsereIncentivo(periodo_id, aluno_id, contrato_id, curso_id, campus_id, bolsa_id)
{
    var url = "/financeiro/post/processa_previsoes.php3" +
              "?periodo_id=" + periodo_id +
              "&aluno_id=" + aluno_id +
              "&curso_id=" + curso_id +
              "&campus_id=" + campus_id +
              "&contrato_id=" + contrato_id +
              "&bolsa_id=" + bolsa_id;

    if (confirm("Você tem certeza que deseja ajustar os incentivos das previsões de lançamento \ndo aluno "+aluno_id+" do Curso "+curso_id+" no Campus "+campus_id+ " e no período " +periodo_id+ "?"))
        location=(url);
    else
        alert("Cancelar OK.");
}
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<table width="100%" border=0 cellpadding=2 cellspacing=1 align=center>
<script language="PHP">

CheckFormParameters(array("ref_pessoa","ref_periodo"));

$conn = new Connection;
$conn->Open();

$sql = "select pessoa_nome('$ref_pessoa')";
$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

if ($query->MoveNext())
{
  list ($aluno_nome) = $query->GetRowValues();
}

$query->Close();
$conn->Close();
</script> 
  <tr> 
    <td height=32 bgcolor="#000099" colspan=9><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Incentivos de </b></font><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2" color="#CCCCFF"><? echo("$aluno_nome"); ?>&nbsp;</font></b></font>
    </td>
  </tr>
  <tr bgcolor="#000000">
    <td colspan=4><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>C&oacute;digo</b></font></td>
    <td><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Contrato</b></font></td>
    <td> 
      <div align="center"><font face="Verdana" size="2" color="#ffffff"><b>In&iacute;cio</b></font></div>
    </td>
    <td><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Validade</b></font></td>
    <td><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Tipo de Bolsa</b></font></td>
    <td><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>%</b></font></td>
  </tr>
  <script language="PHP">

$conn = new Connection;

$conn->Open();

$sql = " select A.id," .
       "        A.ref_contrato, " .
       "        B.ref_curso, " .
       "        get_curso_abrv(B.ref_curso), " .
       "        B.ref_campus, " .
       "        A.dt_inicio," .
       "        A.dt_validade," .
       "        A.ref_pessoa," .
       "        A.ref_tipo_bolsa, " .
       "        get_bolsa(A.ref_tipo_bolsa)," .
       "        A.percentual, " .
       "        A.dt_validade >= date(now()) " .
       " from bolsas A, contratos B " .
       " where A.ref_contrato=B.id and " .
       "       A.ref_pessoa='$ref_pessoa'";

$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

for ( $row=0; $query->MoveNext(); $row++ )
{
  list ($ref_bolsa,
        $ref_contrato,
        $ref_curso,
        $curso_desc,
        $ref_campus,
        $dt_inicio,
        $dt_validade,
        $ref_pessoa,
        $ref_tipo_bolsa,
        $tipo_bolsa,
        $percentual,
        $fl_validade) = $query->GetRowValues();

  $dt_inicio = InvData($dt_inicio);
  $dt_validade = InvData($dt_validade);

  if ( ( $row % 2 ) == 0 )
  {
      $bg = '#FFFFEE';
  }
  else
  {
      $bg = '#EEEEFF';
  }

  </script>
  <tr bgcolor=<?echo($bg)?>>
    <td><font face="Verdana" size="2" color="#000099"><?echo("$ref_bolsa")?></td>
    
    <script language="PHP">
    if ($fl_validade == 't')
    {
        echo("<td><a href=\"javascript:InsereIncentivo('$ref_periodo','$ref_pessoa','$ref_contrato', '$ref_curso','$ref_campus','$ref_bolsa')\"><img src=\"../images/previsao.gif\" border=0 title=\"Atualizar Previsões\"></a></td>");
    }
    else
    {
        echo("<td><font face=\"Verdana\" size=\"2\" color=\"#000099\">&nbsp;</td>");
    }
    
    echo("<td><a href=\"/financeiro/alter_bolsa.phtml?id=". $ref_bolsa.  " \"><img src=\"../images/update.gif\" border=0 title=\"Alterar Incentivo\"></a></td>");
    echo("<td><a href=\"javascript:Confirma_Exclui('$ref_bolsa') \"><img src=\"../images/delete.gif\" border=0 title=\"Deletar Incentivo\"></a></td>");
    </script>
    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo("<a href=\"/academico/alterar_contrato.phtml?id=$ref_contrato\"> <img src=\"../images/select.gif\" title=\"$ref_curso - $curso_desc\" border=0></a> $ref_contrato");?></font></div>
    </td>
    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_inicio);?></font></div>
    </td>
    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_validade);?>&nbsp;</font></div>
    </td>
    <td><font face="Verdana" size="2" color="#000099"><?echo("$ref_tipo_bolsa - $tipo_bolsa");?></font></td>
    <td> 
      <div align="right"><font face="Verdana" size="2" color="#000099"><?echo($percentual);?>&nbsp;</font></div>
    </td>
  </tr>
  <script language="PHP">
}

$query->Close();

$conn->Close();

</script>
</table>

<center>

<? echo("<a href=\"/financeiro/bolsa_inclui.phtml?ref_pessoa=" . $ref_pessoa . " \"> [Dar Incentivo]</a>"); ?>

</center>

  </body>
</html>
