<? require("../../../lib/common.php"); ?>
<? require("../lib/InvData.php3"); ?>
<html>
<head>
<title><? echo($aluno_nome); ?></title>
</head>
<body bgcolor="#FFFFFF">
<table border=0 cellpadding=2 cellspacing=1 align=center width="750">
  <tr> 
    <td height=32 bgcolor="#000099" colspan="7"><font face="Verdana" size="3" color="#ffffff">&nbsp;<b>Matriculas</b></font> 
  </tr>
  <tr bgcolor="#000000"> 
    <td height="21"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Código</b></font></td>
    <td height="21"><font face="Verdana" size="2" color="#ffffff"><b>Disciplina</b></font></td>
    <td height="21" align="center"><font face="Verdana" size="2" color="#ffffff"><b>Data Matrícula</b></font></td>
    <td height="21" align="center"><font face="Verdana" size="2" color="#ffffff"><b>Data Cancel.</b></font></td>
    <td height="21" align="center"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Disciplina Oferecida</b></font></td>
    <td height="21" colspan="2" align="center"><font face="Verdana" size="2" color="#ffffff">&nbsp;<b>Curso Subst.</b></font><font face="Verdana" size="2" color="#ffffff"></font></td>
  </tr>
  <script language="PHP">


$conn = new Connection;

$conn->Open();

$sql = " select A.id, " .
       "        A.ref_campus, " .
       "	    get_creditos(A.ref_disciplina)," .
       "    	A.ref_disciplina, " .
       "	    descricao_disciplina(A.ref_disciplina)," .
       "	    A.ref_curso_subst, " .
       "	    curso_desc(A.ref_curso_subst)," .
       "	    A.ref_disciplina_subst, " .
       "	    descricao_disciplina(A.ref_disciplina_subst)," .
       "	    A.ref_disciplina_ofer, " .
       "	    dia_disciplina_ofer_todos(B.id), " .
       "	    A.dt_cancelamento is not null, " .
       "        A.dt_matricula, " .
       "        A.dt_cancelamento " .
       " from matricula A, disciplinas_ofer B" .
       " where A.ref_contrato='$ref_contrato' and " .
       "	   A.ref_periodo='$ref_periodo' and " .
       "  	   A.ref_disciplina_ofer = B.id";

$query = $conn->CreateQuery($sql);

SaguAssert($query,"Nao foi possivel executar a consulta!");

for ( $row=0; $query->MoveNext(); $row++ )
{
  list ($id, 
      	$ref_campus, 
	    $num_creditos,
        $ref_disciplina,
    	$descricao_disciplina,
        $ref_curso_subst,
	    $curso_desc,
        $ref_disciplina_subst,
    	$descricao_disciplina_subst,
        $ref_disciplina_ofer,
	    $dia_semana,
	    $is_cancelada,
        $dt_matricula,
        $dt_cancelamento) = $query->GetRowValues();

  $dt_matricula = InvData($dt_matricula);
  $dt_cancelamento = InvData($dt_cancelamento);
  
  if ( ( $row % 2 ) == 0 )
  {

</script>
  <tr bgcolor="#FFFFEE" valign="middle"> 
    <td><font face="Verdana" size="2" color="#000099"><?
if ($is_cancelada == 't')
{
echo('<font color=red>[C]&nbsp;</font>' . $id);
}
else
{
echo('<font color=red>[N]&nbsp;</font>' . $id);
}
?></font></td>
    <td><font face="Verdana" size="2" color="#000099"><?php 
if ($ref_campus != '1')
{
echo("<img src=\"../images/checkoff.gif\" title=\"fora sede\">");
}
else
{
echo("<img src=\"../images/checkon.gif\" title=\"na da sede\">");
}
?><font size="1"><?echo($ref_disciplina . ' - ' . substr($descricao_disciplina,0,30));?>&nbsp;</font></font></td>
    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_matricula);?>&nbsp;</font></div>
    </td>

    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_cancelamento);?>&nbsp;</font></div>
    </td>
    <td> 
      <div align="right"><font face="Verdana" size="2" color="#FF0033"><?echo("[" .$num_creditos . "]");?>&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_ofer);?><font color="#FF3333">&nbsp;<?echo(' dia ' . $dia_semana);?></font>&nbsp;</font></div>
    </td>
    <td> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$curso_desc\">");?></font><font face="Verdana" size="2" color="#FF0033">&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo("$ref_curso_subst");?></font></div>
    </td>
    <td> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$descricao_disciplina_subst\">");?>&nbsp;<font color="#FF0000">disc&nbsp;</font><?echo($ref_disciplina_subst);?></font></div>
    </td>
  </tr>
  <script language="PHP">

  }

  else
  {

</script>
  <tr bgcolor="#EEEEFF" valign="middle"> 
    <td><font face="Verdana" size="2" color="#000099"><?
if ($is_cancelada == 't')
{
echo('<font color=red> [C] </font> ' . $id);
}
else
{
echo('<font color=red> [N] </font> ' . $id);
}
?></font></td>
    <td><font face="Verdana" size="2" color="#000099"><?php 
if ($ref_campus != '1')
{
echo("<img src=\"../images/checkoff.gif\" title=\"fora sede\">");
}
else
{
echo("<img src=\"../images/checkon.gif\" title=\"na da sede\">");
}
?><font size="1"><?echo($ref_disciplina . ' - ' . substr($descricao_disciplina,0,30));?>&nbsp;</font></font></td>
    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_matricula);?>&nbsp;</font></div>
    </td>

    <td> 
      <div align="center"><font face="Verdana" size="2" color="#000099"><?echo($dt_cancelamento);?>&nbsp;</font></div>
    </td>    
    <td> 
      <div align="right"><font face="Verdana" size="2" color="#FF0033"><?echo("[" .$num_creditos . "]");?>&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_ofer);?><font color="#FF3333">&nbsp;<?echo(' dia ' . $dia_semana);?></font><font color="#FF0000">&nbsp;</font></font></div>
    </td>
    <td> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$curso_desc\">");?></font><font face="Verdana" size="2" color="#FF0000">&nbsp;</font><font face="Verdana" size="2" color="#000099"><?echo("$ref_curso_subst");?></font></div>
    </td>
    <td> 
      <div align="left"><font face="Verdana" size="2" color="#000099"><?echo("<img src=\"../images/info.gif\" title=\"$descricao_disciplina_subst\">");?>&nbsp;<font color="#FF0000">disc&nbsp;</font></font><font face="Verdana" size="2" color="#000099"><?echo($ref_disciplina_subst);?></font></div>
    </td>
  </tr>
  <script language="PHP">

  }
}

$query->Close();

$conn->Close();

</script>
</table>


<p>&nbsp;</p></body>
</html>
