<html>
<head>
<title>Cadastro de Convênio Médico</title></head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20">
<form method="post" action="post/convenio_inclui.php3" name="myform">
  <table width="90%" align="center">
    <tr> 
      <td bgcolor="#000099" colspan="2" height="28" align="center"> <font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#CCCCFF"><b>&nbsp;Inclus&atilde;o de Convênio Médico</b></font></td>
    </tr>
    <tr> 
      <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nome&nbsp;</font></td>
      <td> 
        <input name="nome" type=text size="40">
      </td>
    </tr>
    <tr> 
      <td colspan="2"> 
        <hr size="1" width="100%">
      </td>
    </tr>
    <tr> 
      <td colspan="2" align="center"> 
        <input type="submit" name="Submit"   value=" Salvar ">
        <input type="reset"  name="Submit2"  value=" Limpar ">
        <input type="button" name="Submit22" value=" Voltar " onclick="javascript:window.close()">
      </td>
    </tr>
  </table>
  </form>
  </body>
</html>
