<? require("../../../lib/common.php"); ?>
<html>
<head>
</head>
<body bgcolor=white>
<?
  flush();
  $conn = new Connection;
  $conn->Open();

  $sql= "select tablename from pg_tables where substr(tablename,1,2)<>'pg' order by tablename";
  $query = $conn->CreateQuery($sql);
  echo "<table>\n";
  echo "<tr bgcolor=\"#CCCCFF\"><td colspan=2><b> Qtde de Registros das Tabelas </b></td></tr> \n";

  while( $query->MoveNext() )
  {
    $table = $query->GetValue(1);

    $sql2= "select count(*) from $table";
    
    $query2 = $conn->CreateQuery($sql2);
    
    $query2->MoveNext();

    $qtde = $query2->GetValue(1);

    $qtde_total += $qtde;

    echo "<tr><td><font face=arial><b>$table </b></td></td> <td align=right> $qtde</td></tr> \n";

  }
  echo "<tr bgcolor=\"#CCCCFF\"><td><b>Qtde total </b></td><td> $qtde_total</td></tr> \n";
  echo "</table>\n";

  $query->Close();
  $conn->Close();
?>
</body>
</html>
