<? require("../../../lib/common.php"); ?>
<? require("../../../lib/config.php"); ?>
<html>
<head>
<title>UNIVATES</title>
<script language="JavaScript">
function buscaPessoa()
{
  var url = '../generico/post/lista_pessoas.php3' +
            '?pnome=' + escape(document.myform.pnome.value);

  var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1,arg2)
{
    document.myform.pessoa.value = arg1;
    document.myform.pnome.value = arg2;
}
</script>
</head>

<body bgcolor="#FFFFFF" link="#FFFFFF" vlink="#FFFFFF" alink="#FFFFFF" marginwidth="20" marginheight="20">
<TABLE width="500" border="0" cellspacing="4" cellpadding="2" align="center">
    <tr bgcolor="#666699" class="dark">
      <td colspan="2">
        <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="3"><font size="4" color="#FFFFFF">Cadastros Genéricos</font></font></b></div>
      </td>
    </tr>
    <tr bgcolor="#FFCF31" class="dark">
      <td colspan="2">
        <div align="center"><b><font face="Verdana, Arial, Helvetica, sans-serif" size="3"><font size="3" color="#000099">Cadastros</font></font></b></div>
      </td>
    </tr>
    <tr>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2"><a href="paises_inclui.phtml">Pa&iacute;ses</a></font></b></font></div>
      </td>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><a href="configuracao_empresa.phtml"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><font size="2">Empresa</font></font></a></b></font></div>
      </td>
    </tr>
    <tr>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2"><a href="consulta_inclui_estados.phtml">Estados</a></font></b></font></div>
      </td>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><a href="campus_inclui.phtml"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><font size="2">Campus</font></font></a></b></font></div>
      </td>
    </tr>
    <tr>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><a href="consulta_cidades.phtml"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><font size="2">Cidades</font></font></a></b></font></div>
      </td>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2"><a href="consulta_inclui_instituicoes.phtml">Institui&ccedil;&otilde;es</a></font></b></font></div>
      </td>
    </tr>
    <!--<tr>
      <td width="50%" bgcolor="#0099FF">
      <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><a href="consulta_inclui_curso_externo.phtml"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><font size="2">Curso Externo</font></font></a></b></font></div>
      </td>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><a href="dias_inclui.phtml"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><font size="2">Dias</font></font></a></b></font></div>
      </td>
    </tr>-->
    <!--<tr>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2"><a href="turnos_inclui.phtml">Turnos</a></font></b></font></div>
      </td>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><a href="consulta_inclui_horarios.phtml"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><font size="2">Horários</font></font></a></b></font></div>
      </td>
    </tr>-->
    <!--<tr>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2"><a href="eleicoes_inclui.phtml">Eleições</a></font></b></font></div>
      </td>
      <td width="50%" bgcolor="#0099FF">
        <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif" color="#FFFFFF"><b><font size="2"><a href="consulta_inclui_calendario_academico.phtml">Calendário Acadêmico</a></font></b></font></div>
    </tr>-->
    
<!--    <tr bgcolor="#FFFFFF">
      <td width="49%" class="dark">&nbsp;</td>
      <td width="49%" class="dark">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#FFCC00" align="center" colspan="2"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b><font color="#0000CC">Consultas Diversas</font></b></font></td>
    </tr>
    <form method="post" action="" name="myform">
    <tr>
    <td colspan="2">
      <table align="center" border="0"><a name="fim"></a>
        <tr>
          <td bgcolor="#EFEFFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Pessoa</font></td>
          <td bgcolor="#FFFFEF"> 
            <input type="text" name="pessoa" size="10" maxlength="10">
            <input type="text" name="pnome" size="30" maxlength="30">
            <a href="javascript:buscaPessoa()"><img src="../images/find.gif" width="16" height="16" border="0"></a> 
          </td>
          <td bgcolor="#FFFFEF">
            <div align="center">
              <input type="submit" name="Submit" value="Pesquisa">
            </div>
          </td>
        </tr>
      </table>
    </td>-->
    </tr>
    </form>
    <tr>
      <td colspan="2" bgcolor="#FFCC00" align="center"> <a href="javascript:history.back(-1)"><b><font size="2" face="Verdana, Arial, Helvetica, sans-serif" color="#0000FF">Voltar</font></b></a> 
      </td>
    </tr>
</table>
</body>
</html>

