<? require("../../../lib/common.php"); ?>
<? require("../lib/GetPessoaNome.php3"); ?>
<? require("../lib/InvData.php3"); ?>

<html>
<head>
<title><?
list ( $nome, $tmp1, $tmp2 ) = GetPessoaNome($pessoa,true);
echo($nome);
?></title>
<script language="PHP">
function Mostra_Contratos()
{

  global $pessoa, $periodo;

  $conn = new Connection;

  $conn->Open();

  $sql = " select curso_desc(ref_curso), " .
         "        dt_ativacao,".
         "        dt_desativacao, " .
         "        ref_curso, " .
         "        id, " .
         "        ref_last_periodo, " .
         "        ref_campus||' - '|| get_campus(ref_campus), " .
         "        ref_campus, " .
         "        pessoa_nome(ref_pessoa) " .
         " from contratos".
         " where ref_pessoa='$pessoa'".
         " order by dt_ativacao";

  $query = $conn->CreateQuery($sql);

  $n = $query->GetColumnCount();

  echo("<center><table width=\"500\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

  $i=1;

  // cores fundo
  $bg0 = "#000000";
  $bg1 = "#EEEEFF";
  $bg2 = "#FFFFEE";

  // cores fonte
  $fg0 = "#FFFFFF";
  $fg1 = "#000099";
  $fg2 = "#000099";
  
  while( $query->MoveNext() )
  {

    if ($i == 1)
    {
  
      echo("<tr bgcolor=\"#000000\">\n");
      echo ("<td align=left width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;</b></font></td>");
      echo ("<td align=left width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Código</b></font></td>");
      echo ("<td width=\"56%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Curso</b></font></td>");
      echo ("<td width=\"4%\">&nbsp;</td>");
      echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Ativacao</b></font></td>");
      echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>Desativacao</b></font></td>");
      echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"#ffffff\"><b>&nbsp;</b></font></td>");
      echo("  </tr>"); 
    }

    $curso          = $query->GetValue(1);
    $dt_ativacao    = $query->GetValue(2);
    $dt_desativacao = $query->GetValue(3);
    $ref_curso      = $query->GetValue(4);
    $ref_contrato   = $query->GetValue(5);
    $ref_periodo    = $query->GetValue(6);
    $campus         = $query->GetValue(7);
    $ref_campus     = $query->GetValue(8);
    $aluno_nome     = $query->GetValue(9);
    
    $href = "<a href=\"javascript:select_contrato('$ref_contrato','$pessoa','" . urlencode($aluno_nome) . "','$ref_periodo','$ref_curso','$ref_campus')\"><img src=\"../images/select.gif\" title='Ver Contrato' align='absmiddle' border=0></a>";
    $href2 = "<a href=\"javascript:altera_contrato($ref_contrato)\"><img src=\"../images/update.gif\" title='Altera Contrato' align='absmiddle' border=0></a>";
    $img = "<img src=\"../images/select.gif\" title='$campus' align='absmiddle' border=0>";

    if ( $i % 2)
    {

       echo("<tr bgcolor=\"$bg1\">\n");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$ref_curso</td>");
       echo ("<td width=\"56%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg2\">$curso</td>");
       echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$img</td>");
       echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . InvData($dt_ativacao) . "</td>");
       echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">" . InvData($dt_desativacao) . "&nbsp;</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href2</td>");
       echo("  </tr>");

    }
    else
    {
       echo("<tr bgcolor=\"$bg2\">\n");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$ref_curso</td>");
       echo ("<td width=\"56%\"><Font face=\"Verdana\" size=\"1\" color=\"$fg1\">$curso</td>");
       echo ("<td width=\"4%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">$img</td>");
       echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . InvData($dt_ativacao) . "</td>");
       echo ("<td width=\"15%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg1\">" . InvData($dt_desativacao) . "&nbsp;</td>");
       echo ("<td width=\"5%\"><Font face=\"Verdana\" size=\"2\" color=\"$fg2\">$href2</td>");
       echo("  </tr>");
    }

    $i++;

  }

  echo("</table></center>");

  $query->Close();

  $conn->Close();
}
</script>
<script language="JavaScript">
function select_contrato(ref_contrato,ref_pessoa,aluno_nome,ref_periodo,ref_curso,ref_campus)
{
  url = '/financeiro/consulta_previsao.phtml' +
        '?ref_contrato=' + ref_contrato + 
        '&ref_pessoa=' + ref_pessoa + 
        '&aluno_nome=' + aluno_nome + 
        '&ref_periodo=' + ref_periodo +
        '&ref_curso=' + ref_curso +
        '&ref_campus=' + ref_campus;
        
  window.open(url,'contratos','resizable=yes, toolbar=no,width=680,height=400,top=50,left=80,scrollbars=yes');
}

function altera_contrato(ref_contrato)
{
  url = '/academico/alterar_contrato.phtml?id=' + ref_contrato;
  window.open(url,'contratos','resizable=yes, toolbar=no,width=680,height=400,top=50,left=80,scrollbars=yes');
}
</script>
</head>

<body bgcolor="#FFFFFF">
<table cols=2 width="500" align="center" cellpadding="0" cellspacing="0" border="1" bordercolor="#CCCCFF">
  <tr bgcolor="#FFFFFF"> 
    <td height="33" colspan="2"> 
      <div align="center"><font face="Georgia, Times New Roman, Times, serif" size="2" color="#0000CC"><b><font face="Verdana, Arial, Helvetica, sans-serif"><br>
        <font color="#FF0000">Contratos</font><br>
        <?PHP Mostra_Contratos(); ?> <br>
        </font></b></font></div>
    </td>
  </tr>
</table>
<div align="center"><br>
  <form method="post" action="">
    <input type="button" name="Submit" value="Fecha Janela" onClick="javascript:window.close();">
  </form>
</div>
</body>
</html>
